-- CreateEnum
CREATE TYPE "NewPickupStatus" AS ENUM ('PICKUP_CONFIRMED', 'PICKUP_PENDING', 'PICKUP_COMPLETED', 'PICKUP_CANCELLED', 'PICKUP_ERROR', 'PICKUP_SHIPPER', 'PICKUP_HELD', 'PICKUP_PROCESSING', 'PICKUP_REBOOKED', 'PICKUP_HIDDEN');

-- AlterTable
ALTER TABLE "Pickup" ADD COLUMN     "status" "NewPickupStatus" DEFAULT 'PICKUP_CONFIRMED';
