/**
 * @packageDocumentation
 * @module api.functional.v1.tracking.shipments.by_reference
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { TrackingFacadeResponse } from "../../../../../structures/TrackingFacadeResponse";

/**
 * @controller TrackingFacadeController.findByReference
 * @path GET /v1/tracking/shipments/by-reference/:shipmentReference
 * @accessor api.functional.v1.tracking.shipments.by_reference.findByReference
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findByReference(
  connection: IConnection,
  shipmentReference: string,
): Promise<findByReference.Output> {
  return PlainFetcher.fetch(connection, {
    ...findByReference.METADATA,
    template: findByReference.METADATA.path,
    path: findByReference.path(shipmentReference),
  });
}
export namespace findByReference {
  export type Output = TrackingFacadeResponse;

  export const METADATA = {
    method: "GET",
    path: "/v1/tracking/shipments/by-reference/:shipmentReference",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (shipmentReference: string) =>
    `/v1/tracking/shipments/by-reference/${encodeURIComponent(
      shipmentReference?.toString() ?? "null",
    )}`;
}
