
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CustomerGroupServicePrintingPreference` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CustomerGroupServicePrintingPreference
 * 
 */
export type CustomerGroupServicePrintingPreferenceModel = runtime.Types.Result.DefaultSelection<Prisma.$CustomerGroupServicePrintingPreferencePayload>

export type AggregateCustomerGroupServicePrintingPreference = {
  _count: CustomerGroupServicePrintingPreferenceCountAggregateOutputType | null
  _avg: CustomerGroupServicePrintingPreferenceAvgAggregateOutputType | null
  _sum: CustomerGroupServicePrintingPreferenceSumAggregateOutputType | null
  _min: CustomerGroupServicePrintingPreferenceMinAggregateOutputType | null
  _max: CustomerGroupServicePrintingPreferenceMaxAggregateOutputType | null
}

export type CustomerGroupServicePrintingPreferenceAvgAggregateOutputType = {
  labels: number | null
  cubic: number | null
  rangeLeft: number | null
}

export type CustomerGroupServicePrintingPreferenceSumAggregateOutputType = {
  labels: number | null
  cubic: number | null
  rangeLeft: number | null
}

export type CustomerGroupServicePrintingPreferenceMinAggregateOutputType = {
  id: string | null
  customerGroupId: string | null
  tenantId: string | null
  carrierId: string | null
  carrierName: string | null
  serviceId: string | null
  serviceCode: string | null
  serviceName: string | null
  recordName: string | null
  labelPrinterId: string | null
  labelPrinterName: string | null
  labels: number | null
  printerType: string | null
  specialInstructions: string | null
  cubic: number | null
  rangeLeft: number | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CustomerGroupServicePrintingPreferenceMaxAggregateOutputType = {
  id: string | null
  customerGroupId: string | null
  tenantId: string | null
  carrierId: string | null
  carrierName: string | null
  serviceId: string | null
  serviceCode: string | null
  serviceName: string | null
  recordName: string | null
  labelPrinterId: string | null
  labelPrinterName: string | null
  labels: number | null
  printerType: string | null
  specialInstructions: string | null
  cubic: number | null
  rangeLeft: number | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CustomerGroupServicePrintingPreferenceCountAggregateOutputType = {
  id: number
  customerGroupId: number
  tenantId: number
  carrierId: number
  carrierName: number
  serviceId: number
  serviceCode: number
  serviceName: number
  recordName: number
  labelPrinterId: number
  labelPrinterName: number
  labels: number
  printerType: number
  specialInstructions: number
  cubic: number
  rangeLeft: number
  notes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CustomerGroupServicePrintingPreferenceAvgAggregateInputType = {
  labels?: true
  cubic?: true
  rangeLeft?: true
}

export type CustomerGroupServicePrintingPreferenceSumAggregateInputType = {
  labels?: true
  cubic?: true
  rangeLeft?: true
}

export type CustomerGroupServicePrintingPreferenceMinAggregateInputType = {
  id?: true
  customerGroupId?: true
  tenantId?: true
  carrierId?: true
  carrierName?: true
  serviceId?: true
  serviceCode?: true
  serviceName?: true
  recordName?: true
  labelPrinterId?: true
  labelPrinterName?: true
  labels?: true
  printerType?: true
  specialInstructions?: true
  cubic?: true
  rangeLeft?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type CustomerGroupServicePrintingPreferenceMaxAggregateInputType = {
  id?: true
  customerGroupId?: true
  tenantId?: true
  carrierId?: true
  carrierName?: true
  serviceId?: true
  serviceCode?: true
  serviceName?: true
  recordName?: true
  labelPrinterId?: true
  labelPrinterName?: true
  labels?: true
  printerType?: true
  specialInstructions?: true
  cubic?: true
  rangeLeft?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type CustomerGroupServicePrintingPreferenceCountAggregateInputType = {
  id?: true
  customerGroupId?: true
  tenantId?: true
  carrierId?: true
  carrierName?: true
  serviceId?: true
  serviceCode?: true
  serviceName?: true
  recordName?: true
  labelPrinterId?: true
  labelPrinterName?: true
  labels?: true
  printerType?: true
  specialInstructions?: true
  cubic?: true
  rangeLeft?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CustomerGroupServicePrintingPreferenceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CustomerGroupServicePrintingPreference to aggregate.
   */
  where?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomerGroupServicePrintingPreferences to fetch.
   */
  orderBy?: Prisma.CustomerGroupServicePrintingPreferenceOrderByWithRelationInput | Prisma.CustomerGroupServicePrintingPreferenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomerGroupServicePrintingPreferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomerGroupServicePrintingPreferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CustomerGroupServicePrintingPreferences
  **/
  _count?: true | CustomerGroupServicePrintingPreferenceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CustomerGroupServicePrintingPreferenceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CustomerGroupServicePrintingPreferenceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CustomerGroupServicePrintingPreferenceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CustomerGroupServicePrintingPreferenceMaxAggregateInputType
}

export type GetCustomerGroupServicePrintingPreferenceAggregateType<T extends CustomerGroupServicePrintingPreferenceAggregateArgs> = {
      [P in keyof T & keyof AggregateCustomerGroupServicePrintingPreference]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCustomerGroupServicePrintingPreference[P]>
    : Prisma.GetScalarType<T[P], AggregateCustomerGroupServicePrintingPreference[P]>
}




export type CustomerGroupServicePrintingPreferenceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput
  orderBy?: Prisma.CustomerGroupServicePrintingPreferenceOrderByWithAggregationInput | Prisma.CustomerGroupServicePrintingPreferenceOrderByWithAggregationInput[]
  by: Prisma.CustomerGroupServicePrintingPreferenceScalarFieldEnum[] | Prisma.CustomerGroupServicePrintingPreferenceScalarFieldEnum
  having?: Prisma.CustomerGroupServicePrintingPreferenceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CustomerGroupServicePrintingPreferenceCountAggregateInputType | true
  _avg?: CustomerGroupServicePrintingPreferenceAvgAggregateInputType
  _sum?: CustomerGroupServicePrintingPreferenceSumAggregateInputType
  _min?: CustomerGroupServicePrintingPreferenceMinAggregateInputType
  _max?: CustomerGroupServicePrintingPreferenceMaxAggregateInputType
}

export type CustomerGroupServicePrintingPreferenceGroupByOutputType = {
  id: string
  customerGroupId: string
  tenantId: string
  carrierId: string
  carrierName: string
  serviceId: string
  serviceCode: string | null
  serviceName: string | null
  recordName: string | null
  labelPrinterId: string | null
  labelPrinterName: string | null
  labels: number
  printerType: string | null
  specialInstructions: string | null
  cubic: number | null
  rangeLeft: number | null
  notes: string | null
  createdAt: Date
  updatedAt: Date
  _count: CustomerGroupServicePrintingPreferenceCountAggregateOutputType | null
  _avg: CustomerGroupServicePrintingPreferenceAvgAggregateOutputType | null
  _sum: CustomerGroupServicePrintingPreferenceSumAggregateOutputType | null
  _min: CustomerGroupServicePrintingPreferenceMinAggregateOutputType | null
  _max: CustomerGroupServicePrintingPreferenceMaxAggregateOutputType | null
}

export type GetCustomerGroupServicePrintingPreferenceGroupByPayload<T extends CustomerGroupServicePrintingPreferenceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CustomerGroupServicePrintingPreferenceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CustomerGroupServicePrintingPreferenceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CustomerGroupServicePrintingPreferenceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CustomerGroupServicePrintingPreferenceGroupByOutputType[P]>
      }
    >
  >



export type CustomerGroupServicePrintingPreferenceWhereInput = {
  AND?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput | Prisma.CustomerGroupServicePrintingPreferenceWhereInput[]
  OR?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput[]
  NOT?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput | Prisma.CustomerGroupServicePrintingPreferenceWhereInput[]
  id?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  customerGroupId?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  tenantId?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  carrierId?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  carrierName?: Prisma.StringFilter<"CustomerGroupServicePrintingPreference"> | string
  serviceId?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  serviceCode?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  serviceName?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  recordName?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  labelPrinterId?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  labelPrinterName?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  labels?: Prisma.IntFilter<"CustomerGroupServicePrintingPreference"> | number
  printerType?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  specialInstructions?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  cubic?: Prisma.FloatNullableFilter<"CustomerGroupServicePrintingPreference"> | number | null
  rangeLeft?: Prisma.FloatNullableFilter<"CustomerGroupServicePrintingPreference"> | number | null
  notes?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CustomerGroupServicePrintingPreference"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CustomerGroupServicePrintingPreference"> | Date | string
  customerGroup?: Prisma.XOR<Prisma.CustomerGroupScalarRelationFilter, Prisma.CustomerGroupWhereInput>
}

export type CustomerGroupServicePrintingPreferenceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  customerGroupId?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  carrierId?: Prisma.SortOrder
  carrierName?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  serviceCode?: Prisma.SortOrderInput | Prisma.SortOrder
  serviceName?: Prisma.SortOrderInput | Prisma.SortOrder
  recordName?: Prisma.SortOrderInput | Prisma.SortOrder
  labelPrinterId?: Prisma.SortOrderInput | Prisma.SortOrder
  labelPrinterName?: Prisma.SortOrderInput | Prisma.SortOrder
  labels?: Prisma.SortOrder
  printerType?: Prisma.SortOrderInput | Prisma.SortOrder
  specialInstructions?: Prisma.SortOrderInput | Prisma.SortOrder
  cubic?: Prisma.SortOrderInput | Prisma.SortOrder
  rangeLeft?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  customerGroup?: Prisma.CustomerGroupOrderByWithRelationInput
}

export type CustomerGroupServicePrintingPreferenceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  customerGroupId_serviceId?: Prisma.CustomerGroupServicePrintingPreferenceCustomerGroupIdServiceIdCompoundUniqueInput
  AND?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput | Prisma.CustomerGroupServicePrintingPreferenceWhereInput[]
  OR?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput[]
  NOT?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput | Prisma.CustomerGroupServicePrintingPreferenceWhereInput[]
  customerGroupId?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  tenantId?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  carrierId?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  carrierName?: Prisma.StringFilter<"CustomerGroupServicePrintingPreference"> | string
  serviceId?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  serviceCode?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  serviceName?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  recordName?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  labelPrinterId?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  labelPrinterName?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  labels?: Prisma.IntFilter<"CustomerGroupServicePrintingPreference"> | number
  printerType?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  specialInstructions?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  cubic?: Prisma.FloatNullableFilter<"CustomerGroupServicePrintingPreference"> | number | null
  rangeLeft?: Prisma.FloatNullableFilter<"CustomerGroupServicePrintingPreference"> | number | null
  notes?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CustomerGroupServicePrintingPreference"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CustomerGroupServicePrintingPreference"> | Date | string
  customerGroup?: Prisma.XOR<Prisma.CustomerGroupScalarRelationFilter, Prisma.CustomerGroupWhereInput>
}, "id" | "customerGroupId_serviceId">

export type CustomerGroupServicePrintingPreferenceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  customerGroupId?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  carrierId?: Prisma.SortOrder
  carrierName?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  serviceCode?: Prisma.SortOrderInput | Prisma.SortOrder
  serviceName?: Prisma.SortOrderInput | Prisma.SortOrder
  recordName?: Prisma.SortOrderInput | Prisma.SortOrder
  labelPrinterId?: Prisma.SortOrderInput | Prisma.SortOrder
  labelPrinterName?: Prisma.SortOrderInput | Prisma.SortOrder
  labels?: Prisma.SortOrder
  printerType?: Prisma.SortOrderInput | Prisma.SortOrder
  specialInstructions?: Prisma.SortOrderInput | Prisma.SortOrder
  cubic?: Prisma.SortOrderInput | Prisma.SortOrder
  rangeLeft?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CustomerGroupServicePrintingPreferenceCountOrderByAggregateInput
  _avg?: Prisma.CustomerGroupServicePrintingPreferenceAvgOrderByAggregateInput
  _max?: Prisma.CustomerGroupServicePrintingPreferenceMaxOrderByAggregateInput
  _min?: Prisma.CustomerGroupServicePrintingPreferenceMinOrderByAggregateInput
  _sum?: Prisma.CustomerGroupServicePrintingPreferenceSumOrderByAggregateInput
}

export type CustomerGroupServicePrintingPreferenceScalarWhereWithAggregatesInput = {
  AND?: Prisma.CustomerGroupServicePrintingPreferenceScalarWhereWithAggregatesInput | Prisma.CustomerGroupServicePrintingPreferenceScalarWhereWithAggregatesInput[]
  OR?: Prisma.CustomerGroupServicePrintingPreferenceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CustomerGroupServicePrintingPreferenceScalarWhereWithAggregatesInput | Prisma.CustomerGroupServicePrintingPreferenceScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string
  customerGroupId?: Prisma.UuidWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string
  tenantId?: Prisma.UuidWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string
  carrierId?: Prisma.UuidWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string
  carrierName?: Prisma.StringWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string
  serviceId?: Prisma.UuidWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string
  serviceCode?: Prisma.StringNullableWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string | null
  serviceName?: Prisma.StringNullableWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string | null
  recordName?: Prisma.StringNullableWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string | null
  labelPrinterId?: Prisma.StringNullableWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string | null
  labelPrinterName?: Prisma.StringNullableWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string | null
  labels?: Prisma.IntWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | number
  printerType?: Prisma.StringNullableWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string | null
  specialInstructions?: Prisma.StringNullableWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string | null
  cubic?: Prisma.FloatNullableWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | number | null
  rangeLeft?: Prisma.FloatNullableWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | number | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CustomerGroupServicePrintingPreference"> | Date | string
}

export type CustomerGroupServicePrintingPreferenceCreateInput = {
  id?: string
  tenantId: string
  carrierId: string
  carrierName: string
  serviceId: string
  serviceCode?: string | null
  serviceName?: string | null
  recordName?: string | null
  labelPrinterId?: string | null
  labelPrinterName?: string | null
  labels?: number
  printerType?: string | null
  specialInstructions?: string | null
  cubic?: number | null
  rangeLeft?: number | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  customerGroup: Prisma.CustomerGroupCreateNestedOneWithoutServicePrintingPreferencesInput
}

export type CustomerGroupServicePrintingPreferenceUncheckedCreateInput = {
  id?: string
  customerGroupId: string
  tenantId: string
  carrierId: string
  carrierName: string
  serviceId: string
  serviceCode?: string | null
  serviceName?: string | null
  recordName?: string | null
  labelPrinterId?: string | null
  labelPrinterName?: string | null
  labels?: number
  printerType?: string | null
  specialInstructions?: string | null
  cubic?: number | null
  rangeLeft?: number | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerGroupServicePrintingPreferenceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierName?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  serviceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recordName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labels?: Prisma.IntFieldUpdateOperationsInput | number
  printerType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cubic?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rangeLeft?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customerGroup?: Prisma.CustomerGroupUpdateOneRequiredWithoutServicePrintingPreferencesNestedInput
}

export type CustomerGroupServicePrintingPreferenceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  customerGroupId?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierName?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  serviceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recordName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labels?: Prisma.IntFieldUpdateOperationsInput | number
  printerType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cubic?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rangeLeft?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerGroupServicePrintingPreferenceCreateManyInput = {
  id?: string
  customerGroupId: string
  tenantId: string
  carrierId: string
  carrierName: string
  serviceId: string
  serviceCode?: string | null
  serviceName?: string | null
  recordName?: string | null
  labelPrinterId?: string | null
  labelPrinterName?: string | null
  labels?: number
  printerType?: string | null
  specialInstructions?: string | null
  cubic?: number | null
  rangeLeft?: number | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerGroupServicePrintingPreferenceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierName?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  serviceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recordName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labels?: Prisma.IntFieldUpdateOperationsInput | number
  printerType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cubic?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rangeLeft?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerGroupServicePrintingPreferenceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  customerGroupId?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierName?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  serviceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recordName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labels?: Prisma.IntFieldUpdateOperationsInput | number
  printerType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cubic?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rangeLeft?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerGroupServicePrintingPreferenceListRelationFilter = {
  every?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput
  some?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput
  none?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput
}

export type CustomerGroupServicePrintingPreferenceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CustomerGroupServicePrintingPreferenceCustomerGroupIdServiceIdCompoundUniqueInput = {
  customerGroupId: string
  serviceId: string
}

export type CustomerGroupServicePrintingPreferenceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customerGroupId?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  carrierId?: Prisma.SortOrder
  carrierName?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  serviceCode?: Prisma.SortOrder
  serviceName?: Prisma.SortOrder
  recordName?: Prisma.SortOrder
  labelPrinterId?: Prisma.SortOrder
  labelPrinterName?: Prisma.SortOrder
  labels?: Prisma.SortOrder
  printerType?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrder
  cubic?: Prisma.SortOrder
  rangeLeft?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomerGroupServicePrintingPreferenceAvgOrderByAggregateInput = {
  labels?: Prisma.SortOrder
  cubic?: Prisma.SortOrder
  rangeLeft?: Prisma.SortOrder
}

export type CustomerGroupServicePrintingPreferenceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customerGroupId?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  carrierId?: Prisma.SortOrder
  carrierName?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  serviceCode?: Prisma.SortOrder
  serviceName?: Prisma.SortOrder
  recordName?: Prisma.SortOrder
  labelPrinterId?: Prisma.SortOrder
  labelPrinterName?: Prisma.SortOrder
  labels?: Prisma.SortOrder
  printerType?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrder
  cubic?: Prisma.SortOrder
  rangeLeft?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomerGroupServicePrintingPreferenceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customerGroupId?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  carrierId?: Prisma.SortOrder
  carrierName?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  serviceCode?: Prisma.SortOrder
  serviceName?: Prisma.SortOrder
  recordName?: Prisma.SortOrder
  labelPrinterId?: Prisma.SortOrder
  labelPrinterName?: Prisma.SortOrder
  labels?: Prisma.SortOrder
  printerType?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrder
  cubic?: Prisma.SortOrder
  rangeLeft?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomerGroupServicePrintingPreferenceSumOrderByAggregateInput = {
  labels?: Prisma.SortOrder
  cubic?: Prisma.SortOrder
  rangeLeft?: Prisma.SortOrder
}

export type CustomerGroupServicePrintingPreferenceCreateNestedManyWithoutCustomerGroupInput = {
  create?: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceCreateWithoutCustomerGroupInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedCreateWithoutCustomerGroupInput> | Prisma.CustomerGroupServicePrintingPreferenceCreateWithoutCustomerGroupInput[] | Prisma.CustomerGroupServicePrintingPreferenceUncheckedCreateWithoutCustomerGroupInput[]
  connectOrCreate?: Prisma.CustomerGroupServicePrintingPreferenceCreateOrConnectWithoutCustomerGroupInput | Prisma.CustomerGroupServicePrintingPreferenceCreateOrConnectWithoutCustomerGroupInput[]
  createMany?: Prisma.CustomerGroupServicePrintingPreferenceCreateManyCustomerGroupInputEnvelope
  connect?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput | Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput[]
}

export type CustomerGroupServicePrintingPreferenceUncheckedCreateNestedManyWithoutCustomerGroupInput = {
  create?: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceCreateWithoutCustomerGroupInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedCreateWithoutCustomerGroupInput> | Prisma.CustomerGroupServicePrintingPreferenceCreateWithoutCustomerGroupInput[] | Prisma.CustomerGroupServicePrintingPreferenceUncheckedCreateWithoutCustomerGroupInput[]
  connectOrCreate?: Prisma.CustomerGroupServicePrintingPreferenceCreateOrConnectWithoutCustomerGroupInput | Prisma.CustomerGroupServicePrintingPreferenceCreateOrConnectWithoutCustomerGroupInput[]
  createMany?: Prisma.CustomerGroupServicePrintingPreferenceCreateManyCustomerGroupInputEnvelope
  connect?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput | Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput[]
}

export type CustomerGroupServicePrintingPreferenceUpdateManyWithoutCustomerGroupNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceCreateWithoutCustomerGroupInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedCreateWithoutCustomerGroupInput> | Prisma.CustomerGroupServicePrintingPreferenceCreateWithoutCustomerGroupInput[] | Prisma.CustomerGroupServicePrintingPreferenceUncheckedCreateWithoutCustomerGroupInput[]
  connectOrCreate?: Prisma.CustomerGroupServicePrintingPreferenceCreateOrConnectWithoutCustomerGroupInput | Prisma.CustomerGroupServicePrintingPreferenceCreateOrConnectWithoutCustomerGroupInput[]
  upsert?: Prisma.CustomerGroupServicePrintingPreferenceUpsertWithWhereUniqueWithoutCustomerGroupInput | Prisma.CustomerGroupServicePrintingPreferenceUpsertWithWhereUniqueWithoutCustomerGroupInput[]
  createMany?: Prisma.CustomerGroupServicePrintingPreferenceCreateManyCustomerGroupInputEnvelope
  set?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput | Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput[]
  disconnect?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput | Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput[]
  delete?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput | Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput[]
  connect?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput | Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput[]
  update?: Prisma.CustomerGroupServicePrintingPreferenceUpdateWithWhereUniqueWithoutCustomerGroupInput | Prisma.CustomerGroupServicePrintingPreferenceUpdateWithWhereUniqueWithoutCustomerGroupInput[]
  updateMany?: Prisma.CustomerGroupServicePrintingPreferenceUpdateManyWithWhereWithoutCustomerGroupInput | Prisma.CustomerGroupServicePrintingPreferenceUpdateManyWithWhereWithoutCustomerGroupInput[]
  deleteMany?: Prisma.CustomerGroupServicePrintingPreferenceScalarWhereInput | Prisma.CustomerGroupServicePrintingPreferenceScalarWhereInput[]
}

export type CustomerGroupServicePrintingPreferenceUncheckedUpdateManyWithoutCustomerGroupNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceCreateWithoutCustomerGroupInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedCreateWithoutCustomerGroupInput> | Prisma.CustomerGroupServicePrintingPreferenceCreateWithoutCustomerGroupInput[] | Prisma.CustomerGroupServicePrintingPreferenceUncheckedCreateWithoutCustomerGroupInput[]
  connectOrCreate?: Prisma.CustomerGroupServicePrintingPreferenceCreateOrConnectWithoutCustomerGroupInput | Prisma.CustomerGroupServicePrintingPreferenceCreateOrConnectWithoutCustomerGroupInput[]
  upsert?: Prisma.CustomerGroupServicePrintingPreferenceUpsertWithWhereUniqueWithoutCustomerGroupInput | Prisma.CustomerGroupServicePrintingPreferenceUpsertWithWhereUniqueWithoutCustomerGroupInput[]
  createMany?: Prisma.CustomerGroupServicePrintingPreferenceCreateManyCustomerGroupInputEnvelope
  set?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput | Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput[]
  disconnect?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput | Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput[]
  delete?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput | Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput[]
  connect?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput | Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput[]
  update?: Prisma.CustomerGroupServicePrintingPreferenceUpdateWithWhereUniqueWithoutCustomerGroupInput | Prisma.CustomerGroupServicePrintingPreferenceUpdateWithWhereUniqueWithoutCustomerGroupInput[]
  updateMany?: Prisma.CustomerGroupServicePrintingPreferenceUpdateManyWithWhereWithoutCustomerGroupInput | Prisma.CustomerGroupServicePrintingPreferenceUpdateManyWithWhereWithoutCustomerGroupInput[]
  deleteMany?: Prisma.CustomerGroupServicePrintingPreferenceScalarWhereInput | Prisma.CustomerGroupServicePrintingPreferenceScalarWhereInput[]
}

export type CustomerGroupServicePrintingPreferenceCreateWithoutCustomerGroupInput = {
  id?: string
  tenantId: string
  carrierId: string
  carrierName: string
  serviceId: string
  serviceCode?: string | null
  serviceName?: string | null
  recordName?: string | null
  labelPrinterId?: string | null
  labelPrinterName?: string | null
  labels?: number
  printerType?: string | null
  specialInstructions?: string | null
  cubic?: number | null
  rangeLeft?: number | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerGroupServicePrintingPreferenceUncheckedCreateWithoutCustomerGroupInput = {
  id?: string
  tenantId: string
  carrierId: string
  carrierName: string
  serviceId: string
  serviceCode?: string | null
  serviceName?: string | null
  recordName?: string | null
  labelPrinterId?: string | null
  labelPrinterName?: string | null
  labels?: number
  printerType?: string | null
  specialInstructions?: string | null
  cubic?: number | null
  rangeLeft?: number | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerGroupServicePrintingPreferenceCreateOrConnectWithoutCustomerGroupInput = {
  where: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceCreateWithoutCustomerGroupInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedCreateWithoutCustomerGroupInput>
}

export type CustomerGroupServicePrintingPreferenceCreateManyCustomerGroupInputEnvelope = {
  data: Prisma.CustomerGroupServicePrintingPreferenceCreateManyCustomerGroupInput | Prisma.CustomerGroupServicePrintingPreferenceCreateManyCustomerGroupInput[]
  skipDuplicates?: boolean
}

export type CustomerGroupServicePrintingPreferenceUpsertWithWhereUniqueWithoutCustomerGroupInput = {
  where: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput
  update: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceUpdateWithoutCustomerGroupInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedUpdateWithoutCustomerGroupInput>
  create: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceCreateWithoutCustomerGroupInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedCreateWithoutCustomerGroupInput>
}

export type CustomerGroupServicePrintingPreferenceUpdateWithWhereUniqueWithoutCustomerGroupInput = {
  where: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput
  data: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceUpdateWithoutCustomerGroupInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedUpdateWithoutCustomerGroupInput>
}

export type CustomerGroupServicePrintingPreferenceUpdateManyWithWhereWithoutCustomerGroupInput = {
  where: Prisma.CustomerGroupServicePrintingPreferenceScalarWhereInput
  data: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceUpdateManyMutationInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedUpdateManyWithoutCustomerGroupInput>
}

export type CustomerGroupServicePrintingPreferenceScalarWhereInput = {
  AND?: Prisma.CustomerGroupServicePrintingPreferenceScalarWhereInput | Prisma.CustomerGroupServicePrintingPreferenceScalarWhereInput[]
  OR?: Prisma.CustomerGroupServicePrintingPreferenceScalarWhereInput[]
  NOT?: Prisma.CustomerGroupServicePrintingPreferenceScalarWhereInput | Prisma.CustomerGroupServicePrintingPreferenceScalarWhereInput[]
  id?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  customerGroupId?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  tenantId?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  carrierId?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  carrierName?: Prisma.StringFilter<"CustomerGroupServicePrintingPreference"> | string
  serviceId?: Prisma.UuidFilter<"CustomerGroupServicePrintingPreference"> | string
  serviceCode?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  serviceName?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  recordName?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  labelPrinterId?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  labelPrinterName?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  labels?: Prisma.IntFilter<"CustomerGroupServicePrintingPreference"> | number
  printerType?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  specialInstructions?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  cubic?: Prisma.FloatNullableFilter<"CustomerGroupServicePrintingPreference"> | number | null
  rangeLeft?: Prisma.FloatNullableFilter<"CustomerGroupServicePrintingPreference"> | number | null
  notes?: Prisma.StringNullableFilter<"CustomerGroupServicePrintingPreference"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CustomerGroupServicePrintingPreference"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CustomerGroupServicePrintingPreference"> | Date | string
}

export type CustomerGroupServicePrintingPreferenceCreateManyCustomerGroupInput = {
  id?: string
  tenantId: string
  carrierId: string
  carrierName: string
  serviceId: string
  serviceCode?: string | null
  serviceName?: string | null
  recordName?: string | null
  labelPrinterId?: string | null
  labelPrinterName?: string | null
  labels?: number
  printerType?: string | null
  specialInstructions?: string | null
  cubic?: number | null
  rangeLeft?: number | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerGroupServicePrintingPreferenceUpdateWithoutCustomerGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierName?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  serviceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recordName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labels?: Prisma.IntFieldUpdateOperationsInput | number
  printerType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cubic?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rangeLeft?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerGroupServicePrintingPreferenceUncheckedUpdateWithoutCustomerGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierName?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  serviceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recordName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labels?: Prisma.IntFieldUpdateOperationsInput | number
  printerType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cubic?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rangeLeft?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerGroupServicePrintingPreferenceUncheckedUpdateManyWithoutCustomerGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierId?: Prisma.StringFieldUpdateOperationsInput | string
  carrierName?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  serviceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recordName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labelPrinterName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  labels?: Prisma.IntFieldUpdateOperationsInput | number
  printerType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cubic?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rangeLeft?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CustomerGroupServicePrintingPreferenceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customerGroupId?: boolean
  tenantId?: boolean
  carrierId?: boolean
  carrierName?: boolean
  serviceId?: boolean
  serviceCode?: boolean
  serviceName?: boolean
  recordName?: boolean
  labelPrinterId?: boolean
  labelPrinterName?: boolean
  labels?: boolean
  printerType?: boolean
  specialInstructions?: boolean
  cubic?: boolean
  rangeLeft?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  customerGroup?: boolean | Prisma.CustomerGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customerGroupServicePrintingPreference"]>

export type CustomerGroupServicePrintingPreferenceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customerGroupId?: boolean
  tenantId?: boolean
  carrierId?: boolean
  carrierName?: boolean
  serviceId?: boolean
  serviceCode?: boolean
  serviceName?: boolean
  recordName?: boolean
  labelPrinterId?: boolean
  labelPrinterName?: boolean
  labels?: boolean
  printerType?: boolean
  specialInstructions?: boolean
  cubic?: boolean
  rangeLeft?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  customerGroup?: boolean | Prisma.CustomerGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customerGroupServicePrintingPreference"]>

export type CustomerGroupServicePrintingPreferenceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customerGroupId?: boolean
  tenantId?: boolean
  carrierId?: boolean
  carrierName?: boolean
  serviceId?: boolean
  serviceCode?: boolean
  serviceName?: boolean
  recordName?: boolean
  labelPrinterId?: boolean
  labelPrinterName?: boolean
  labels?: boolean
  printerType?: boolean
  specialInstructions?: boolean
  cubic?: boolean
  rangeLeft?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  customerGroup?: boolean | Prisma.CustomerGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customerGroupServicePrintingPreference"]>

export type CustomerGroupServicePrintingPreferenceSelectScalar = {
  id?: boolean
  customerGroupId?: boolean
  tenantId?: boolean
  carrierId?: boolean
  carrierName?: boolean
  serviceId?: boolean
  serviceCode?: boolean
  serviceName?: boolean
  recordName?: boolean
  labelPrinterId?: boolean
  labelPrinterName?: boolean
  labels?: boolean
  printerType?: boolean
  specialInstructions?: boolean
  cubic?: boolean
  rangeLeft?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CustomerGroupServicePrintingPreferenceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "customerGroupId" | "tenantId" | "carrierId" | "carrierName" | "serviceId" | "serviceCode" | "serviceName" | "recordName" | "labelPrinterId" | "labelPrinterName" | "labels" | "printerType" | "specialInstructions" | "cubic" | "rangeLeft" | "notes" | "createdAt" | "updatedAt", ExtArgs["result"]["customerGroupServicePrintingPreference"]>
export type CustomerGroupServicePrintingPreferenceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customerGroup?: boolean | Prisma.CustomerGroupDefaultArgs<ExtArgs>
}
export type CustomerGroupServicePrintingPreferenceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customerGroup?: boolean | Prisma.CustomerGroupDefaultArgs<ExtArgs>
}
export type CustomerGroupServicePrintingPreferenceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customerGroup?: boolean | Prisma.CustomerGroupDefaultArgs<ExtArgs>
}

export type $CustomerGroupServicePrintingPreferencePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CustomerGroupServicePrintingPreference"
  objects: {
    customerGroup: Prisma.$CustomerGroupPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    customerGroupId: string
    tenantId: string
    carrierId: string
    carrierName: string
    serviceId: string
    serviceCode: string | null
    serviceName: string | null
    recordName: string | null
    labelPrinterId: string | null
    labelPrinterName: string | null
    labels: number
    printerType: string | null
    specialInstructions: string | null
    cubic: number | null
    rangeLeft: number | null
    notes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["customerGroupServicePrintingPreference"]>
  composites: {}
}

export type CustomerGroupServicePrintingPreferenceGetPayload<S extends boolean | null | undefined | CustomerGroupServicePrintingPreferenceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CustomerGroupServicePrintingPreferencePayload, S>

export type CustomerGroupServicePrintingPreferenceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CustomerGroupServicePrintingPreferenceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CustomerGroupServicePrintingPreferenceCountAggregateInputType | true
  }

export interface CustomerGroupServicePrintingPreferenceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CustomerGroupServicePrintingPreference'], meta: { name: 'CustomerGroupServicePrintingPreference' } }
  /**
   * Find zero or one CustomerGroupServicePrintingPreference that matches the filter.
   * @param {CustomerGroupServicePrintingPreferenceFindUniqueArgs} args - Arguments to find a CustomerGroupServicePrintingPreference
   * @example
   * // Get one CustomerGroupServicePrintingPreference
   * const customerGroupServicePrintingPreference = await prisma.customerGroupServicePrintingPreference.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CustomerGroupServicePrintingPreferenceFindUniqueArgs>(args: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CustomerGroupServicePrintingPreferenceClient<runtime.Types.Result.GetResult<Prisma.$CustomerGroupServicePrintingPreferencePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CustomerGroupServicePrintingPreference that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CustomerGroupServicePrintingPreferenceFindUniqueOrThrowArgs} args - Arguments to find a CustomerGroupServicePrintingPreference
   * @example
   * // Get one CustomerGroupServicePrintingPreference
   * const customerGroupServicePrintingPreference = await prisma.customerGroupServicePrintingPreference.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CustomerGroupServicePrintingPreferenceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomerGroupServicePrintingPreferenceClient<runtime.Types.Result.GetResult<Prisma.$CustomerGroupServicePrintingPreferencePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CustomerGroupServicePrintingPreference that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerGroupServicePrintingPreferenceFindFirstArgs} args - Arguments to find a CustomerGroupServicePrintingPreference
   * @example
   * // Get one CustomerGroupServicePrintingPreference
   * const customerGroupServicePrintingPreference = await prisma.customerGroupServicePrintingPreference.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CustomerGroupServicePrintingPreferenceFindFirstArgs>(args?: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceFindFirstArgs<ExtArgs>>): Prisma.Prisma__CustomerGroupServicePrintingPreferenceClient<runtime.Types.Result.GetResult<Prisma.$CustomerGroupServicePrintingPreferencePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CustomerGroupServicePrintingPreference that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerGroupServicePrintingPreferenceFindFirstOrThrowArgs} args - Arguments to find a CustomerGroupServicePrintingPreference
   * @example
   * // Get one CustomerGroupServicePrintingPreference
   * const customerGroupServicePrintingPreference = await prisma.customerGroupServicePrintingPreference.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CustomerGroupServicePrintingPreferenceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomerGroupServicePrintingPreferenceClient<runtime.Types.Result.GetResult<Prisma.$CustomerGroupServicePrintingPreferencePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CustomerGroupServicePrintingPreferences that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerGroupServicePrintingPreferenceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CustomerGroupServicePrintingPreferences
   * const customerGroupServicePrintingPreferences = await prisma.customerGroupServicePrintingPreference.findMany()
   * 
   * // Get first 10 CustomerGroupServicePrintingPreferences
   * const customerGroupServicePrintingPreferences = await prisma.customerGroupServicePrintingPreference.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const customerGroupServicePrintingPreferenceWithIdOnly = await prisma.customerGroupServicePrintingPreference.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CustomerGroupServicePrintingPreferenceFindManyArgs>(args?: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerGroupServicePrintingPreferencePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CustomerGroupServicePrintingPreference.
   * @param {CustomerGroupServicePrintingPreferenceCreateArgs} args - Arguments to create a CustomerGroupServicePrintingPreference.
   * @example
   * // Create one CustomerGroupServicePrintingPreference
   * const CustomerGroupServicePrintingPreference = await prisma.customerGroupServicePrintingPreference.create({
   *   data: {
   *     // ... data to create a CustomerGroupServicePrintingPreference
   *   }
   * })
   * 
   */
  create<T extends CustomerGroupServicePrintingPreferenceCreateArgs>(args: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceCreateArgs<ExtArgs>>): Prisma.Prisma__CustomerGroupServicePrintingPreferenceClient<runtime.Types.Result.GetResult<Prisma.$CustomerGroupServicePrintingPreferencePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CustomerGroupServicePrintingPreferences.
   * @param {CustomerGroupServicePrintingPreferenceCreateManyArgs} args - Arguments to create many CustomerGroupServicePrintingPreferences.
   * @example
   * // Create many CustomerGroupServicePrintingPreferences
   * const customerGroupServicePrintingPreference = await prisma.customerGroupServicePrintingPreference.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CustomerGroupServicePrintingPreferenceCreateManyArgs>(args?: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CustomerGroupServicePrintingPreferences and returns the data saved in the database.
   * @param {CustomerGroupServicePrintingPreferenceCreateManyAndReturnArgs} args - Arguments to create many CustomerGroupServicePrintingPreferences.
   * @example
   * // Create many CustomerGroupServicePrintingPreferences
   * const customerGroupServicePrintingPreference = await prisma.customerGroupServicePrintingPreference.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CustomerGroupServicePrintingPreferences and only return the `id`
   * const customerGroupServicePrintingPreferenceWithIdOnly = await prisma.customerGroupServicePrintingPreference.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CustomerGroupServicePrintingPreferenceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerGroupServicePrintingPreferencePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CustomerGroupServicePrintingPreference.
   * @param {CustomerGroupServicePrintingPreferenceDeleteArgs} args - Arguments to delete one CustomerGroupServicePrintingPreference.
   * @example
   * // Delete one CustomerGroupServicePrintingPreference
   * const CustomerGroupServicePrintingPreference = await prisma.customerGroupServicePrintingPreference.delete({
   *   where: {
   *     // ... filter to delete one CustomerGroupServicePrintingPreference
   *   }
   * })
   * 
   */
  delete<T extends CustomerGroupServicePrintingPreferenceDeleteArgs>(args: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceDeleteArgs<ExtArgs>>): Prisma.Prisma__CustomerGroupServicePrintingPreferenceClient<runtime.Types.Result.GetResult<Prisma.$CustomerGroupServicePrintingPreferencePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CustomerGroupServicePrintingPreference.
   * @param {CustomerGroupServicePrintingPreferenceUpdateArgs} args - Arguments to update one CustomerGroupServicePrintingPreference.
   * @example
   * // Update one CustomerGroupServicePrintingPreference
   * const customerGroupServicePrintingPreference = await prisma.customerGroupServicePrintingPreference.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CustomerGroupServicePrintingPreferenceUpdateArgs>(args: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceUpdateArgs<ExtArgs>>): Prisma.Prisma__CustomerGroupServicePrintingPreferenceClient<runtime.Types.Result.GetResult<Prisma.$CustomerGroupServicePrintingPreferencePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CustomerGroupServicePrintingPreferences.
   * @param {CustomerGroupServicePrintingPreferenceDeleteManyArgs} args - Arguments to filter CustomerGroupServicePrintingPreferences to delete.
   * @example
   * // Delete a few CustomerGroupServicePrintingPreferences
   * const { count } = await prisma.customerGroupServicePrintingPreference.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CustomerGroupServicePrintingPreferenceDeleteManyArgs>(args?: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CustomerGroupServicePrintingPreferences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerGroupServicePrintingPreferenceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CustomerGroupServicePrintingPreferences
   * const customerGroupServicePrintingPreference = await prisma.customerGroupServicePrintingPreference.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CustomerGroupServicePrintingPreferenceUpdateManyArgs>(args: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CustomerGroupServicePrintingPreferences and returns the data updated in the database.
   * @param {CustomerGroupServicePrintingPreferenceUpdateManyAndReturnArgs} args - Arguments to update many CustomerGroupServicePrintingPreferences.
   * @example
   * // Update many CustomerGroupServicePrintingPreferences
   * const customerGroupServicePrintingPreference = await prisma.customerGroupServicePrintingPreference.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CustomerGroupServicePrintingPreferences and only return the `id`
   * const customerGroupServicePrintingPreferenceWithIdOnly = await prisma.customerGroupServicePrintingPreference.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CustomerGroupServicePrintingPreferenceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerGroupServicePrintingPreferencePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CustomerGroupServicePrintingPreference.
   * @param {CustomerGroupServicePrintingPreferenceUpsertArgs} args - Arguments to update or create a CustomerGroupServicePrintingPreference.
   * @example
   * // Update or create a CustomerGroupServicePrintingPreference
   * const customerGroupServicePrintingPreference = await prisma.customerGroupServicePrintingPreference.upsert({
   *   create: {
   *     // ... data to create a CustomerGroupServicePrintingPreference
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CustomerGroupServicePrintingPreference we want to update
   *   }
   * })
   */
  upsert<T extends CustomerGroupServicePrintingPreferenceUpsertArgs>(args: Prisma.SelectSubset<T, CustomerGroupServicePrintingPreferenceUpsertArgs<ExtArgs>>): Prisma.Prisma__CustomerGroupServicePrintingPreferenceClient<runtime.Types.Result.GetResult<Prisma.$CustomerGroupServicePrintingPreferencePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CustomerGroupServicePrintingPreferences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerGroupServicePrintingPreferenceCountArgs} args - Arguments to filter CustomerGroupServicePrintingPreferences to count.
   * @example
   * // Count the number of CustomerGroupServicePrintingPreferences
   * const count = await prisma.customerGroupServicePrintingPreference.count({
   *   where: {
   *     // ... the filter for the CustomerGroupServicePrintingPreferences we want to count
   *   }
   * })
  **/
  count<T extends CustomerGroupServicePrintingPreferenceCountArgs>(
    args?: Prisma.Subset<T, CustomerGroupServicePrintingPreferenceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CustomerGroupServicePrintingPreferenceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CustomerGroupServicePrintingPreference.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerGroupServicePrintingPreferenceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CustomerGroupServicePrintingPreferenceAggregateArgs>(args: Prisma.Subset<T, CustomerGroupServicePrintingPreferenceAggregateArgs>): Prisma.PrismaPromise<GetCustomerGroupServicePrintingPreferenceAggregateType<T>>

  /**
   * Group by CustomerGroupServicePrintingPreference.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerGroupServicePrintingPreferenceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CustomerGroupServicePrintingPreferenceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CustomerGroupServicePrintingPreferenceGroupByArgs['orderBy'] }
      : { orderBy?: CustomerGroupServicePrintingPreferenceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CustomerGroupServicePrintingPreferenceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCustomerGroupServicePrintingPreferenceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CustomerGroupServicePrintingPreference model
 */
readonly fields: CustomerGroupServicePrintingPreferenceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CustomerGroupServicePrintingPreference.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CustomerGroupServicePrintingPreferenceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  customerGroup<T extends Prisma.CustomerGroupDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CustomerGroupDefaultArgs<ExtArgs>>): Prisma.Prisma__CustomerGroupClient<runtime.Types.Result.GetResult<Prisma.$CustomerGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CustomerGroupServicePrintingPreference model
 */
export interface CustomerGroupServicePrintingPreferenceFieldRefs {
  readonly id: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly customerGroupId: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly tenantId: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly carrierId: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly carrierName: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly serviceId: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly serviceCode: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly serviceName: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly recordName: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly labelPrinterId: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly labelPrinterName: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly labels: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'Int'>
  readonly printerType: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly specialInstructions: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly cubic: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'Float'>
  readonly rangeLeft: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'Float'>
  readonly notes: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'String'>
  readonly createdAt: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CustomerGroupServicePrintingPreference", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CustomerGroupServicePrintingPreference findUnique
 */
export type CustomerGroupServicePrintingPreferenceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerGroupServicePrintingPreference
   */
  select?: Prisma.CustomerGroupServicePrintingPreferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerGroupServicePrintingPreference
   */
  omit?: Prisma.CustomerGroupServicePrintingPreferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerGroupServicePrintingPreferenceInclude<ExtArgs> | null
  /**
   * Filter, which CustomerGroupServicePrintingPreference to fetch.
   */
  where: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput
}

/**
 * CustomerGroupServicePrintingPreference findUniqueOrThrow
 */
export type CustomerGroupServicePrintingPreferenceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerGroupServicePrintingPreference
   */
  select?: Prisma.CustomerGroupServicePrintingPreferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerGroupServicePrintingPreference
   */
  omit?: Prisma.CustomerGroupServicePrintingPreferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerGroupServicePrintingPreferenceInclude<ExtArgs> | null
  /**
   * Filter, which CustomerGroupServicePrintingPreference to fetch.
   */
  where: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput
}

/**
 * CustomerGroupServicePrintingPreference findFirst
 */
export type CustomerGroupServicePrintingPreferenceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerGroupServicePrintingPreference
   */
  select?: Prisma.CustomerGroupServicePrintingPreferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerGroupServicePrintingPreference
   */
  omit?: Prisma.CustomerGroupServicePrintingPreferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerGroupServicePrintingPreferenceInclude<ExtArgs> | null
  /**
   * Filter, which CustomerGroupServicePrintingPreference to fetch.
   */
  where?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomerGroupServicePrintingPreferences to fetch.
   */
  orderBy?: Prisma.CustomerGroupServicePrintingPreferenceOrderByWithRelationInput | Prisma.CustomerGroupServicePrintingPreferenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CustomerGroupServicePrintingPreferences.
   */
  cursor?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomerGroupServicePrintingPreferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomerGroupServicePrintingPreferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomerGroupServicePrintingPreferences.
   */
  distinct?: Prisma.CustomerGroupServicePrintingPreferenceScalarFieldEnum | Prisma.CustomerGroupServicePrintingPreferenceScalarFieldEnum[]
}

/**
 * CustomerGroupServicePrintingPreference findFirstOrThrow
 */
export type CustomerGroupServicePrintingPreferenceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerGroupServicePrintingPreference
   */
  select?: Prisma.CustomerGroupServicePrintingPreferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerGroupServicePrintingPreference
   */
  omit?: Prisma.CustomerGroupServicePrintingPreferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerGroupServicePrintingPreferenceInclude<ExtArgs> | null
  /**
   * Filter, which CustomerGroupServicePrintingPreference to fetch.
   */
  where?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomerGroupServicePrintingPreferences to fetch.
   */
  orderBy?: Prisma.CustomerGroupServicePrintingPreferenceOrderByWithRelationInput | Prisma.CustomerGroupServicePrintingPreferenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CustomerGroupServicePrintingPreferences.
   */
  cursor?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomerGroupServicePrintingPreferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomerGroupServicePrintingPreferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomerGroupServicePrintingPreferences.
   */
  distinct?: Prisma.CustomerGroupServicePrintingPreferenceScalarFieldEnum | Prisma.CustomerGroupServicePrintingPreferenceScalarFieldEnum[]
}

/**
 * CustomerGroupServicePrintingPreference findMany
 */
export type CustomerGroupServicePrintingPreferenceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerGroupServicePrintingPreference
   */
  select?: Prisma.CustomerGroupServicePrintingPreferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerGroupServicePrintingPreference
   */
  omit?: Prisma.CustomerGroupServicePrintingPreferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerGroupServicePrintingPreferenceInclude<ExtArgs> | null
  /**
   * Filter, which CustomerGroupServicePrintingPreferences to fetch.
   */
  where?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomerGroupServicePrintingPreferences to fetch.
   */
  orderBy?: Prisma.CustomerGroupServicePrintingPreferenceOrderByWithRelationInput | Prisma.CustomerGroupServicePrintingPreferenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CustomerGroupServicePrintingPreferences.
   */
  cursor?: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomerGroupServicePrintingPreferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomerGroupServicePrintingPreferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomerGroupServicePrintingPreferences.
   */
  distinct?: Prisma.CustomerGroupServicePrintingPreferenceScalarFieldEnum | Prisma.CustomerGroupServicePrintingPreferenceScalarFieldEnum[]
}

/**
 * CustomerGroupServicePrintingPreference create
 */
export type CustomerGroupServicePrintingPreferenceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerGroupServicePrintingPreference
   */
  select?: Prisma.CustomerGroupServicePrintingPreferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerGroupServicePrintingPreference
   */
  omit?: Prisma.CustomerGroupServicePrintingPreferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerGroupServicePrintingPreferenceInclude<ExtArgs> | null
  /**
   * The data needed to create a CustomerGroupServicePrintingPreference.
   */
  data: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceCreateInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedCreateInput>
}

/**
 * CustomerGroupServicePrintingPreference createMany
 */
export type CustomerGroupServicePrintingPreferenceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CustomerGroupServicePrintingPreferences.
   */
  data: Prisma.CustomerGroupServicePrintingPreferenceCreateManyInput | Prisma.CustomerGroupServicePrintingPreferenceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CustomerGroupServicePrintingPreference createManyAndReturn
 */
export type CustomerGroupServicePrintingPreferenceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerGroupServicePrintingPreference
   */
  select?: Prisma.CustomerGroupServicePrintingPreferenceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerGroupServicePrintingPreference
   */
  omit?: Prisma.CustomerGroupServicePrintingPreferenceOmit<ExtArgs> | null
  /**
   * The data used to create many CustomerGroupServicePrintingPreferences.
   */
  data: Prisma.CustomerGroupServicePrintingPreferenceCreateManyInput | Prisma.CustomerGroupServicePrintingPreferenceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerGroupServicePrintingPreferenceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CustomerGroupServicePrintingPreference update
 */
export type CustomerGroupServicePrintingPreferenceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerGroupServicePrintingPreference
   */
  select?: Prisma.CustomerGroupServicePrintingPreferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerGroupServicePrintingPreference
   */
  omit?: Prisma.CustomerGroupServicePrintingPreferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerGroupServicePrintingPreferenceInclude<ExtArgs> | null
  /**
   * The data needed to update a CustomerGroupServicePrintingPreference.
   */
  data: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceUpdateInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedUpdateInput>
  /**
   * Choose, which CustomerGroupServicePrintingPreference to update.
   */
  where: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput
}

/**
 * CustomerGroupServicePrintingPreference updateMany
 */
export type CustomerGroupServicePrintingPreferenceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CustomerGroupServicePrintingPreferences.
   */
  data: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceUpdateManyMutationInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedUpdateManyInput>
  /**
   * Filter which CustomerGroupServicePrintingPreferences to update
   */
  where?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput
  /**
   * Limit how many CustomerGroupServicePrintingPreferences to update.
   */
  limit?: number
}

/**
 * CustomerGroupServicePrintingPreference updateManyAndReturn
 */
export type CustomerGroupServicePrintingPreferenceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerGroupServicePrintingPreference
   */
  select?: Prisma.CustomerGroupServicePrintingPreferenceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerGroupServicePrintingPreference
   */
  omit?: Prisma.CustomerGroupServicePrintingPreferenceOmit<ExtArgs> | null
  /**
   * The data used to update CustomerGroupServicePrintingPreferences.
   */
  data: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceUpdateManyMutationInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedUpdateManyInput>
  /**
   * Filter which CustomerGroupServicePrintingPreferences to update
   */
  where?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput
  /**
   * Limit how many CustomerGroupServicePrintingPreferences to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerGroupServicePrintingPreferenceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CustomerGroupServicePrintingPreference upsert
 */
export type CustomerGroupServicePrintingPreferenceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerGroupServicePrintingPreference
   */
  select?: Prisma.CustomerGroupServicePrintingPreferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerGroupServicePrintingPreference
   */
  omit?: Prisma.CustomerGroupServicePrintingPreferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerGroupServicePrintingPreferenceInclude<ExtArgs> | null
  /**
   * The filter to search for the CustomerGroupServicePrintingPreference to update in case it exists.
   */
  where: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput
  /**
   * In case the CustomerGroupServicePrintingPreference found by the `where` argument doesn't exist, create a new CustomerGroupServicePrintingPreference with this data.
   */
  create: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceCreateInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedCreateInput>
  /**
   * In case the CustomerGroupServicePrintingPreference was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CustomerGroupServicePrintingPreferenceUpdateInput, Prisma.CustomerGroupServicePrintingPreferenceUncheckedUpdateInput>
}

/**
 * CustomerGroupServicePrintingPreference delete
 */
export type CustomerGroupServicePrintingPreferenceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerGroupServicePrintingPreference
   */
  select?: Prisma.CustomerGroupServicePrintingPreferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerGroupServicePrintingPreference
   */
  omit?: Prisma.CustomerGroupServicePrintingPreferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerGroupServicePrintingPreferenceInclude<ExtArgs> | null
  /**
   * Filter which CustomerGroupServicePrintingPreference to delete.
   */
  where: Prisma.CustomerGroupServicePrintingPreferenceWhereUniqueInput
}

/**
 * CustomerGroupServicePrintingPreference deleteMany
 */
export type CustomerGroupServicePrintingPreferenceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CustomerGroupServicePrintingPreferences to delete
   */
  where?: Prisma.CustomerGroupServicePrintingPreferenceWhereInput
  /**
   * Limit how many CustomerGroupServicePrintingPreferences to delete.
   */
  limit?: number
}

/**
 * CustomerGroupServicePrintingPreference without action
 */
export type CustomerGroupServicePrintingPreferenceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerGroupServicePrintingPreference
   */
  select?: Prisma.CustomerGroupServicePrintingPreferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerGroupServicePrintingPreference
   */
  omit?: Prisma.CustomerGroupServicePrintingPreferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerGroupServicePrintingPreferenceInclude<ExtArgs> | null
}
