/**
 * @packageDocumentation
 * @module api.functional.v1.tracking_service.accounts.shipments
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";

import type { TenantInternalHeaders } from "../../../../../structures/TenantInternalHeaders";
import type { TrackingShipmentsResponse } from "../../../../../structures/TrackingShipmentsResponse";

/**
 * @controller TrackingController.getShipmentsTracking
 * @path GET /v1/tracking-service/accounts/:accountId/shipments
 * @accessor api.functional.v1.tracking_service.accounts.shipments.getShipmentsTracking
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getShipmentsTracking(
  connection: IConnection<getShipmentsTracking.Headers>,
  accountId: string &
    tags.TagBase<{
      target: "string";
      kind: "format";
      value: "uuid";
      validate: '$importInternal("isFormatUuid")($input)';
      exclusive: ["format", "pattern"];
      schema: {
        format: "uuid";
      };
    }>,
): Promise<getShipmentsTracking.Output> {
  return PlainFetcher.fetch(connection, {
    ...getShipmentsTracking.METADATA,
    template: getShipmentsTracking.METADATA.path,
    path: getShipmentsTracking.path(accountId),
  });
}
export namespace getShipmentsTracking {
  export type Headers = TenantInternalHeaders;
  export type Output = TrackingShipmentsResponse;

  export const METADATA = {
    method: "GET",
    path: "/v1/tracking-service/accounts/:accountId/shipments",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    accountId: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>,
  ) =>
    `/v1/tracking-service/accounts/${encodeURIComponent(
      accountId?.toString() ?? "null",
    )}/shipments`;
}
