/**
 * @packageDocumentation
 * @module api.functional.v1.tracking_service.shipments.events
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";

import type { TenantInternalHeaders } from "../../../../../structures/TenantInternalHeaders";
import type { TrackingEventsResponse } from "../../../../../structures/TrackingEventsResponse";

/**
 * @controller TrackingController.getTrackingEvents
 * @path GET /v1/tracking-service/shipments/:shipmentId/events
 * @accessor api.functional.v1.tracking_service.shipments.events.getTrackingEvents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getTrackingEvents(
  connection: IConnection<getTrackingEvents.Headers>,
  shipmentId: string &
    tags.TagBase<{
      target: "string";
      kind: "format";
      value: "uuid";
      validate: '$importInternal("isFormatUuid")($input)';
      exclusive: ["format", "pattern"];
      schema: {
        format: "uuid";
      };
    }>,
): Promise<getTrackingEvents.Output> {
  return PlainFetcher.fetch(connection, {
    ...getTrackingEvents.METADATA,
    template: getTrackingEvents.METADATA.path,
    path: getTrackingEvents.path(shipmentId),
  });
}
export namespace getTrackingEvents {
  export type Headers = TenantInternalHeaders;
  export type Output = TrackingEventsResponse;

  export const METADATA = {
    method: "GET",
    path: "/v1/tracking-service/shipments/:shipmentId/events",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    shipmentId: string &
      tags.TagBase<{
        target: "string";
        kind: "format";
        value: "uuid";
        validate: '$importInternal("isFormatUuid")($input)';
        exclusive: ["format", "pattern"];
        schema: {
          format: "uuid";
        };
      }>,
  ) =>
    `/v1/tracking-service/shipments/${encodeURIComponent(
      shipmentId?.toString() ?? "null",
    )}/events`;
}
