
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AccountCarrierConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AccountCarrierConfig
 * 
 */
export type AccountCarrierConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$AccountCarrierConfigPayload>

export type AggregateAccountCarrierConfig = {
  _count: AccountCarrierConfigCountAggregateOutputType | null
  _avg: AccountCarrierConfigAvgAggregateOutputType | null
  _sum: AccountCarrierConfigSumAggregateOutputType | null
  _min: AccountCarrierConfigMinAggregateOutputType | null
  _max: AccountCarrierConfigMaxAggregateOutputType | null
}

export type AccountCarrierConfigAvgAggregateOutputType = {
  consignmentMax: number | null
  consignmentMin: number | null
  consignmentNextId: number | null
  manifestMax: number | null
  manifestMin: number | null
  manifestNextId: number | null
  atlCodeMax: number | null
  atlCodeMin: number | null
  atlCodeLength: number | null
  atlCodeNextId: number | null
}

export type AccountCarrierConfigSumAggregateOutputType = {
  consignmentMax: number | null
  consignmentMin: number | null
  consignmentNextId: number | null
  manifestMax: number | null
  manifestMin: number | null
  manifestNextId: number | null
  atlCodeMax: number | null
  atlCodeMin: number | null
  atlCodeLength: number | null
  atlCodeNextId: number | null
}

export type AccountCarrierConfigMinAggregateOutputType = {
  id: string | null
  accountCarrierId: string | null
  tenantId: string | null
  consignmentPrefix: string | null
  consignmentMax: number | null
  consignmentMin: number | null
  consignmentNextId: number | null
  manifestPrefix: string | null
  manifestMax: number | null
  manifestMin: number | null
  manifestNextId: number | null
  atlCodePrefix: string | null
  atlCodeMax: number | null
  atlCodeMin: number | null
  atlCodeLength: number | null
  atlCodeNextId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccountCarrierConfigMaxAggregateOutputType = {
  id: string | null
  accountCarrierId: string | null
  tenantId: string | null
  consignmentPrefix: string | null
  consignmentMax: number | null
  consignmentMin: number | null
  consignmentNextId: number | null
  manifestPrefix: string | null
  manifestMax: number | null
  manifestMin: number | null
  manifestNextId: number | null
  atlCodePrefix: string | null
  atlCodeMax: number | null
  atlCodeMin: number | null
  atlCodeLength: number | null
  atlCodeNextId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccountCarrierConfigCountAggregateOutputType = {
  id: number
  accountCarrierId: number
  tenantId: number
  consignmentPrefix: number
  consignmentMax: number
  consignmentMin: number
  consignmentNextId: number
  manifestPrefix: number
  manifestMax: number
  manifestMin: number
  manifestNextId: number
  atlCodePrefix: number
  atlCodeMax: number
  atlCodeMin: number
  atlCodeLength: number
  atlCodeNextId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AccountCarrierConfigAvgAggregateInputType = {
  consignmentMax?: true
  consignmentMin?: true
  consignmentNextId?: true
  manifestMax?: true
  manifestMin?: true
  manifestNextId?: true
  atlCodeMax?: true
  atlCodeMin?: true
  atlCodeLength?: true
  atlCodeNextId?: true
}

export type AccountCarrierConfigSumAggregateInputType = {
  consignmentMax?: true
  consignmentMin?: true
  consignmentNextId?: true
  manifestMax?: true
  manifestMin?: true
  manifestNextId?: true
  atlCodeMax?: true
  atlCodeMin?: true
  atlCodeLength?: true
  atlCodeNextId?: true
}

export type AccountCarrierConfigMinAggregateInputType = {
  id?: true
  accountCarrierId?: true
  tenantId?: true
  consignmentPrefix?: true
  consignmentMax?: true
  consignmentMin?: true
  consignmentNextId?: true
  manifestPrefix?: true
  manifestMax?: true
  manifestMin?: true
  manifestNextId?: true
  atlCodePrefix?: true
  atlCodeMax?: true
  atlCodeMin?: true
  atlCodeLength?: true
  atlCodeNextId?: true
  createdAt?: true
  updatedAt?: true
}

export type AccountCarrierConfigMaxAggregateInputType = {
  id?: true
  accountCarrierId?: true
  tenantId?: true
  consignmentPrefix?: true
  consignmentMax?: true
  consignmentMin?: true
  consignmentNextId?: true
  manifestPrefix?: true
  manifestMax?: true
  manifestMin?: true
  manifestNextId?: true
  atlCodePrefix?: true
  atlCodeMax?: true
  atlCodeMin?: true
  atlCodeLength?: true
  atlCodeNextId?: true
  createdAt?: true
  updatedAt?: true
}

export type AccountCarrierConfigCountAggregateInputType = {
  id?: true
  accountCarrierId?: true
  tenantId?: true
  consignmentPrefix?: true
  consignmentMax?: true
  consignmentMin?: true
  consignmentNextId?: true
  manifestPrefix?: true
  manifestMax?: true
  manifestMin?: true
  manifestNextId?: true
  atlCodePrefix?: true
  atlCodeMax?: true
  atlCodeMin?: true
  atlCodeLength?: true
  atlCodeNextId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AccountCarrierConfigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccountCarrierConfig to aggregate.
   */
  where?: Prisma.AccountCarrierConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountCarrierConfigs to fetch.
   */
  orderBy?: Prisma.AccountCarrierConfigOrderByWithRelationInput | Prisma.AccountCarrierConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccountCarrierConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountCarrierConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountCarrierConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AccountCarrierConfigs
  **/
  _count?: true | AccountCarrierConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AccountCarrierConfigAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AccountCarrierConfigSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccountCarrierConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccountCarrierConfigMaxAggregateInputType
}

export type GetAccountCarrierConfigAggregateType<T extends AccountCarrierConfigAggregateArgs> = {
      [P in keyof T & keyof AggregateAccountCarrierConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccountCarrierConfig[P]>
    : Prisma.GetScalarType<T[P], AggregateAccountCarrierConfig[P]>
}




export type AccountCarrierConfigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountCarrierConfigWhereInput
  orderBy?: Prisma.AccountCarrierConfigOrderByWithAggregationInput | Prisma.AccountCarrierConfigOrderByWithAggregationInput[]
  by: Prisma.AccountCarrierConfigScalarFieldEnum[] | Prisma.AccountCarrierConfigScalarFieldEnum
  having?: Prisma.AccountCarrierConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccountCarrierConfigCountAggregateInputType | true
  _avg?: AccountCarrierConfigAvgAggregateInputType
  _sum?: AccountCarrierConfigSumAggregateInputType
  _min?: AccountCarrierConfigMinAggregateInputType
  _max?: AccountCarrierConfigMaxAggregateInputType
}

export type AccountCarrierConfigGroupByOutputType = {
  id: string
  accountCarrierId: string
  tenantId: string
  consignmentPrefix: string | null
  consignmentMax: number | null
  consignmentMin: number | null
  consignmentNextId: number | null
  manifestPrefix: string | null
  manifestMax: number | null
  manifestMin: number | null
  manifestNextId: number | null
  atlCodePrefix: string | null
  atlCodeMax: number | null
  atlCodeMin: number | null
  atlCodeLength: number | null
  atlCodeNextId: number | null
  createdAt: Date
  updatedAt: Date
  _count: AccountCarrierConfigCountAggregateOutputType | null
  _avg: AccountCarrierConfigAvgAggregateOutputType | null
  _sum: AccountCarrierConfigSumAggregateOutputType | null
  _min: AccountCarrierConfigMinAggregateOutputType | null
  _max: AccountCarrierConfigMaxAggregateOutputType | null
}

export type GetAccountCarrierConfigGroupByPayload<T extends AccountCarrierConfigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccountCarrierConfigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccountCarrierConfigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccountCarrierConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccountCarrierConfigGroupByOutputType[P]>
      }
    >
  >



export type AccountCarrierConfigWhereInput = {
  AND?: Prisma.AccountCarrierConfigWhereInput | Prisma.AccountCarrierConfigWhereInput[]
  OR?: Prisma.AccountCarrierConfigWhereInput[]
  NOT?: Prisma.AccountCarrierConfigWhereInput | Prisma.AccountCarrierConfigWhereInput[]
  id?: Prisma.UuidFilter<"AccountCarrierConfig"> | string
  accountCarrierId?: Prisma.UuidFilter<"AccountCarrierConfig"> | string
  tenantId?: Prisma.UuidFilter<"AccountCarrierConfig"> | string
  consignmentPrefix?: Prisma.StringNullableFilter<"AccountCarrierConfig"> | string | null
  consignmentMax?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  consignmentMin?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  consignmentNextId?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  manifestPrefix?: Prisma.StringNullableFilter<"AccountCarrierConfig"> | string | null
  manifestMax?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  manifestMin?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  manifestNextId?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  atlCodePrefix?: Prisma.StringNullableFilter<"AccountCarrierConfig"> | string | null
  atlCodeMax?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  atlCodeMin?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  atlCodeLength?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  atlCodeNextId?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  createdAt?: Prisma.DateTimeFilter<"AccountCarrierConfig"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccountCarrierConfig"> | Date | string
  accountCarrier?: Prisma.XOR<Prisma.AccountCarrierScalarRelationFilter, Prisma.AccountCarrierWhereInput>
}

export type AccountCarrierConfigOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  accountCarrierId?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  consignmentPrefix?: Prisma.SortOrderInput | Prisma.SortOrder
  consignmentMax?: Prisma.SortOrderInput | Prisma.SortOrder
  consignmentMin?: Prisma.SortOrderInput | Prisma.SortOrder
  consignmentNextId?: Prisma.SortOrderInput | Prisma.SortOrder
  manifestPrefix?: Prisma.SortOrderInput | Prisma.SortOrder
  manifestMax?: Prisma.SortOrderInput | Prisma.SortOrder
  manifestMin?: Prisma.SortOrderInput | Prisma.SortOrder
  manifestNextId?: Prisma.SortOrderInput | Prisma.SortOrder
  atlCodePrefix?: Prisma.SortOrderInput | Prisma.SortOrder
  atlCodeMax?: Prisma.SortOrderInput | Prisma.SortOrder
  atlCodeMin?: Prisma.SortOrderInput | Prisma.SortOrder
  atlCodeLength?: Prisma.SortOrderInput | Prisma.SortOrder
  atlCodeNextId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  accountCarrier?: Prisma.AccountCarrierOrderByWithRelationInput
}

export type AccountCarrierConfigWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  accountCarrierId?: string
  AND?: Prisma.AccountCarrierConfigWhereInput | Prisma.AccountCarrierConfigWhereInput[]
  OR?: Prisma.AccountCarrierConfigWhereInput[]
  NOT?: Prisma.AccountCarrierConfigWhereInput | Prisma.AccountCarrierConfigWhereInput[]
  tenantId?: Prisma.UuidFilter<"AccountCarrierConfig"> | string
  consignmentPrefix?: Prisma.StringNullableFilter<"AccountCarrierConfig"> | string | null
  consignmentMax?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  consignmentMin?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  consignmentNextId?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  manifestPrefix?: Prisma.StringNullableFilter<"AccountCarrierConfig"> | string | null
  manifestMax?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  manifestMin?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  manifestNextId?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  atlCodePrefix?: Prisma.StringNullableFilter<"AccountCarrierConfig"> | string | null
  atlCodeMax?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  atlCodeMin?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  atlCodeLength?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  atlCodeNextId?: Prisma.IntNullableFilter<"AccountCarrierConfig"> | number | null
  createdAt?: Prisma.DateTimeFilter<"AccountCarrierConfig"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccountCarrierConfig"> | Date | string
  accountCarrier?: Prisma.XOR<Prisma.AccountCarrierScalarRelationFilter, Prisma.AccountCarrierWhereInput>
}, "id" | "accountCarrierId">

export type AccountCarrierConfigOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  accountCarrierId?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  consignmentPrefix?: Prisma.SortOrderInput | Prisma.SortOrder
  consignmentMax?: Prisma.SortOrderInput | Prisma.SortOrder
  consignmentMin?: Prisma.SortOrderInput | Prisma.SortOrder
  consignmentNextId?: Prisma.SortOrderInput | Prisma.SortOrder
  manifestPrefix?: Prisma.SortOrderInput | Prisma.SortOrder
  manifestMax?: Prisma.SortOrderInput | Prisma.SortOrder
  manifestMin?: Prisma.SortOrderInput | Prisma.SortOrder
  manifestNextId?: Prisma.SortOrderInput | Prisma.SortOrder
  atlCodePrefix?: Prisma.SortOrderInput | Prisma.SortOrder
  atlCodeMax?: Prisma.SortOrderInput | Prisma.SortOrder
  atlCodeMin?: Prisma.SortOrderInput | Prisma.SortOrder
  atlCodeLength?: Prisma.SortOrderInput | Prisma.SortOrder
  atlCodeNextId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AccountCarrierConfigCountOrderByAggregateInput
  _avg?: Prisma.AccountCarrierConfigAvgOrderByAggregateInput
  _max?: Prisma.AccountCarrierConfigMaxOrderByAggregateInput
  _min?: Prisma.AccountCarrierConfigMinOrderByAggregateInput
  _sum?: Prisma.AccountCarrierConfigSumOrderByAggregateInput
}

export type AccountCarrierConfigScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccountCarrierConfigScalarWhereWithAggregatesInput | Prisma.AccountCarrierConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccountCarrierConfigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccountCarrierConfigScalarWhereWithAggregatesInput | Prisma.AccountCarrierConfigScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"AccountCarrierConfig"> | string
  accountCarrierId?: Prisma.UuidWithAggregatesFilter<"AccountCarrierConfig"> | string
  tenantId?: Prisma.UuidWithAggregatesFilter<"AccountCarrierConfig"> | string
  consignmentPrefix?: Prisma.StringNullableWithAggregatesFilter<"AccountCarrierConfig"> | string | null
  consignmentMax?: Prisma.IntNullableWithAggregatesFilter<"AccountCarrierConfig"> | number | null
  consignmentMin?: Prisma.IntNullableWithAggregatesFilter<"AccountCarrierConfig"> | number | null
  consignmentNextId?: Prisma.IntNullableWithAggregatesFilter<"AccountCarrierConfig"> | number | null
  manifestPrefix?: Prisma.StringNullableWithAggregatesFilter<"AccountCarrierConfig"> | string | null
  manifestMax?: Prisma.IntNullableWithAggregatesFilter<"AccountCarrierConfig"> | number | null
  manifestMin?: Prisma.IntNullableWithAggregatesFilter<"AccountCarrierConfig"> | number | null
  manifestNextId?: Prisma.IntNullableWithAggregatesFilter<"AccountCarrierConfig"> | number | null
  atlCodePrefix?: Prisma.StringNullableWithAggregatesFilter<"AccountCarrierConfig"> | string | null
  atlCodeMax?: Prisma.IntNullableWithAggregatesFilter<"AccountCarrierConfig"> | number | null
  atlCodeMin?: Prisma.IntNullableWithAggregatesFilter<"AccountCarrierConfig"> | number | null
  atlCodeLength?: Prisma.IntNullableWithAggregatesFilter<"AccountCarrierConfig"> | number | null
  atlCodeNextId?: Prisma.IntNullableWithAggregatesFilter<"AccountCarrierConfig"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AccountCarrierConfig"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AccountCarrierConfig"> | Date | string
}

export type AccountCarrierConfigCreateInput = {
  id?: string
  tenantId: string
  consignmentPrefix?: string | null
  consignmentMax?: number | null
  consignmentMin?: number | null
  consignmentNextId?: number | null
  manifestPrefix?: string | null
  manifestMax?: number | null
  manifestMin?: number | null
  manifestNextId?: number | null
  atlCodePrefix?: string | null
  atlCodeMax?: number | null
  atlCodeMin?: number | null
  atlCodeLength?: number | null
  atlCodeNextId?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accountCarrier: Prisma.AccountCarrierCreateNestedOneWithoutConfigInput
}

export type AccountCarrierConfigUncheckedCreateInput = {
  id?: string
  accountCarrierId: string
  tenantId: string
  consignmentPrefix?: string | null
  consignmentMax?: number | null
  consignmentMin?: number | null
  consignmentNextId?: number | null
  manifestPrefix?: string | null
  manifestMax?: number | null
  manifestMin?: number | null
  manifestNextId?: number | null
  atlCodePrefix?: string | null
  atlCodeMax?: number | null
  atlCodeMin?: number | null
  atlCodeLength?: number | null
  atlCodeNextId?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountCarrierConfigUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  consignmentPrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consignmentMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  consignmentMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  consignmentNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestPrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  manifestMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodePrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  atlCodeMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accountCarrier?: Prisma.AccountCarrierUpdateOneRequiredWithoutConfigNestedInput
}

export type AccountCarrierConfigUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountCarrierId?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  consignmentPrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consignmentMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  consignmentMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  consignmentNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestPrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  manifestMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodePrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  atlCodeMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountCarrierConfigCreateManyInput = {
  id?: string
  accountCarrierId: string
  tenantId: string
  consignmentPrefix?: string | null
  consignmentMax?: number | null
  consignmentMin?: number | null
  consignmentNextId?: number | null
  manifestPrefix?: string | null
  manifestMax?: number | null
  manifestMin?: number | null
  manifestNextId?: number | null
  atlCodePrefix?: string | null
  atlCodeMax?: number | null
  atlCodeMin?: number | null
  atlCodeLength?: number | null
  atlCodeNextId?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountCarrierConfigUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  consignmentPrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consignmentMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  consignmentMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  consignmentNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestPrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  manifestMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodePrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  atlCodeMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountCarrierConfigUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountCarrierId?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  consignmentPrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consignmentMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  consignmentMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  consignmentNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestPrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  manifestMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodePrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  atlCodeMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountCarrierConfigNullableScalarRelationFilter = {
  is?: Prisma.AccountCarrierConfigWhereInput | null
  isNot?: Prisma.AccountCarrierConfigWhereInput | null
}

export type AccountCarrierConfigCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountCarrierId?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  consignmentPrefix?: Prisma.SortOrder
  consignmentMax?: Prisma.SortOrder
  consignmentMin?: Prisma.SortOrder
  consignmentNextId?: Prisma.SortOrder
  manifestPrefix?: Prisma.SortOrder
  manifestMax?: Prisma.SortOrder
  manifestMin?: Prisma.SortOrder
  manifestNextId?: Prisma.SortOrder
  atlCodePrefix?: Prisma.SortOrder
  atlCodeMax?: Prisma.SortOrder
  atlCodeMin?: Prisma.SortOrder
  atlCodeLength?: Prisma.SortOrder
  atlCodeNextId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountCarrierConfigAvgOrderByAggregateInput = {
  consignmentMax?: Prisma.SortOrder
  consignmentMin?: Prisma.SortOrder
  consignmentNextId?: Prisma.SortOrder
  manifestMax?: Prisma.SortOrder
  manifestMin?: Prisma.SortOrder
  manifestNextId?: Prisma.SortOrder
  atlCodeMax?: Prisma.SortOrder
  atlCodeMin?: Prisma.SortOrder
  atlCodeLength?: Prisma.SortOrder
  atlCodeNextId?: Prisma.SortOrder
}

export type AccountCarrierConfigMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountCarrierId?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  consignmentPrefix?: Prisma.SortOrder
  consignmentMax?: Prisma.SortOrder
  consignmentMin?: Prisma.SortOrder
  consignmentNextId?: Prisma.SortOrder
  manifestPrefix?: Prisma.SortOrder
  manifestMax?: Prisma.SortOrder
  manifestMin?: Prisma.SortOrder
  manifestNextId?: Prisma.SortOrder
  atlCodePrefix?: Prisma.SortOrder
  atlCodeMax?: Prisma.SortOrder
  atlCodeMin?: Prisma.SortOrder
  atlCodeLength?: Prisma.SortOrder
  atlCodeNextId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountCarrierConfigMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountCarrierId?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  consignmentPrefix?: Prisma.SortOrder
  consignmentMax?: Prisma.SortOrder
  consignmentMin?: Prisma.SortOrder
  consignmentNextId?: Prisma.SortOrder
  manifestPrefix?: Prisma.SortOrder
  manifestMax?: Prisma.SortOrder
  manifestMin?: Prisma.SortOrder
  manifestNextId?: Prisma.SortOrder
  atlCodePrefix?: Prisma.SortOrder
  atlCodeMax?: Prisma.SortOrder
  atlCodeMin?: Prisma.SortOrder
  atlCodeLength?: Prisma.SortOrder
  atlCodeNextId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountCarrierConfigSumOrderByAggregateInput = {
  consignmentMax?: Prisma.SortOrder
  consignmentMin?: Prisma.SortOrder
  consignmentNextId?: Prisma.SortOrder
  manifestMax?: Prisma.SortOrder
  manifestMin?: Prisma.SortOrder
  manifestNextId?: Prisma.SortOrder
  atlCodeMax?: Prisma.SortOrder
  atlCodeMin?: Prisma.SortOrder
  atlCodeLength?: Prisma.SortOrder
  atlCodeNextId?: Prisma.SortOrder
}

export type AccountCarrierConfigCreateNestedOneWithoutAccountCarrierInput = {
  create?: Prisma.XOR<Prisma.AccountCarrierConfigCreateWithoutAccountCarrierInput, Prisma.AccountCarrierConfigUncheckedCreateWithoutAccountCarrierInput>
  connectOrCreate?: Prisma.AccountCarrierConfigCreateOrConnectWithoutAccountCarrierInput
  connect?: Prisma.AccountCarrierConfigWhereUniqueInput
}

export type AccountCarrierConfigUncheckedCreateNestedOneWithoutAccountCarrierInput = {
  create?: Prisma.XOR<Prisma.AccountCarrierConfigCreateWithoutAccountCarrierInput, Prisma.AccountCarrierConfigUncheckedCreateWithoutAccountCarrierInput>
  connectOrCreate?: Prisma.AccountCarrierConfigCreateOrConnectWithoutAccountCarrierInput
  connect?: Prisma.AccountCarrierConfigWhereUniqueInput
}

export type AccountCarrierConfigUpdateOneWithoutAccountCarrierNestedInput = {
  create?: Prisma.XOR<Prisma.AccountCarrierConfigCreateWithoutAccountCarrierInput, Prisma.AccountCarrierConfigUncheckedCreateWithoutAccountCarrierInput>
  connectOrCreate?: Prisma.AccountCarrierConfigCreateOrConnectWithoutAccountCarrierInput
  upsert?: Prisma.AccountCarrierConfigUpsertWithoutAccountCarrierInput
  disconnect?: Prisma.AccountCarrierConfigWhereInput | boolean
  delete?: Prisma.AccountCarrierConfigWhereInput | boolean
  connect?: Prisma.AccountCarrierConfigWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccountCarrierConfigUpdateToOneWithWhereWithoutAccountCarrierInput, Prisma.AccountCarrierConfigUpdateWithoutAccountCarrierInput>, Prisma.AccountCarrierConfigUncheckedUpdateWithoutAccountCarrierInput>
}

export type AccountCarrierConfigUncheckedUpdateOneWithoutAccountCarrierNestedInput = {
  create?: Prisma.XOR<Prisma.AccountCarrierConfigCreateWithoutAccountCarrierInput, Prisma.AccountCarrierConfigUncheckedCreateWithoutAccountCarrierInput>
  connectOrCreate?: Prisma.AccountCarrierConfigCreateOrConnectWithoutAccountCarrierInput
  upsert?: Prisma.AccountCarrierConfigUpsertWithoutAccountCarrierInput
  disconnect?: Prisma.AccountCarrierConfigWhereInput | boolean
  delete?: Prisma.AccountCarrierConfigWhereInput | boolean
  connect?: Prisma.AccountCarrierConfigWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccountCarrierConfigUpdateToOneWithWhereWithoutAccountCarrierInput, Prisma.AccountCarrierConfigUpdateWithoutAccountCarrierInput>, Prisma.AccountCarrierConfigUncheckedUpdateWithoutAccountCarrierInput>
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type AccountCarrierConfigCreateWithoutAccountCarrierInput = {
  id?: string
  tenantId: string
  consignmentPrefix?: string | null
  consignmentMax?: number | null
  consignmentMin?: number | null
  consignmentNextId?: number | null
  manifestPrefix?: string | null
  manifestMax?: number | null
  manifestMin?: number | null
  manifestNextId?: number | null
  atlCodePrefix?: string | null
  atlCodeMax?: number | null
  atlCodeMin?: number | null
  atlCodeLength?: number | null
  atlCodeNextId?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountCarrierConfigUncheckedCreateWithoutAccountCarrierInput = {
  id?: string
  tenantId: string
  consignmentPrefix?: string | null
  consignmentMax?: number | null
  consignmentMin?: number | null
  consignmentNextId?: number | null
  manifestPrefix?: string | null
  manifestMax?: number | null
  manifestMin?: number | null
  manifestNextId?: number | null
  atlCodePrefix?: string | null
  atlCodeMax?: number | null
  atlCodeMin?: number | null
  atlCodeLength?: number | null
  atlCodeNextId?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountCarrierConfigCreateOrConnectWithoutAccountCarrierInput = {
  where: Prisma.AccountCarrierConfigWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountCarrierConfigCreateWithoutAccountCarrierInput, Prisma.AccountCarrierConfigUncheckedCreateWithoutAccountCarrierInput>
}

export type AccountCarrierConfigUpsertWithoutAccountCarrierInput = {
  update: Prisma.XOR<Prisma.AccountCarrierConfigUpdateWithoutAccountCarrierInput, Prisma.AccountCarrierConfigUncheckedUpdateWithoutAccountCarrierInput>
  create: Prisma.XOR<Prisma.AccountCarrierConfigCreateWithoutAccountCarrierInput, Prisma.AccountCarrierConfigUncheckedCreateWithoutAccountCarrierInput>
  where?: Prisma.AccountCarrierConfigWhereInput
}

export type AccountCarrierConfigUpdateToOneWithWhereWithoutAccountCarrierInput = {
  where?: Prisma.AccountCarrierConfigWhereInput
  data: Prisma.XOR<Prisma.AccountCarrierConfigUpdateWithoutAccountCarrierInput, Prisma.AccountCarrierConfigUncheckedUpdateWithoutAccountCarrierInput>
}

export type AccountCarrierConfigUpdateWithoutAccountCarrierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  consignmentPrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consignmentMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  consignmentMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  consignmentNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestPrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  manifestMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodePrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  atlCodeMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountCarrierConfigUncheckedUpdateWithoutAccountCarrierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  consignmentPrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consignmentMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  consignmentMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  consignmentNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestPrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  manifestMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  manifestNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodePrefix?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  atlCodeMax?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeMin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  atlCodeNextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AccountCarrierConfigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountCarrierId?: boolean
  tenantId?: boolean
  consignmentPrefix?: boolean
  consignmentMax?: boolean
  consignmentMin?: boolean
  consignmentNextId?: boolean
  manifestPrefix?: boolean
  manifestMax?: boolean
  manifestMin?: boolean
  manifestNextId?: boolean
  atlCodePrefix?: boolean
  atlCodeMax?: boolean
  atlCodeMin?: boolean
  atlCodeLength?: boolean
  atlCodeNextId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  accountCarrier?: boolean | Prisma.AccountCarrierDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accountCarrierConfig"]>

export type AccountCarrierConfigSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountCarrierId?: boolean
  tenantId?: boolean
  consignmentPrefix?: boolean
  consignmentMax?: boolean
  consignmentMin?: boolean
  consignmentNextId?: boolean
  manifestPrefix?: boolean
  manifestMax?: boolean
  manifestMin?: boolean
  manifestNextId?: boolean
  atlCodePrefix?: boolean
  atlCodeMax?: boolean
  atlCodeMin?: boolean
  atlCodeLength?: boolean
  atlCodeNextId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  accountCarrier?: boolean | Prisma.AccountCarrierDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accountCarrierConfig"]>

export type AccountCarrierConfigSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountCarrierId?: boolean
  tenantId?: boolean
  consignmentPrefix?: boolean
  consignmentMax?: boolean
  consignmentMin?: boolean
  consignmentNextId?: boolean
  manifestPrefix?: boolean
  manifestMax?: boolean
  manifestMin?: boolean
  manifestNextId?: boolean
  atlCodePrefix?: boolean
  atlCodeMax?: boolean
  atlCodeMin?: boolean
  atlCodeLength?: boolean
  atlCodeNextId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  accountCarrier?: boolean | Prisma.AccountCarrierDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accountCarrierConfig"]>

export type AccountCarrierConfigSelectScalar = {
  id?: boolean
  accountCarrierId?: boolean
  tenantId?: boolean
  consignmentPrefix?: boolean
  consignmentMax?: boolean
  consignmentMin?: boolean
  consignmentNextId?: boolean
  manifestPrefix?: boolean
  manifestMax?: boolean
  manifestMin?: boolean
  manifestNextId?: boolean
  atlCodePrefix?: boolean
  atlCodeMax?: boolean
  atlCodeMin?: boolean
  atlCodeLength?: boolean
  atlCodeNextId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AccountCarrierConfigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "accountCarrierId" | "tenantId" | "consignmentPrefix" | "consignmentMax" | "consignmentMin" | "consignmentNextId" | "manifestPrefix" | "manifestMax" | "manifestMin" | "manifestNextId" | "atlCodePrefix" | "atlCodeMax" | "atlCodeMin" | "atlCodeLength" | "atlCodeNextId" | "createdAt" | "updatedAt", ExtArgs["result"]["accountCarrierConfig"]>
export type AccountCarrierConfigInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accountCarrier?: boolean | Prisma.AccountCarrierDefaultArgs<ExtArgs>
}
export type AccountCarrierConfigIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accountCarrier?: boolean | Prisma.AccountCarrierDefaultArgs<ExtArgs>
}
export type AccountCarrierConfigIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accountCarrier?: boolean | Prisma.AccountCarrierDefaultArgs<ExtArgs>
}

export type $AccountCarrierConfigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AccountCarrierConfig"
  objects: {
    accountCarrier: Prisma.$AccountCarrierPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    accountCarrierId: string
    tenantId: string
    consignmentPrefix: string | null
    consignmentMax: number | null
    consignmentMin: number | null
    consignmentNextId: number | null
    manifestPrefix: string | null
    manifestMax: number | null
    manifestMin: number | null
    manifestNextId: number | null
    atlCodePrefix: string | null
    atlCodeMax: number | null
    atlCodeMin: number | null
    atlCodeLength: number | null
    atlCodeNextId: number | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["accountCarrierConfig"]>
  composites: {}
}

export type AccountCarrierConfigGetPayload<S extends boolean | null | undefined | AccountCarrierConfigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccountCarrierConfigPayload, S>

export type AccountCarrierConfigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccountCarrierConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccountCarrierConfigCountAggregateInputType | true
  }

export interface AccountCarrierConfigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AccountCarrierConfig'], meta: { name: 'AccountCarrierConfig' } }
  /**
   * Find zero or one AccountCarrierConfig that matches the filter.
   * @param {AccountCarrierConfigFindUniqueArgs} args - Arguments to find a AccountCarrierConfig
   * @example
   * // Get one AccountCarrierConfig
   * const accountCarrierConfig = await prisma.accountCarrierConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccountCarrierConfigFindUniqueArgs>(args: Prisma.SelectSubset<T, AccountCarrierConfigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccountCarrierConfigClient<runtime.Types.Result.GetResult<Prisma.$AccountCarrierConfigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AccountCarrierConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccountCarrierConfigFindUniqueOrThrowArgs} args - Arguments to find a AccountCarrierConfig
   * @example
   * // Get one AccountCarrierConfig
   * const accountCarrierConfig = await prisma.accountCarrierConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccountCarrierConfigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccountCarrierConfigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountCarrierConfigClient<runtime.Types.Result.GetResult<Prisma.$AccountCarrierConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccountCarrierConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountCarrierConfigFindFirstArgs} args - Arguments to find a AccountCarrierConfig
   * @example
   * // Get one AccountCarrierConfig
   * const accountCarrierConfig = await prisma.accountCarrierConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccountCarrierConfigFindFirstArgs>(args?: Prisma.SelectSubset<T, AccountCarrierConfigFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccountCarrierConfigClient<runtime.Types.Result.GetResult<Prisma.$AccountCarrierConfigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccountCarrierConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountCarrierConfigFindFirstOrThrowArgs} args - Arguments to find a AccountCarrierConfig
   * @example
   * // Get one AccountCarrierConfig
   * const accountCarrierConfig = await prisma.accountCarrierConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccountCarrierConfigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccountCarrierConfigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountCarrierConfigClient<runtime.Types.Result.GetResult<Prisma.$AccountCarrierConfigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AccountCarrierConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountCarrierConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AccountCarrierConfigs
   * const accountCarrierConfigs = await prisma.accountCarrierConfig.findMany()
   * 
   * // Get first 10 AccountCarrierConfigs
   * const accountCarrierConfigs = await prisma.accountCarrierConfig.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accountCarrierConfigWithIdOnly = await prisma.accountCarrierConfig.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccountCarrierConfigFindManyArgs>(args?: Prisma.SelectSubset<T, AccountCarrierConfigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountCarrierConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AccountCarrierConfig.
   * @param {AccountCarrierConfigCreateArgs} args - Arguments to create a AccountCarrierConfig.
   * @example
   * // Create one AccountCarrierConfig
   * const AccountCarrierConfig = await prisma.accountCarrierConfig.create({
   *   data: {
   *     // ... data to create a AccountCarrierConfig
   *   }
   * })
   * 
   */
  create<T extends AccountCarrierConfigCreateArgs>(args: Prisma.SelectSubset<T, AccountCarrierConfigCreateArgs<ExtArgs>>): Prisma.Prisma__AccountCarrierConfigClient<runtime.Types.Result.GetResult<Prisma.$AccountCarrierConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AccountCarrierConfigs.
   * @param {AccountCarrierConfigCreateManyArgs} args - Arguments to create many AccountCarrierConfigs.
   * @example
   * // Create many AccountCarrierConfigs
   * const accountCarrierConfig = await prisma.accountCarrierConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccountCarrierConfigCreateManyArgs>(args?: Prisma.SelectSubset<T, AccountCarrierConfigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AccountCarrierConfigs and returns the data saved in the database.
   * @param {AccountCarrierConfigCreateManyAndReturnArgs} args - Arguments to create many AccountCarrierConfigs.
   * @example
   * // Create many AccountCarrierConfigs
   * const accountCarrierConfig = await prisma.accountCarrierConfig.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AccountCarrierConfigs and only return the `id`
   * const accountCarrierConfigWithIdOnly = await prisma.accountCarrierConfig.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccountCarrierConfigCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccountCarrierConfigCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountCarrierConfigPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AccountCarrierConfig.
   * @param {AccountCarrierConfigDeleteArgs} args - Arguments to delete one AccountCarrierConfig.
   * @example
   * // Delete one AccountCarrierConfig
   * const AccountCarrierConfig = await prisma.accountCarrierConfig.delete({
   *   where: {
   *     // ... filter to delete one AccountCarrierConfig
   *   }
   * })
   * 
   */
  delete<T extends AccountCarrierConfigDeleteArgs>(args: Prisma.SelectSubset<T, AccountCarrierConfigDeleteArgs<ExtArgs>>): Prisma.Prisma__AccountCarrierConfigClient<runtime.Types.Result.GetResult<Prisma.$AccountCarrierConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AccountCarrierConfig.
   * @param {AccountCarrierConfigUpdateArgs} args - Arguments to update one AccountCarrierConfig.
   * @example
   * // Update one AccountCarrierConfig
   * const accountCarrierConfig = await prisma.accountCarrierConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccountCarrierConfigUpdateArgs>(args: Prisma.SelectSubset<T, AccountCarrierConfigUpdateArgs<ExtArgs>>): Prisma.Prisma__AccountCarrierConfigClient<runtime.Types.Result.GetResult<Prisma.$AccountCarrierConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AccountCarrierConfigs.
   * @param {AccountCarrierConfigDeleteManyArgs} args - Arguments to filter AccountCarrierConfigs to delete.
   * @example
   * // Delete a few AccountCarrierConfigs
   * const { count } = await prisma.accountCarrierConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccountCarrierConfigDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccountCarrierConfigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccountCarrierConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountCarrierConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AccountCarrierConfigs
   * const accountCarrierConfig = await prisma.accountCarrierConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccountCarrierConfigUpdateManyArgs>(args: Prisma.SelectSubset<T, AccountCarrierConfigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccountCarrierConfigs and returns the data updated in the database.
   * @param {AccountCarrierConfigUpdateManyAndReturnArgs} args - Arguments to update many AccountCarrierConfigs.
   * @example
   * // Update many AccountCarrierConfigs
   * const accountCarrierConfig = await prisma.accountCarrierConfig.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AccountCarrierConfigs and only return the `id`
   * const accountCarrierConfigWithIdOnly = await prisma.accountCarrierConfig.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccountCarrierConfigUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccountCarrierConfigUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountCarrierConfigPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AccountCarrierConfig.
   * @param {AccountCarrierConfigUpsertArgs} args - Arguments to update or create a AccountCarrierConfig.
   * @example
   * // Update or create a AccountCarrierConfig
   * const accountCarrierConfig = await prisma.accountCarrierConfig.upsert({
   *   create: {
   *     // ... data to create a AccountCarrierConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AccountCarrierConfig we want to update
   *   }
   * })
   */
  upsert<T extends AccountCarrierConfigUpsertArgs>(args: Prisma.SelectSubset<T, AccountCarrierConfigUpsertArgs<ExtArgs>>): Prisma.Prisma__AccountCarrierConfigClient<runtime.Types.Result.GetResult<Prisma.$AccountCarrierConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AccountCarrierConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountCarrierConfigCountArgs} args - Arguments to filter AccountCarrierConfigs to count.
   * @example
   * // Count the number of AccountCarrierConfigs
   * const count = await prisma.accountCarrierConfig.count({
   *   where: {
   *     // ... the filter for the AccountCarrierConfigs we want to count
   *   }
   * })
  **/
  count<T extends AccountCarrierConfigCountArgs>(
    args?: Prisma.Subset<T, AccountCarrierConfigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccountCarrierConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AccountCarrierConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountCarrierConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccountCarrierConfigAggregateArgs>(args: Prisma.Subset<T, AccountCarrierConfigAggregateArgs>): Prisma.PrismaPromise<GetAccountCarrierConfigAggregateType<T>>

  /**
   * Group by AccountCarrierConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountCarrierConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccountCarrierConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccountCarrierConfigGroupByArgs['orderBy'] }
      : { orderBy?: AccountCarrierConfigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccountCarrierConfigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccountCarrierConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AccountCarrierConfig model
 */
readonly fields: AccountCarrierConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AccountCarrierConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccountCarrierConfigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  accountCarrier<T extends Prisma.AccountCarrierDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccountCarrierDefaultArgs<ExtArgs>>): Prisma.Prisma__AccountCarrierClient<runtime.Types.Result.GetResult<Prisma.$AccountCarrierPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AccountCarrierConfig model
 */
export interface AccountCarrierConfigFieldRefs {
  readonly id: Prisma.FieldRef<"AccountCarrierConfig", 'String'>
  readonly accountCarrierId: Prisma.FieldRef<"AccountCarrierConfig", 'String'>
  readonly tenantId: Prisma.FieldRef<"AccountCarrierConfig", 'String'>
  readonly consignmentPrefix: Prisma.FieldRef<"AccountCarrierConfig", 'String'>
  readonly consignmentMax: Prisma.FieldRef<"AccountCarrierConfig", 'Int'>
  readonly consignmentMin: Prisma.FieldRef<"AccountCarrierConfig", 'Int'>
  readonly consignmentNextId: Prisma.FieldRef<"AccountCarrierConfig", 'Int'>
  readonly manifestPrefix: Prisma.FieldRef<"AccountCarrierConfig", 'String'>
  readonly manifestMax: Prisma.FieldRef<"AccountCarrierConfig", 'Int'>
  readonly manifestMin: Prisma.FieldRef<"AccountCarrierConfig", 'Int'>
  readonly manifestNextId: Prisma.FieldRef<"AccountCarrierConfig", 'Int'>
  readonly atlCodePrefix: Prisma.FieldRef<"AccountCarrierConfig", 'String'>
  readonly atlCodeMax: Prisma.FieldRef<"AccountCarrierConfig", 'Int'>
  readonly atlCodeMin: Prisma.FieldRef<"AccountCarrierConfig", 'Int'>
  readonly atlCodeLength: Prisma.FieldRef<"AccountCarrierConfig", 'Int'>
  readonly atlCodeNextId: Prisma.FieldRef<"AccountCarrierConfig", 'Int'>
  readonly createdAt: Prisma.FieldRef<"AccountCarrierConfig", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AccountCarrierConfig", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AccountCarrierConfig findUnique
 */
export type AccountCarrierConfigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCarrierConfig
   */
  select?: Prisma.AccountCarrierConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountCarrierConfig
   */
  omit?: Prisma.AccountCarrierConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountCarrierConfigInclude<ExtArgs> | null
  /**
   * Filter, which AccountCarrierConfig to fetch.
   */
  where: Prisma.AccountCarrierConfigWhereUniqueInput
}

/**
 * AccountCarrierConfig findUniqueOrThrow
 */
export type AccountCarrierConfigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCarrierConfig
   */
  select?: Prisma.AccountCarrierConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountCarrierConfig
   */
  omit?: Prisma.AccountCarrierConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountCarrierConfigInclude<ExtArgs> | null
  /**
   * Filter, which AccountCarrierConfig to fetch.
   */
  where: Prisma.AccountCarrierConfigWhereUniqueInput
}

/**
 * AccountCarrierConfig findFirst
 */
export type AccountCarrierConfigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCarrierConfig
   */
  select?: Prisma.AccountCarrierConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountCarrierConfig
   */
  omit?: Prisma.AccountCarrierConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountCarrierConfigInclude<ExtArgs> | null
  /**
   * Filter, which AccountCarrierConfig to fetch.
   */
  where?: Prisma.AccountCarrierConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountCarrierConfigs to fetch.
   */
  orderBy?: Prisma.AccountCarrierConfigOrderByWithRelationInput | Prisma.AccountCarrierConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccountCarrierConfigs.
   */
  cursor?: Prisma.AccountCarrierConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountCarrierConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountCarrierConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountCarrierConfigs.
   */
  distinct?: Prisma.AccountCarrierConfigScalarFieldEnum | Prisma.AccountCarrierConfigScalarFieldEnum[]
}

/**
 * AccountCarrierConfig findFirstOrThrow
 */
export type AccountCarrierConfigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCarrierConfig
   */
  select?: Prisma.AccountCarrierConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountCarrierConfig
   */
  omit?: Prisma.AccountCarrierConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountCarrierConfigInclude<ExtArgs> | null
  /**
   * Filter, which AccountCarrierConfig to fetch.
   */
  where?: Prisma.AccountCarrierConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountCarrierConfigs to fetch.
   */
  orderBy?: Prisma.AccountCarrierConfigOrderByWithRelationInput | Prisma.AccountCarrierConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccountCarrierConfigs.
   */
  cursor?: Prisma.AccountCarrierConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountCarrierConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountCarrierConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountCarrierConfigs.
   */
  distinct?: Prisma.AccountCarrierConfigScalarFieldEnum | Prisma.AccountCarrierConfigScalarFieldEnum[]
}

/**
 * AccountCarrierConfig findMany
 */
export type AccountCarrierConfigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCarrierConfig
   */
  select?: Prisma.AccountCarrierConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountCarrierConfig
   */
  omit?: Prisma.AccountCarrierConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountCarrierConfigInclude<ExtArgs> | null
  /**
   * Filter, which AccountCarrierConfigs to fetch.
   */
  where?: Prisma.AccountCarrierConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountCarrierConfigs to fetch.
   */
  orderBy?: Prisma.AccountCarrierConfigOrderByWithRelationInput | Prisma.AccountCarrierConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AccountCarrierConfigs.
   */
  cursor?: Prisma.AccountCarrierConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountCarrierConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountCarrierConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountCarrierConfigs.
   */
  distinct?: Prisma.AccountCarrierConfigScalarFieldEnum | Prisma.AccountCarrierConfigScalarFieldEnum[]
}

/**
 * AccountCarrierConfig create
 */
export type AccountCarrierConfigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCarrierConfig
   */
  select?: Prisma.AccountCarrierConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountCarrierConfig
   */
  omit?: Prisma.AccountCarrierConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountCarrierConfigInclude<ExtArgs> | null
  /**
   * The data needed to create a AccountCarrierConfig.
   */
  data: Prisma.XOR<Prisma.AccountCarrierConfigCreateInput, Prisma.AccountCarrierConfigUncheckedCreateInput>
}

/**
 * AccountCarrierConfig createMany
 */
export type AccountCarrierConfigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AccountCarrierConfigs.
   */
  data: Prisma.AccountCarrierConfigCreateManyInput | Prisma.AccountCarrierConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccountCarrierConfig createManyAndReturn
 */
export type AccountCarrierConfigCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCarrierConfig
   */
  select?: Prisma.AccountCarrierConfigSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccountCarrierConfig
   */
  omit?: Prisma.AccountCarrierConfigOmit<ExtArgs> | null
  /**
   * The data used to create many AccountCarrierConfigs.
   */
  data: Prisma.AccountCarrierConfigCreateManyInput | Prisma.AccountCarrierConfigCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountCarrierConfigIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AccountCarrierConfig update
 */
export type AccountCarrierConfigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCarrierConfig
   */
  select?: Prisma.AccountCarrierConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountCarrierConfig
   */
  omit?: Prisma.AccountCarrierConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountCarrierConfigInclude<ExtArgs> | null
  /**
   * The data needed to update a AccountCarrierConfig.
   */
  data: Prisma.XOR<Prisma.AccountCarrierConfigUpdateInput, Prisma.AccountCarrierConfigUncheckedUpdateInput>
  /**
   * Choose, which AccountCarrierConfig to update.
   */
  where: Prisma.AccountCarrierConfigWhereUniqueInput
}

/**
 * AccountCarrierConfig updateMany
 */
export type AccountCarrierConfigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AccountCarrierConfigs.
   */
  data: Prisma.XOR<Prisma.AccountCarrierConfigUpdateManyMutationInput, Prisma.AccountCarrierConfigUncheckedUpdateManyInput>
  /**
   * Filter which AccountCarrierConfigs to update
   */
  where?: Prisma.AccountCarrierConfigWhereInput
  /**
   * Limit how many AccountCarrierConfigs to update.
   */
  limit?: number
}

/**
 * AccountCarrierConfig updateManyAndReturn
 */
export type AccountCarrierConfigUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCarrierConfig
   */
  select?: Prisma.AccountCarrierConfigSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccountCarrierConfig
   */
  omit?: Prisma.AccountCarrierConfigOmit<ExtArgs> | null
  /**
   * The data used to update AccountCarrierConfigs.
   */
  data: Prisma.XOR<Prisma.AccountCarrierConfigUpdateManyMutationInput, Prisma.AccountCarrierConfigUncheckedUpdateManyInput>
  /**
   * Filter which AccountCarrierConfigs to update
   */
  where?: Prisma.AccountCarrierConfigWhereInput
  /**
   * Limit how many AccountCarrierConfigs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountCarrierConfigIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AccountCarrierConfig upsert
 */
export type AccountCarrierConfigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCarrierConfig
   */
  select?: Prisma.AccountCarrierConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountCarrierConfig
   */
  omit?: Prisma.AccountCarrierConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountCarrierConfigInclude<ExtArgs> | null
  /**
   * The filter to search for the AccountCarrierConfig to update in case it exists.
   */
  where: Prisma.AccountCarrierConfigWhereUniqueInput
  /**
   * In case the AccountCarrierConfig found by the `where` argument doesn't exist, create a new AccountCarrierConfig with this data.
   */
  create: Prisma.XOR<Prisma.AccountCarrierConfigCreateInput, Prisma.AccountCarrierConfigUncheckedCreateInput>
  /**
   * In case the AccountCarrierConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccountCarrierConfigUpdateInput, Prisma.AccountCarrierConfigUncheckedUpdateInput>
}

/**
 * AccountCarrierConfig delete
 */
export type AccountCarrierConfigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCarrierConfig
   */
  select?: Prisma.AccountCarrierConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountCarrierConfig
   */
  omit?: Prisma.AccountCarrierConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountCarrierConfigInclude<ExtArgs> | null
  /**
   * Filter which AccountCarrierConfig to delete.
   */
  where: Prisma.AccountCarrierConfigWhereUniqueInput
}

/**
 * AccountCarrierConfig deleteMany
 */
export type AccountCarrierConfigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccountCarrierConfigs to delete
   */
  where?: Prisma.AccountCarrierConfigWhereInput
  /**
   * Limit how many AccountCarrierConfigs to delete.
   */
  limit?: number
}

/**
 * AccountCarrierConfig without action
 */
export type AccountCarrierConfigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCarrierConfig
   */
  select?: Prisma.AccountCarrierConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountCarrierConfig
   */
  omit?: Prisma.AccountCarrierConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountCarrierConfigInclude<ExtArgs> | null
}
