
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DraftShipment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DraftShipment
 * 
 */
export type DraftShipmentModel = runtime.Types.Result.DefaultSelection<Prisma.$DraftShipmentPayload>

export type AggregateDraftShipment = {
  _count: DraftShipmentCountAggregateOutputType | null
  _avg: DraftShipmentAvgAggregateOutputType | null
  _sum: DraftShipmentSumAggregateOutputType | null
  _min: DraftShipmentMinAggregateOutputType | null
  _max: DraftShipmentMaxAggregateOutputType | null
}

export type DraftShipmentAvgAggregateOutputType = {
  estimatedPrice: runtime.Decimal | null
  totalQuantity: number | null
  totalWeight: runtime.Decimal | null
  totalVolume: runtime.Decimal | null
}

export type DraftShipmentSumAggregateOutputType = {
  estimatedPrice: runtime.Decimal | null
  totalQuantity: number | null
  totalWeight: runtime.Decimal | null
  totalVolume: runtime.Decimal | null
}

export type DraftShipmentMinAggregateOutputType = {
  id: string | null
  accountId: string | null
  customerGroupId: string | null
  dispatchDate: Date | null
  senderName: string | null
  senderAddress: string | null
  senderCountry: string | null
  senderState: string | null
  senderSuburb: string | null
  senderPostcode: string | null
  receiverName: string | null
  receiverAddress: string | null
  receiverState: string | null
  receiverPostcode: string | null
  receiverCountry: string | null
  receiverSuburb: string | null
  carrier: string | null
  serviceName: string | null
  estimatedPrice: runtime.Decimal | null
  shipmentReferenceId: string | null
  status: $Enums.ShipmentStatus | null
  tenantId: string | null
  createdAt: Date | null
  eta: string | null
  internalReference: string | null
  consignmentReference: string | null
  totalQuantity: number | null
  totalWeight: runtime.Decimal | null
  totalVolume: runtime.Decimal | null
  thirdPartyAccountNumber: string | null
  deleted: boolean | null
}

export type DraftShipmentMaxAggregateOutputType = {
  id: string | null
  accountId: string | null
  customerGroupId: string | null
  dispatchDate: Date | null
  senderName: string | null
  senderAddress: string | null
  senderCountry: string | null
  senderState: string | null
  senderSuburb: string | null
  senderPostcode: string | null
  receiverName: string | null
  receiverAddress: string | null
  receiverState: string | null
  receiverPostcode: string | null
  receiverCountry: string | null
  receiverSuburb: string | null
  carrier: string | null
  serviceName: string | null
  estimatedPrice: runtime.Decimal | null
  shipmentReferenceId: string | null
  status: $Enums.ShipmentStatus | null
  tenantId: string | null
  createdAt: Date | null
  eta: string | null
  internalReference: string | null
  consignmentReference: string | null
  totalQuantity: number | null
  totalWeight: runtime.Decimal | null
  totalVolume: runtime.Decimal | null
  thirdPartyAccountNumber: string | null
  deleted: boolean | null
}

export type DraftShipmentCountAggregateOutputType = {
  id: number
  data: number
  accountId: number
  customerGroupId: number
  dispatchDate: number
  senderName: number
  senderAddress: number
  senderCountry: number
  senderState: number
  senderSuburb: number
  senderPostcode: number
  receiverName: number
  receiverAddress: number
  receiverState: number
  receiverPostcode: number
  receiverCountry: number
  receiverSuburb: number
  carrier: number
  serviceName: number
  estimatedPrice: number
  shipmentReferenceId: number
  status: number
  tenantId: number
  createdAt: number
  eta: number
  internalReference: number
  consignmentReference: number
  totalQuantity: number
  totalWeight: number
  totalVolume: number
  thirdPartyAccountNumber: number
  deleted: number
  _all: number
}


export type DraftShipmentAvgAggregateInputType = {
  estimatedPrice?: true
  totalQuantity?: true
  totalWeight?: true
  totalVolume?: true
}

export type DraftShipmentSumAggregateInputType = {
  estimatedPrice?: true
  totalQuantity?: true
  totalWeight?: true
  totalVolume?: true
}

export type DraftShipmentMinAggregateInputType = {
  id?: true
  accountId?: true
  customerGroupId?: true
  dispatchDate?: true
  senderName?: true
  senderAddress?: true
  senderCountry?: true
  senderState?: true
  senderSuburb?: true
  senderPostcode?: true
  receiverName?: true
  receiverAddress?: true
  receiverState?: true
  receiverPostcode?: true
  receiverCountry?: true
  receiverSuburb?: true
  carrier?: true
  serviceName?: true
  estimatedPrice?: true
  shipmentReferenceId?: true
  status?: true
  tenantId?: true
  createdAt?: true
  eta?: true
  internalReference?: true
  consignmentReference?: true
  totalQuantity?: true
  totalWeight?: true
  totalVolume?: true
  thirdPartyAccountNumber?: true
  deleted?: true
}

export type DraftShipmentMaxAggregateInputType = {
  id?: true
  accountId?: true
  customerGroupId?: true
  dispatchDate?: true
  senderName?: true
  senderAddress?: true
  senderCountry?: true
  senderState?: true
  senderSuburb?: true
  senderPostcode?: true
  receiverName?: true
  receiverAddress?: true
  receiverState?: true
  receiverPostcode?: true
  receiverCountry?: true
  receiverSuburb?: true
  carrier?: true
  serviceName?: true
  estimatedPrice?: true
  shipmentReferenceId?: true
  status?: true
  tenantId?: true
  createdAt?: true
  eta?: true
  internalReference?: true
  consignmentReference?: true
  totalQuantity?: true
  totalWeight?: true
  totalVolume?: true
  thirdPartyAccountNumber?: true
  deleted?: true
}

export type DraftShipmentCountAggregateInputType = {
  id?: true
  data?: true
  accountId?: true
  customerGroupId?: true
  dispatchDate?: true
  senderName?: true
  senderAddress?: true
  senderCountry?: true
  senderState?: true
  senderSuburb?: true
  senderPostcode?: true
  receiverName?: true
  receiverAddress?: true
  receiverState?: true
  receiverPostcode?: true
  receiverCountry?: true
  receiverSuburb?: true
  carrier?: true
  serviceName?: true
  estimatedPrice?: true
  shipmentReferenceId?: true
  status?: true
  tenantId?: true
  createdAt?: true
  eta?: true
  internalReference?: true
  consignmentReference?: true
  totalQuantity?: true
  totalWeight?: true
  totalVolume?: true
  thirdPartyAccountNumber?: true
  deleted?: true
  _all?: true
}

export type DraftShipmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DraftShipment to aggregate.
   */
  where?: Prisma.DraftShipmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DraftShipments to fetch.
   */
  orderBy?: Prisma.DraftShipmentOrderByWithRelationInput | Prisma.DraftShipmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DraftShipmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DraftShipments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DraftShipments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DraftShipments
  **/
  _count?: true | DraftShipmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DraftShipmentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DraftShipmentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DraftShipmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DraftShipmentMaxAggregateInputType
}

export type GetDraftShipmentAggregateType<T extends DraftShipmentAggregateArgs> = {
      [P in keyof T & keyof AggregateDraftShipment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDraftShipment[P]>
    : Prisma.GetScalarType<T[P], AggregateDraftShipment[P]>
}




export type DraftShipmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DraftShipmentWhereInput
  orderBy?: Prisma.DraftShipmentOrderByWithAggregationInput | Prisma.DraftShipmentOrderByWithAggregationInput[]
  by: Prisma.DraftShipmentScalarFieldEnum[] | Prisma.DraftShipmentScalarFieldEnum
  having?: Prisma.DraftShipmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DraftShipmentCountAggregateInputType | true
  _avg?: DraftShipmentAvgAggregateInputType
  _sum?: DraftShipmentSumAggregateInputType
  _min?: DraftShipmentMinAggregateInputType
  _max?: DraftShipmentMaxAggregateInputType
}

export type DraftShipmentGroupByOutputType = {
  id: string
  data: runtime.JsonValue
  accountId: string
  customerGroupId: string
  dispatchDate: Date | null
  senderName: string | null
  senderAddress: string | null
  senderCountry: string | null
  senderState: string | null
  senderSuburb: string | null
  senderPostcode: string | null
  receiverName: string | null
  receiverAddress: string | null
  receiverState: string | null
  receiverPostcode: string | null
  receiverCountry: string | null
  receiverSuburb: string | null
  carrier: string | null
  serviceName: string | null
  estimatedPrice: runtime.Decimal | null
  shipmentReferenceId: string | null
  status: $Enums.ShipmentStatus | null
  tenantId: string
  createdAt: Date
  eta: string | null
  internalReference: string | null
  consignmentReference: string | null
  totalQuantity: number | null
  totalWeight: runtime.Decimal | null
  totalVolume: runtime.Decimal | null
  thirdPartyAccountNumber: string | null
  deleted: boolean
  _count: DraftShipmentCountAggregateOutputType | null
  _avg: DraftShipmentAvgAggregateOutputType | null
  _sum: DraftShipmentSumAggregateOutputType | null
  _min: DraftShipmentMinAggregateOutputType | null
  _max: DraftShipmentMaxAggregateOutputType | null
}

export type GetDraftShipmentGroupByPayload<T extends DraftShipmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DraftShipmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DraftShipmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DraftShipmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DraftShipmentGroupByOutputType[P]>
      }
    >
  >



export type DraftShipmentWhereInput = {
  AND?: Prisma.DraftShipmentWhereInput | Prisma.DraftShipmentWhereInput[]
  OR?: Prisma.DraftShipmentWhereInput[]
  NOT?: Prisma.DraftShipmentWhereInput | Prisma.DraftShipmentWhereInput[]
  id?: Prisma.UuidFilter<"DraftShipment"> | string
  data?: Prisma.JsonFilter<"DraftShipment">
  accountId?: Prisma.UuidFilter<"DraftShipment"> | string
  customerGroupId?: Prisma.UuidFilter<"DraftShipment"> | string
  dispatchDate?: Prisma.DateTimeNullableFilter<"DraftShipment"> | Date | string | null
  senderName?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  senderAddress?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  senderCountry?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  senderState?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  senderSuburb?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  senderPostcode?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  receiverName?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  receiverAddress?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  receiverState?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  receiverPostcode?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  receiverCountry?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  receiverSuburb?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  carrier?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  serviceName?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  estimatedPrice?: Prisma.DecimalNullableFilter<"DraftShipment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  shipmentReferenceId?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  status?: Prisma.EnumShipmentStatusNullableFilter<"DraftShipment"> | $Enums.ShipmentStatus | null
  tenantId?: Prisma.UuidFilter<"DraftShipment"> | string
  createdAt?: Prisma.DateTimeFilter<"DraftShipment"> | Date | string
  eta?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  internalReference?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  consignmentReference?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  totalQuantity?: Prisma.IntNullableFilter<"DraftShipment"> | number | null
  totalWeight?: Prisma.DecimalNullableFilter<"DraftShipment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  totalVolume?: Prisma.DecimalNullableFilter<"DraftShipment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  thirdPartyAccountNumber?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  deleted?: Prisma.BoolFilter<"DraftShipment"> | boolean
}

export type DraftShipmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  customerGroupId?: Prisma.SortOrder
  dispatchDate?: Prisma.SortOrderInput | Prisma.SortOrder
  senderName?: Prisma.SortOrderInput | Prisma.SortOrder
  senderAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  senderCountry?: Prisma.SortOrderInput | Prisma.SortOrder
  senderState?: Prisma.SortOrderInput | Prisma.SortOrder
  senderSuburb?: Prisma.SortOrderInput | Prisma.SortOrder
  senderPostcode?: Prisma.SortOrderInput | Prisma.SortOrder
  receiverName?: Prisma.SortOrderInput | Prisma.SortOrder
  receiverAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  receiverState?: Prisma.SortOrderInput | Prisma.SortOrder
  receiverPostcode?: Prisma.SortOrderInput | Prisma.SortOrder
  receiverCountry?: Prisma.SortOrderInput | Prisma.SortOrder
  receiverSuburb?: Prisma.SortOrderInput | Prisma.SortOrder
  carrier?: Prisma.SortOrderInput | Prisma.SortOrder
  serviceName?: Prisma.SortOrderInput | Prisma.SortOrder
  estimatedPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  shipmentReferenceId?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  eta?: Prisma.SortOrderInput | Prisma.SortOrder
  internalReference?: Prisma.SortOrderInput | Prisma.SortOrder
  consignmentReference?: Prisma.SortOrderInput | Prisma.SortOrder
  totalQuantity?: Prisma.SortOrderInput | Prisma.SortOrder
  totalWeight?: Prisma.SortOrderInput | Prisma.SortOrder
  totalVolume?: Prisma.SortOrderInput | Prisma.SortOrder
  thirdPartyAccountNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type DraftShipmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  shipmentReferenceId?: string
  AND?: Prisma.DraftShipmentWhereInput | Prisma.DraftShipmentWhereInput[]
  OR?: Prisma.DraftShipmentWhereInput[]
  NOT?: Prisma.DraftShipmentWhereInput | Prisma.DraftShipmentWhereInput[]
  data?: Prisma.JsonFilter<"DraftShipment">
  accountId?: Prisma.UuidFilter<"DraftShipment"> | string
  customerGroupId?: Prisma.UuidFilter<"DraftShipment"> | string
  dispatchDate?: Prisma.DateTimeNullableFilter<"DraftShipment"> | Date | string | null
  senderName?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  senderAddress?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  senderCountry?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  senderState?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  senderSuburb?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  senderPostcode?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  receiverName?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  receiverAddress?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  receiverState?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  receiverPostcode?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  receiverCountry?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  receiverSuburb?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  carrier?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  serviceName?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  estimatedPrice?: Prisma.DecimalNullableFilter<"DraftShipment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.EnumShipmentStatusNullableFilter<"DraftShipment"> | $Enums.ShipmentStatus | null
  tenantId?: Prisma.UuidFilter<"DraftShipment"> | string
  createdAt?: Prisma.DateTimeFilter<"DraftShipment"> | Date | string
  eta?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  internalReference?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  consignmentReference?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  totalQuantity?: Prisma.IntNullableFilter<"DraftShipment"> | number | null
  totalWeight?: Prisma.DecimalNullableFilter<"DraftShipment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  totalVolume?: Prisma.DecimalNullableFilter<"DraftShipment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  thirdPartyAccountNumber?: Prisma.StringNullableFilter<"DraftShipment"> | string | null
  deleted?: Prisma.BoolFilter<"DraftShipment"> | boolean
}, "id" | "shipmentReferenceId">

export type DraftShipmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  customerGroupId?: Prisma.SortOrder
  dispatchDate?: Prisma.SortOrderInput | Prisma.SortOrder
  senderName?: Prisma.SortOrderInput | Prisma.SortOrder
  senderAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  senderCountry?: Prisma.SortOrderInput | Prisma.SortOrder
  senderState?: Prisma.SortOrderInput | Prisma.SortOrder
  senderSuburb?: Prisma.SortOrderInput | Prisma.SortOrder
  senderPostcode?: Prisma.SortOrderInput | Prisma.SortOrder
  receiverName?: Prisma.SortOrderInput | Prisma.SortOrder
  receiverAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  receiverState?: Prisma.SortOrderInput | Prisma.SortOrder
  receiverPostcode?: Prisma.SortOrderInput | Prisma.SortOrder
  receiverCountry?: Prisma.SortOrderInput | Prisma.SortOrder
  receiverSuburb?: Prisma.SortOrderInput | Prisma.SortOrder
  carrier?: Prisma.SortOrderInput | Prisma.SortOrder
  serviceName?: Prisma.SortOrderInput | Prisma.SortOrder
  estimatedPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  shipmentReferenceId?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  eta?: Prisma.SortOrderInput | Prisma.SortOrder
  internalReference?: Prisma.SortOrderInput | Prisma.SortOrder
  consignmentReference?: Prisma.SortOrderInput | Prisma.SortOrder
  totalQuantity?: Prisma.SortOrderInput | Prisma.SortOrder
  totalWeight?: Prisma.SortOrderInput | Prisma.SortOrder
  totalVolume?: Prisma.SortOrderInput | Prisma.SortOrder
  thirdPartyAccountNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted?: Prisma.SortOrder
  _count?: Prisma.DraftShipmentCountOrderByAggregateInput
  _avg?: Prisma.DraftShipmentAvgOrderByAggregateInput
  _max?: Prisma.DraftShipmentMaxOrderByAggregateInput
  _min?: Prisma.DraftShipmentMinOrderByAggregateInput
  _sum?: Prisma.DraftShipmentSumOrderByAggregateInput
}

export type DraftShipmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.DraftShipmentScalarWhereWithAggregatesInput | Prisma.DraftShipmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.DraftShipmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DraftShipmentScalarWhereWithAggregatesInput | Prisma.DraftShipmentScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"DraftShipment"> | string
  data?: Prisma.JsonWithAggregatesFilter<"DraftShipment">
  accountId?: Prisma.UuidWithAggregatesFilter<"DraftShipment"> | string
  customerGroupId?: Prisma.UuidWithAggregatesFilter<"DraftShipment"> | string
  dispatchDate?: Prisma.DateTimeNullableWithAggregatesFilter<"DraftShipment"> | Date | string | null
  senderName?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  senderAddress?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  senderCountry?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  senderState?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  senderSuburb?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  senderPostcode?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  receiverName?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  receiverAddress?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  receiverState?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  receiverPostcode?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  receiverCountry?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  receiverSuburb?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  carrier?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  serviceName?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  estimatedPrice?: Prisma.DecimalNullableWithAggregatesFilter<"DraftShipment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  shipmentReferenceId?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  status?: Prisma.EnumShipmentStatusNullableWithAggregatesFilter<"DraftShipment"> | $Enums.ShipmentStatus | null
  tenantId?: Prisma.UuidWithAggregatesFilter<"DraftShipment"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DraftShipment"> | Date | string
  eta?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  internalReference?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  consignmentReference?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  totalQuantity?: Prisma.IntNullableWithAggregatesFilter<"DraftShipment"> | number | null
  totalWeight?: Prisma.DecimalNullableWithAggregatesFilter<"DraftShipment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  totalVolume?: Prisma.DecimalNullableWithAggregatesFilter<"DraftShipment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  thirdPartyAccountNumber?: Prisma.StringNullableWithAggregatesFilter<"DraftShipment"> | string | null
  deleted?: Prisma.BoolWithAggregatesFilter<"DraftShipment"> | boolean
}

export type DraftShipmentCreateInput = {
  id?: string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  accountId: string
  customerGroupId: string
  dispatchDate?: Date | string | null
  senderName?: string | null
  senderAddress?: string | null
  senderCountry?: string | null
  senderState?: string | null
  senderSuburb?: string | null
  senderPostcode?: string | null
  receiverName?: string | null
  receiverAddress?: string | null
  receiverState?: string | null
  receiverPostcode?: string | null
  receiverCountry?: string | null
  receiverSuburb?: string | null
  carrier?: string | null
  serviceName?: string | null
  estimatedPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  shipmentReferenceId?: string | null
  status?: $Enums.ShipmentStatus | null
  tenantId?: string
  createdAt?: Date | string
  eta?: string | null
  internalReference?: string | null
  consignmentReference?: string | null
  totalQuantity?: number | null
  totalWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  totalVolume?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  thirdPartyAccountNumber?: string | null
  deleted?: boolean
}

export type DraftShipmentUncheckedCreateInput = {
  id?: string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  accountId: string
  customerGroupId: string
  dispatchDate?: Date | string | null
  senderName?: string | null
  senderAddress?: string | null
  senderCountry?: string | null
  senderState?: string | null
  senderSuburb?: string | null
  senderPostcode?: string | null
  receiverName?: string | null
  receiverAddress?: string | null
  receiverState?: string | null
  receiverPostcode?: string | null
  receiverCountry?: string | null
  receiverSuburb?: string | null
  carrier?: string | null
  serviceName?: string | null
  estimatedPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  shipmentReferenceId?: string | null
  status?: $Enums.ShipmentStatus | null
  tenantId?: string
  createdAt?: Date | string
  eta?: string | null
  internalReference?: string | null
  consignmentReference?: string | null
  totalQuantity?: number | null
  totalWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  totalVolume?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  thirdPartyAccountNumber?: string | null
  deleted?: boolean
}

export type DraftShipmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  customerGroupId?: Prisma.StringFieldUpdateOperationsInput | string
  dispatchDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  senderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderCountry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderSuburb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderPostcode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverPostcode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverCountry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverSuburb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  carrier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  serviceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  shipmentReferenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableEnumShipmentStatusFieldUpdateOperationsInput | $Enums.ShipmentStatus | null
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eta?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  internalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consignmentReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalQuantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  totalWeight?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  totalVolume?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  thirdPartyAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DraftShipmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  customerGroupId?: Prisma.StringFieldUpdateOperationsInput | string
  dispatchDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  senderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderCountry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderSuburb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderPostcode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverPostcode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverCountry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverSuburb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  carrier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  serviceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  shipmentReferenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableEnumShipmentStatusFieldUpdateOperationsInput | $Enums.ShipmentStatus | null
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eta?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  internalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consignmentReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalQuantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  totalWeight?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  totalVolume?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  thirdPartyAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DraftShipmentCreateManyInput = {
  id?: string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  accountId: string
  customerGroupId: string
  dispatchDate?: Date | string | null
  senderName?: string | null
  senderAddress?: string | null
  senderCountry?: string | null
  senderState?: string | null
  senderSuburb?: string | null
  senderPostcode?: string | null
  receiverName?: string | null
  receiverAddress?: string | null
  receiverState?: string | null
  receiverPostcode?: string | null
  receiverCountry?: string | null
  receiverSuburb?: string | null
  carrier?: string | null
  serviceName?: string | null
  estimatedPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  shipmentReferenceId?: string | null
  status?: $Enums.ShipmentStatus | null
  tenantId?: string
  createdAt?: Date | string
  eta?: string | null
  internalReference?: string | null
  consignmentReference?: string | null
  totalQuantity?: number | null
  totalWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  totalVolume?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  thirdPartyAccountNumber?: string | null
  deleted?: boolean
}

export type DraftShipmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  customerGroupId?: Prisma.StringFieldUpdateOperationsInput | string
  dispatchDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  senderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderCountry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderSuburb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderPostcode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverPostcode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverCountry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverSuburb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  carrier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  serviceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  shipmentReferenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableEnumShipmentStatusFieldUpdateOperationsInput | $Enums.ShipmentStatus | null
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eta?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  internalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consignmentReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalQuantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  totalWeight?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  totalVolume?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  thirdPartyAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DraftShipmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  customerGroupId?: Prisma.StringFieldUpdateOperationsInput | string
  dispatchDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  senderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderCountry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderSuburb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  senderPostcode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverPostcode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverCountry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receiverSuburb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  carrier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  serviceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  shipmentReferenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableEnumShipmentStatusFieldUpdateOperationsInput | $Enums.ShipmentStatus | null
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eta?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  internalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  consignmentReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalQuantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  totalWeight?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  totalVolume?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  thirdPartyAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DraftShipmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  customerGroupId?: Prisma.SortOrder
  dispatchDate?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  senderAddress?: Prisma.SortOrder
  senderCountry?: Prisma.SortOrder
  senderState?: Prisma.SortOrder
  senderSuburb?: Prisma.SortOrder
  senderPostcode?: Prisma.SortOrder
  receiverName?: Prisma.SortOrder
  receiverAddress?: Prisma.SortOrder
  receiverState?: Prisma.SortOrder
  receiverPostcode?: Prisma.SortOrder
  receiverCountry?: Prisma.SortOrder
  receiverSuburb?: Prisma.SortOrder
  carrier?: Prisma.SortOrder
  serviceName?: Prisma.SortOrder
  estimatedPrice?: Prisma.SortOrder
  shipmentReferenceId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  eta?: Prisma.SortOrder
  internalReference?: Prisma.SortOrder
  consignmentReference?: Prisma.SortOrder
  totalQuantity?: Prisma.SortOrder
  totalWeight?: Prisma.SortOrder
  totalVolume?: Prisma.SortOrder
  thirdPartyAccountNumber?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type DraftShipmentAvgOrderByAggregateInput = {
  estimatedPrice?: Prisma.SortOrder
  totalQuantity?: Prisma.SortOrder
  totalWeight?: Prisma.SortOrder
  totalVolume?: Prisma.SortOrder
}

export type DraftShipmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  customerGroupId?: Prisma.SortOrder
  dispatchDate?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  senderAddress?: Prisma.SortOrder
  senderCountry?: Prisma.SortOrder
  senderState?: Prisma.SortOrder
  senderSuburb?: Prisma.SortOrder
  senderPostcode?: Prisma.SortOrder
  receiverName?: Prisma.SortOrder
  receiverAddress?: Prisma.SortOrder
  receiverState?: Prisma.SortOrder
  receiverPostcode?: Prisma.SortOrder
  receiverCountry?: Prisma.SortOrder
  receiverSuburb?: Prisma.SortOrder
  carrier?: Prisma.SortOrder
  serviceName?: Prisma.SortOrder
  estimatedPrice?: Prisma.SortOrder
  shipmentReferenceId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  eta?: Prisma.SortOrder
  internalReference?: Prisma.SortOrder
  consignmentReference?: Prisma.SortOrder
  totalQuantity?: Prisma.SortOrder
  totalWeight?: Prisma.SortOrder
  totalVolume?: Prisma.SortOrder
  thirdPartyAccountNumber?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type DraftShipmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  customerGroupId?: Prisma.SortOrder
  dispatchDate?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  senderAddress?: Prisma.SortOrder
  senderCountry?: Prisma.SortOrder
  senderState?: Prisma.SortOrder
  senderSuburb?: Prisma.SortOrder
  senderPostcode?: Prisma.SortOrder
  receiverName?: Prisma.SortOrder
  receiverAddress?: Prisma.SortOrder
  receiverState?: Prisma.SortOrder
  receiverPostcode?: Prisma.SortOrder
  receiverCountry?: Prisma.SortOrder
  receiverSuburb?: Prisma.SortOrder
  carrier?: Prisma.SortOrder
  serviceName?: Prisma.SortOrder
  estimatedPrice?: Prisma.SortOrder
  shipmentReferenceId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  eta?: Prisma.SortOrder
  internalReference?: Prisma.SortOrder
  consignmentReference?: Prisma.SortOrder
  totalQuantity?: Prisma.SortOrder
  totalWeight?: Prisma.SortOrder
  totalVolume?: Prisma.SortOrder
  thirdPartyAccountNumber?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type DraftShipmentSumOrderByAggregateInput = {
  estimatedPrice?: Prisma.SortOrder
  totalQuantity?: Prisma.SortOrder
  totalWeight?: Prisma.SortOrder
  totalVolume?: Prisma.SortOrder
}

export type NullableEnumShipmentStatusFieldUpdateOperationsInput = {
  set?: $Enums.ShipmentStatus | null
}



export type DraftShipmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  data?: boolean
  accountId?: boolean
  customerGroupId?: boolean
  dispatchDate?: boolean
  senderName?: boolean
  senderAddress?: boolean
  senderCountry?: boolean
  senderState?: boolean
  senderSuburb?: boolean
  senderPostcode?: boolean
  receiverName?: boolean
  receiverAddress?: boolean
  receiverState?: boolean
  receiverPostcode?: boolean
  receiverCountry?: boolean
  receiverSuburb?: boolean
  carrier?: boolean
  serviceName?: boolean
  estimatedPrice?: boolean
  shipmentReferenceId?: boolean
  status?: boolean
  tenantId?: boolean
  createdAt?: boolean
  eta?: boolean
  internalReference?: boolean
  consignmentReference?: boolean
  totalQuantity?: boolean
  totalWeight?: boolean
  totalVolume?: boolean
  thirdPartyAccountNumber?: boolean
  deleted?: boolean
}, ExtArgs["result"]["draftShipment"]>

export type DraftShipmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  data?: boolean
  accountId?: boolean
  customerGroupId?: boolean
  dispatchDate?: boolean
  senderName?: boolean
  senderAddress?: boolean
  senderCountry?: boolean
  senderState?: boolean
  senderSuburb?: boolean
  senderPostcode?: boolean
  receiverName?: boolean
  receiverAddress?: boolean
  receiverState?: boolean
  receiverPostcode?: boolean
  receiverCountry?: boolean
  receiverSuburb?: boolean
  carrier?: boolean
  serviceName?: boolean
  estimatedPrice?: boolean
  shipmentReferenceId?: boolean
  status?: boolean
  tenantId?: boolean
  createdAt?: boolean
  eta?: boolean
  internalReference?: boolean
  consignmentReference?: boolean
  totalQuantity?: boolean
  totalWeight?: boolean
  totalVolume?: boolean
  thirdPartyAccountNumber?: boolean
  deleted?: boolean
}, ExtArgs["result"]["draftShipment"]>

export type DraftShipmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  data?: boolean
  accountId?: boolean
  customerGroupId?: boolean
  dispatchDate?: boolean
  senderName?: boolean
  senderAddress?: boolean
  senderCountry?: boolean
  senderState?: boolean
  senderSuburb?: boolean
  senderPostcode?: boolean
  receiverName?: boolean
  receiverAddress?: boolean
  receiverState?: boolean
  receiverPostcode?: boolean
  receiverCountry?: boolean
  receiverSuburb?: boolean
  carrier?: boolean
  serviceName?: boolean
  estimatedPrice?: boolean
  shipmentReferenceId?: boolean
  status?: boolean
  tenantId?: boolean
  createdAt?: boolean
  eta?: boolean
  internalReference?: boolean
  consignmentReference?: boolean
  totalQuantity?: boolean
  totalWeight?: boolean
  totalVolume?: boolean
  thirdPartyAccountNumber?: boolean
  deleted?: boolean
}, ExtArgs["result"]["draftShipment"]>

export type DraftShipmentSelectScalar = {
  id?: boolean
  data?: boolean
  accountId?: boolean
  customerGroupId?: boolean
  dispatchDate?: boolean
  senderName?: boolean
  senderAddress?: boolean
  senderCountry?: boolean
  senderState?: boolean
  senderSuburb?: boolean
  senderPostcode?: boolean
  receiverName?: boolean
  receiverAddress?: boolean
  receiverState?: boolean
  receiverPostcode?: boolean
  receiverCountry?: boolean
  receiverSuburb?: boolean
  carrier?: boolean
  serviceName?: boolean
  estimatedPrice?: boolean
  shipmentReferenceId?: boolean
  status?: boolean
  tenantId?: boolean
  createdAt?: boolean
  eta?: boolean
  internalReference?: boolean
  consignmentReference?: boolean
  totalQuantity?: boolean
  totalWeight?: boolean
  totalVolume?: boolean
  thirdPartyAccountNumber?: boolean
  deleted?: boolean
}

export type DraftShipmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "data" | "accountId" | "customerGroupId" | "dispatchDate" | "senderName" | "senderAddress" | "senderCountry" | "senderState" | "senderSuburb" | "senderPostcode" | "receiverName" | "receiverAddress" | "receiverState" | "receiverPostcode" | "receiverCountry" | "receiverSuburb" | "carrier" | "serviceName" | "estimatedPrice" | "shipmentReferenceId" | "status" | "tenantId" | "createdAt" | "eta" | "internalReference" | "consignmentReference" | "totalQuantity" | "totalWeight" | "totalVolume" | "thirdPartyAccountNumber" | "deleted", ExtArgs["result"]["draftShipment"]>

export type $DraftShipmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DraftShipment"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    data: runtime.JsonValue
    accountId: string
    customerGroupId: string
    dispatchDate: Date | null
    senderName: string | null
    senderAddress: string | null
    senderCountry: string | null
    senderState: string | null
    senderSuburb: string | null
    senderPostcode: string | null
    receiverName: string | null
    receiverAddress: string | null
    receiverState: string | null
    receiverPostcode: string | null
    receiverCountry: string | null
    receiverSuburb: string | null
    carrier: string | null
    serviceName: string | null
    estimatedPrice: runtime.Decimal | null
    shipmentReferenceId: string | null
    status: $Enums.ShipmentStatus | null
    tenantId: string
    createdAt: Date
    eta: string | null
    internalReference: string | null
    consignmentReference: string | null
    totalQuantity: number | null
    totalWeight: runtime.Decimal | null
    totalVolume: runtime.Decimal | null
    thirdPartyAccountNumber: string | null
    deleted: boolean
  }, ExtArgs["result"]["draftShipment"]>
  composites: {}
}

export type DraftShipmentGetPayload<S extends boolean | null | undefined | DraftShipmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DraftShipmentPayload, S>

export type DraftShipmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DraftShipmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DraftShipmentCountAggregateInputType | true
  }

export interface DraftShipmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DraftShipment'], meta: { name: 'DraftShipment' } }
  /**
   * Find zero or one DraftShipment that matches the filter.
   * @param {DraftShipmentFindUniqueArgs} args - Arguments to find a DraftShipment
   * @example
   * // Get one DraftShipment
   * const draftShipment = await prisma.draftShipment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DraftShipmentFindUniqueArgs>(args: Prisma.SelectSubset<T, DraftShipmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DraftShipmentClient<runtime.Types.Result.GetResult<Prisma.$DraftShipmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DraftShipment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DraftShipmentFindUniqueOrThrowArgs} args - Arguments to find a DraftShipment
   * @example
   * // Get one DraftShipment
   * const draftShipment = await prisma.draftShipment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DraftShipmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DraftShipmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DraftShipmentClient<runtime.Types.Result.GetResult<Prisma.$DraftShipmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DraftShipment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DraftShipmentFindFirstArgs} args - Arguments to find a DraftShipment
   * @example
   * // Get one DraftShipment
   * const draftShipment = await prisma.draftShipment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DraftShipmentFindFirstArgs>(args?: Prisma.SelectSubset<T, DraftShipmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__DraftShipmentClient<runtime.Types.Result.GetResult<Prisma.$DraftShipmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DraftShipment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DraftShipmentFindFirstOrThrowArgs} args - Arguments to find a DraftShipment
   * @example
   * // Get one DraftShipment
   * const draftShipment = await prisma.draftShipment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DraftShipmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DraftShipmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DraftShipmentClient<runtime.Types.Result.GetResult<Prisma.$DraftShipmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DraftShipments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DraftShipmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DraftShipments
   * const draftShipments = await prisma.draftShipment.findMany()
   * 
   * // Get first 10 DraftShipments
   * const draftShipments = await prisma.draftShipment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const draftShipmentWithIdOnly = await prisma.draftShipment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DraftShipmentFindManyArgs>(args?: Prisma.SelectSubset<T, DraftShipmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DraftShipmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DraftShipment.
   * @param {DraftShipmentCreateArgs} args - Arguments to create a DraftShipment.
   * @example
   * // Create one DraftShipment
   * const DraftShipment = await prisma.draftShipment.create({
   *   data: {
   *     // ... data to create a DraftShipment
   *   }
   * })
   * 
   */
  create<T extends DraftShipmentCreateArgs>(args: Prisma.SelectSubset<T, DraftShipmentCreateArgs<ExtArgs>>): Prisma.Prisma__DraftShipmentClient<runtime.Types.Result.GetResult<Prisma.$DraftShipmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DraftShipments.
   * @param {DraftShipmentCreateManyArgs} args - Arguments to create many DraftShipments.
   * @example
   * // Create many DraftShipments
   * const draftShipment = await prisma.draftShipment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DraftShipmentCreateManyArgs>(args?: Prisma.SelectSubset<T, DraftShipmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DraftShipments and returns the data saved in the database.
   * @param {DraftShipmentCreateManyAndReturnArgs} args - Arguments to create many DraftShipments.
   * @example
   * // Create many DraftShipments
   * const draftShipment = await prisma.draftShipment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DraftShipments and only return the `id`
   * const draftShipmentWithIdOnly = await prisma.draftShipment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DraftShipmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DraftShipmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DraftShipmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DraftShipment.
   * @param {DraftShipmentDeleteArgs} args - Arguments to delete one DraftShipment.
   * @example
   * // Delete one DraftShipment
   * const DraftShipment = await prisma.draftShipment.delete({
   *   where: {
   *     // ... filter to delete one DraftShipment
   *   }
   * })
   * 
   */
  delete<T extends DraftShipmentDeleteArgs>(args: Prisma.SelectSubset<T, DraftShipmentDeleteArgs<ExtArgs>>): Prisma.Prisma__DraftShipmentClient<runtime.Types.Result.GetResult<Prisma.$DraftShipmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DraftShipment.
   * @param {DraftShipmentUpdateArgs} args - Arguments to update one DraftShipment.
   * @example
   * // Update one DraftShipment
   * const draftShipment = await prisma.draftShipment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DraftShipmentUpdateArgs>(args: Prisma.SelectSubset<T, DraftShipmentUpdateArgs<ExtArgs>>): Prisma.Prisma__DraftShipmentClient<runtime.Types.Result.GetResult<Prisma.$DraftShipmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DraftShipments.
   * @param {DraftShipmentDeleteManyArgs} args - Arguments to filter DraftShipments to delete.
   * @example
   * // Delete a few DraftShipments
   * const { count } = await prisma.draftShipment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DraftShipmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, DraftShipmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DraftShipments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DraftShipmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DraftShipments
   * const draftShipment = await prisma.draftShipment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DraftShipmentUpdateManyArgs>(args: Prisma.SelectSubset<T, DraftShipmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DraftShipments and returns the data updated in the database.
   * @param {DraftShipmentUpdateManyAndReturnArgs} args - Arguments to update many DraftShipments.
   * @example
   * // Update many DraftShipments
   * const draftShipment = await prisma.draftShipment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DraftShipments and only return the `id`
   * const draftShipmentWithIdOnly = await prisma.draftShipment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DraftShipmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DraftShipmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DraftShipmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DraftShipment.
   * @param {DraftShipmentUpsertArgs} args - Arguments to update or create a DraftShipment.
   * @example
   * // Update or create a DraftShipment
   * const draftShipment = await prisma.draftShipment.upsert({
   *   create: {
   *     // ... data to create a DraftShipment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DraftShipment we want to update
   *   }
   * })
   */
  upsert<T extends DraftShipmentUpsertArgs>(args: Prisma.SelectSubset<T, DraftShipmentUpsertArgs<ExtArgs>>): Prisma.Prisma__DraftShipmentClient<runtime.Types.Result.GetResult<Prisma.$DraftShipmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DraftShipments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DraftShipmentCountArgs} args - Arguments to filter DraftShipments to count.
   * @example
   * // Count the number of DraftShipments
   * const count = await prisma.draftShipment.count({
   *   where: {
   *     // ... the filter for the DraftShipments we want to count
   *   }
   * })
  **/
  count<T extends DraftShipmentCountArgs>(
    args?: Prisma.Subset<T, DraftShipmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DraftShipmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DraftShipment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DraftShipmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DraftShipmentAggregateArgs>(args: Prisma.Subset<T, DraftShipmentAggregateArgs>): Prisma.PrismaPromise<GetDraftShipmentAggregateType<T>>

  /**
   * Group by DraftShipment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DraftShipmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DraftShipmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DraftShipmentGroupByArgs['orderBy'] }
      : { orderBy?: DraftShipmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DraftShipmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDraftShipmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DraftShipment model
 */
readonly fields: DraftShipmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DraftShipment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DraftShipmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DraftShipment model
 */
export interface DraftShipmentFieldRefs {
  readonly id: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly data: Prisma.FieldRef<"DraftShipment", 'Json'>
  readonly accountId: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly customerGroupId: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly dispatchDate: Prisma.FieldRef<"DraftShipment", 'DateTime'>
  readonly senderName: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly senderAddress: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly senderCountry: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly senderState: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly senderSuburb: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly senderPostcode: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly receiverName: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly receiverAddress: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly receiverState: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly receiverPostcode: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly receiverCountry: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly receiverSuburb: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly carrier: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly serviceName: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly estimatedPrice: Prisma.FieldRef<"DraftShipment", 'Decimal'>
  readonly shipmentReferenceId: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly status: Prisma.FieldRef<"DraftShipment", 'ShipmentStatus'>
  readonly tenantId: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly createdAt: Prisma.FieldRef<"DraftShipment", 'DateTime'>
  readonly eta: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly internalReference: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly consignmentReference: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly totalQuantity: Prisma.FieldRef<"DraftShipment", 'Int'>
  readonly totalWeight: Prisma.FieldRef<"DraftShipment", 'Decimal'>
  readonly totalVolume: Prisma.FieldRef<"DraftShipment", 'Decimal'>
  readonly thirdPartyAccountNumber: Prisma.FieldRef<"DraftShipment", 'String'>
  readonly deleted: Prisma.FieldRef<"DraftShipment", 'Boolean'>
}
    

// Custom InputTypes
/**
 * DraftShipment findUnique
 */
export type DraftShipmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftShipment
   */
  select?: Prisma.DraftShipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DraftShipment
   */
  omit?: Prisma.DraftShipmentOmit<ExtArgs> | null
  /**
   * Filter, which DraftShipment to fetch.
   */
  where: Prisma.DraftShipmentWhereUniqueInput
}

/**
 * DraftShipment findUniqueOrThrow
 */
export type DraftShipmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftShipment
   */
  select?: Prisma.DraftShipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DraftShipment
   */
  omit?: Prisma.DraftShipmentOmit<ExtArgs> | null
  /**
   * Filter, which DraftShipment to fetch.
   */
  where: Prisma.DraftShipmentWhereUniqueInput
}

/**
 * DraftShipment findFirst
 */
export type DraftShipmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftShipment
   */
  select?: Prisma.DraftShipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DraftShipment
   */
  omit?: Prisma.DraftShipmentOmit<ExtArgs> | null
  /**
   * Filter, which DraftShipment to fetch.
   */
  where?: Prisma.DraftShipmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DraftShipments to fetch.
   */
  orderBy?: Prisma.DraftShipmentOrderByWithRelationInput | Prisma.DraftShipmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DraftShipments.
   */
  cursor?: Prisma.DraftShipmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DraftShipments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DraftShipments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DraftShipments.
   */
  distinct?: Prisma.DraftShipmentScalarFieldEnum | Prisma.DraftShipmentScalarFieldEnum[]
}

/**
 * DraftShipment findFirstOrThrow
 */
export type DraftShipmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftShipment
   */
  select?: Prisma.DraftShipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DraftShipment
   */
  omit?: Prisma.DraftShipmentOmit<ExtArgs> | null
  /**
   * Filter, which DraftShipment to fetch.
   */
  where?: Prisma.DraftShipmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DraftShipments to fetch.
   */
  orderBy?: Prisma.DraftShipmentOrderByWithRelationInput | Prisma.DraftShipmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DraftShipments.
   */
  cursor?: Prisma.DraftShipmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DraftShipments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DraftShipments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DraftShipments.
   */
  distinct?: Prisma.DraftShipmentScalarFieldEnum | Prisma.DraftShipmentScalarFieldEnum[]
}

/**
 * DraftShipment findMany
 */
export type DraftShipmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftShipment
   */
  select?: Prisma.DraftShipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DraftShipment
   */
  omit?: Prisma.DraftShipmentOmit<ExtArgs> | null
  /**
   * Filter, which DraftShipments to fetch.
   */
  where?: Prisma.DraftShipmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DraftShipments to fetch.
   */
  orderBy?: Prisma.DraftShipmentOrderByWithRelationInput | Prisma.DraftShipmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DraftShipments.
   */
  cursor?: Prisma.DraftShipmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DraftShipments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DraftShipments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DraftShipments.
   */
  distinct?: Prisma.DraftShipmentScalarFieldEnum | Prisma.DraftShipmentScalarFieldEnum[]
}

/**
 * DraftShipment create
 */
export type DraftShipmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftShipment
   */
  select?: Prisma.DraftShipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DraftShipment
   */
  omit?: Prisma.DraftShipmentOmit<ExtArgs> | null
  /**
   * The data needed to create a DraftShipment.
   */
  data: Prisma.XOR<Prisma.DraftShipmentCreateInput, Prisma.DraftShipmentUncheckedCreateInput>
}

/**
 * DraftShipment createMany
 */
export type DraftShipmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DraftShipments.
   */
  data: Prisma.DraftShipmentCreateManyInput | Prisma.DraftShipmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DraftShipment createManyAndReturn
 */
export type DraftShipmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftShipment
   */
  select?: Prisma.DraftShipmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DraftShipment
   */
  omit?: Prisma.DraftShipmentOmit<ExtArgs> | null
  /**
   * The data used to create many DraftShipments.
   */
  data: Prisma.DraftShipmentCreateManyInput | Prisma.DraftShipmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DraftShipment update
 */
export type DraftShipmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftShipment
   */
  select?: Prisma.DraftShipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DraftShipment
   */
  omit?: Prisma.DraftShipmentOmit<ExtArgs> | null
  /**
   * The data needed to update a DraftShipment.
   */
  data: Prisma.XOR<Prisma.DraftShipmentUpdateInput, Prisma.DraftShipmentUncheckedUpdateInput>
  /**
   * Choose, which DraftShipment to update.
   */
  where: Prisma.DraftShipmentWhereUniqueInput
}

/**
 * DraftShipment updateMany
 */
export type DraftShipmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DraftShipments.
   */
  data: Prisma.XOR<Prisma.DraftShipmentUpdateManyMutationInput, Prisma.DraftShipmentUncheckedUpdateManyInput>
  /**
   * Filter which DraftShipments to update
   */
  where?: Prisma.DraftShipmentWhereInput
  /**
   * Limit how many DraftShipments to update.
   */
  limit?: number
}

/**
 * DraftShipment updateManyAndReturn
 */
export type DraftShipmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftShipment
   */
  select?: Prisma.DraftShipmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DraftShipment
   */
  omit?: Prisma.DraftShipmentOmit<ExtArgs> | null
  /**
   * The data used to update DraftShipments.
   */
  data: Prisma.XOR<Prisma.DraftShipmentUpdateManyMutationInput, Prisma.DraftShipmentUncheckedUpdateManyInput>
  /**
   * Filter which DraftShipments to update
   */
  where?: Prisma.DraftShipmentWhereInput
  /**
   * Limit how many DraftShipments to update.
   */
  limit?: number
}

/**
 * DraftShipment upsert
 */
export type DraftShipmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftShipment
   */
  select?: Prisma.DraftShipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DraftShipment
   */
  omit?: Prisma.DraftShipmentOmit<ExtArgs> | null
  /**
   * The filter to search for the DraftShipment to update in case it exists.
   */
  where: Prisma.DraftShipmentWhereUniqueInput
  /**
   * In case the DraftShipment found by the `where` argument doesn't exist, create a new DraftShipment with this data.
   */
  create: Prisma.XOR<Prisma.DraftShipmentCreateInput, Prisma.DraftShipmentUncheckedCreateInput>
  /**
   * In case the DraftShipment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DraftShipmentUpdateInput, Prisma.DraftShipmentUncheckedUpdateInput>
}

/**
 * DraftShipment delete
 */
export type DraftShipmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftShipment
   */
  select?: Prisma.DraftShipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DraftShipment
   */
  omit?: Prisma.DraftShipmentOmit<ExtArgs> | null
  /**
   * Filter which DraftShipment to delete.
   */
  where: Prisma.DraftShipmentWhereUniqueInput
}

/**
 * DraftShipment deleteMany
 */
export type DraftShipmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DraftShipments to delete
   */
  where?: Prisma.DraftShipmentWhereInput
  /**
   * Limit how many DraftShipments to delete.
   */
  limit?: number
}

/**
 * DraftShipment without action
 */
export type DraftShipmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftShipment
   */
  select?: Prisma.DraftShipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DraftShipment
   */
  omit?: Prisma.DraftShipmentOmit<ExtArgs> | null
}
