
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Receiver` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Receiver
 * 
 */
export type ReceiverModel = runtime.Types.Result.DefaultSelection<Prisma.$ReceiverPayload>

export type AggregateReceiver = {
  _count: ReceiverCountAggregateOutputType | null
  _min: ReceiverMinAggregateOutputType | null
  _max: ReceiverMaxAggregateOutputType | null
}

export type ReceiverMinAggregateOutputType = {
  id: string | null
  name: string | null
  locationId: string | null
  specialInstructions: string | null
  createdAt: Date | null
  tenantId: string | null
  code: string | null
  isResidential: boolean | null
  isRecipient: boolean | null
}

export type ReceiverMaxAggregateOutputType = {
  id: string | null
  name: string | null
  locationId: string | null
  specialInstructions: string | null
  createdAt: Date | null
  tenantId: string | null
  code: string | null
  isResidential: boolean | null
  isRecipient: boolean | null
}

export type ReceiverCountAggregateOutputType = {
  id: number
  name: number
  locationId: number
  specialInstructions: number
  createdAt: number
  tenantId: number
  code: number
  isResidential: number
  isRecipient: number
  _all: number
}


export type ReceiverMinAggregateInputType = {
  id?: true
  name?: true
  locationId?: true
  specialInstructions?: true
  createdAt?: true
  tenantId?: true
  code?: true
  isResidential?: true
  isRecipient?: true
}

export type ReceiverMaxAggregateInputType = {
  id?: true
  name?: true
  locationId?: true
  specialInstructions?: true
  createdAt?: true
  tenantId?: true
  code?: true
  isResidential?: true
  isRecipient?: true
}

export type ReceiverCountAggregateInputType = {
  id?: true
  name?: true
  locationId?: true
  specialInstructions?: true
  createdAt?: true
  tenantId?: true
  code?: true
  isResidential?: true
  isRecipient?: true
  _all?: true
}

export type ReceiverAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Receiver to aggregate.
   */
  where?: Prisma.ReceiverWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Receivers to fetch.
   */
  orderBy?: Prisma.ReceiverOrderByWithRelationInput | Prisma.ReceiverOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReceiverWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Receivers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Receivers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Receivers
  **/
  _count?: true | ReceiverCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReceiverMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReceiverMaxAggregateInputType
}

export type GetReceiverAggregateType<T extends ReceiverAggregateArgs> = {
      [P in keyof T & keyof AggregateReceiver]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReceiver[P]>
    : Prisma.GetScalarType<T[P], AggregateReceiver[P]>
}




export type ReceiverGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReceiverWhereInput
  orderBy?: Prisma.ReceiverOrderByWithAggregationInput | Prisma.ReceiverOrderByWithAggregationInput[]
  by: Prisma.ReceiverScalarFieldEnum[] | Prisma.ReceiverScalarFieldEnum
  having?: Prisma.ReceiverScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReceiverCountAggregateInputType | true
  _min?: ReceiverMinAggregateInputType
  _max?: ReceiverMaxAggregateInputType
}

export type ReceiverGroupByOutputType = {
  id: string
  name: string
  locationId: string
  specialInstructions: string | null
  createdAt: Date
  tenantId: string
  code: string | null
  isResidential: boolean
  isRecipient: boolean | null
  _count: ReceiverCountAggregateOutputType | null
  _min: ReceiverMinAggregateOutputType | null
  _max: ReceiverMaxAggregateOutputType | null
}

export type GetReceiverGroupByPayload<T extends ReceiverGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReceiverGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReceiverGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReceiverGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReceiverGroupByOutputType[P]>
      }
    >
  >



export type ReceiverWhereInput = {
  AND?: Prisma.ReceiverWhereInput | Prisma.ReceiverWhereInput[]
  OR?: Prisma.ReceiverWhereInput[]
  NOT?: Prisma.ReceiverWhereInput | Prisma.ReceiverWhereInput[]
  id?: Prisma.UuidFilter<"Receiver"> | string
  name?: Prisma.StringFilter<"Receiver"> | string
  locationId?: Prisma.UuidFilter<"Receiver"> | string
  specialInstructions?: Prisma.StringNullableFilter<"Receiver"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Receiver"> | Date | string
  tenantId?: Prisma.UuidFilter<"Receiver"> | string
  code?: Prisma.StringNullableFilter<"Receiver"> | string | null
  isResidential?: Prisma.BoolFilter<"Receiver"> | boolean
  isRecipient?: Prisma.BoolNullableFilter<"Receiver"> | boolean | null
  location?: Prisma.XOR<Prisma.LocationScalarRelationFilter, Prisma.LocationWhereInput>
  shipment?: Prisma.ShipmentListRelationFilter
  newShipment?: Prisma.NewShipmentListRelationFilter
}

export type ReceiverOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  locationId?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  code?: Prisma.SortOrderInput | Prisma.SortOrder
  isResidential?: Prisma.SortOrder
  isRecipient?: Prisma.SortOrderInput | Prisma.SortOrder
  location?: Prisma.LocationOrderByWithRelationInput
  shipment?: Prisma.ShipmentOrderByRelationAggregateInput
  newShipment?: Prisma.NewShipmentOrderByRelationAggregateInput
}

export type ReceiverWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  locationId?: string
  AND?: Prisma.ReceiverWhereInput | Prisma.ReceiverWhereInput[]
  OR?: Prisma.ReceiverWhereInput[]
  NOT?: Prisma.ReceiverWhereInput | Prisma.ReceiverWhereInput[]
  name?: Prisma.StringFilter<"Receiver"> | string
  specialInstructions?: Prisma.StringNullableFilter<"Receiver"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Receiver"> | Date | string
  tenantId?: Prisma.UuidFilter<"Receiver"> | string
  code?: Prisma.StringNullableFilter<"Receiver"> | string | null
  isResidential?: Prisma.BoolFilter<"Receiver"> | boolean
  isRecipient?: Prisma.BoolNullableFilter<"Receiver"> | boolean | null
  location?: Prisma.XOR<Prisma.LocationScalarRelationFilter, Prisma.LocationWhereInput>
  shipment?: Prisma.ShipmentListRelationFilter
  newShipment?: Prisma.NewShipmentListRelationFilter
}, "id" | "locationId">

export type ReceiverOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  locationId?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  code?: Prisma.SortOrderInput | Prisma.SortOrder
  isResidential?: Prisma.SortOrder
  isRecipient?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ReceiverCountOrderByAggregateInput
  _max?: Prisma.ReceiverMaxOrderByAggregateInput
  _min?: Prisma.ReceiverMinOrderByAggregateInput
}

export type ReceiverScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReceiverScalarWhereWithAggregatesInput | Prisma.ReceiverScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReceiverScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReceiverScalarWhereWithAggregatesInput | Prisma.ReceiverScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Receiver"> | string
  name?: Prisma.StringWithAggregatesFilter<"Receiver"> | string
  locationId?: Prisma.UuidWithAggregatesFilter<"Receiver"> | string
  specialInstructions?: Prisma.StringNullableWithAggregatesFilter<"Receiver"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Receiver"> | Date | string
  tenantId?: Prisma.UuidWithAggregatesFilter<"Receiver"> | string
  code?: Prisma.StringNullableWithAggregatesFilter<"Receiver"> | string | null
  isResidential?: Prisma.BoolWithAggregatesFilter<"Receiver"> | boolean
  isRecipient?: Prisma.BoolNullableWithAggregatesFilter<"Receiver"> | boolean | null
}

export type ReceiverCreateInput = {
  id?: string
  name?: string
  specialInstructions?: string | null
  createdAt?: Date | string
  tenantId?: string
  code?: string | null
  isResidential?: boolean
  isRecipient?: boolean | null
  location: Prisma.LocationCreateNestedOneWithoutReceiverInput
  shipment?: Prisma.ShipmentCreateNestedManyWithoutReceiverInput
  newShipment?: Prisma.NewShipmentCreateNestedManyWithoutReceiverInput
}

export type ReceiverUncheckedCreateInput = {
  id?: string
  name?: string
  locationId: string
  specialInstructions?: string | null
  createdAt?: Date | string
  tenantId?: string
  code?: string | null
  isResidential?: boolean
  isRecipient?: boolean | null
  shipment?: Prisma.ShipmentUncheckedCreateNestedManyWithoutReceiverInput
  newShipment?: Prisma.NewShipmentUncheckedCreateNestedManyWithoutReceiverInput
}

export type ReceiverUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isResidential?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isRecipient?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  location?: Prisma.LocationUpdateOneRequiredWithoutReceiverNestedInput
  shipment?: Prisma.ShipmentUpdateManyWithoutReceiverNestedInput
  newShipment?: Prisma.NewShipmentUpdateManyWithoutReceiverNestedInput
}

export type ReceiverUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  locationId?: Prisma.StringFieldUpdateOperationsInput | string
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isResidential?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isRecipient?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  shipment?: Prisma.ShipmentUncheckedUpdateManyWithoutReceiverNestedInput
  newShipment?: Prisma.NewShipmentUncheckedUpdateManyWithoutReceiverNestedInput
}

export type ReceiverCreateManyInput = {
  id?: string
  name?: string
  locationId: string
  specialInstructions?: string | null
  createdAt?: Date | string
  tenantId?: string
  code?: string | null
  isResidential?: boolean
  isRecipient?: boolean | null
}

export type ReceiverUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isResidential?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isRecipient?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type ReceiverUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  locationId?: Prisma.StringFieldUpdateOperationsInput | string
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isResidential?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isRecipient?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type ReceiverNullableScalarRelationFilter = {
  is?: Prisma.ReceiverWhereInput | null
  isNot?: Prisma.ReceiverWhereInput | null
}

export type ReceiverCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  locationId?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  isResidential?: Prisma.SortOrder
  isRecipient?: Prisma.SortOrder
}

export type ReceiverMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  locationId?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  isResidential?: Prisma.SortOrder
  isRecipient?: Prisma.SortOrder
}

export type ReceiverMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  locationId?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  isResidential?: Prisma.SortOrder
  isRecipient?: Prisma.SortOrder
}

export type ReceiverCreateNestedOneWithoutShipmentInput = {
  create?: Prisma.XOR<Prisma.ReceiverCreateWithoutShipmentInput, Prisma.ReceiverUncheckedCreateWithoutShipmentInput>
  connectOrCreate?: Prisma.ReceiverCreateOrConnectWithoutShipmentInput
  connect?: Prisma.ReceiverWhereUniqueInput
}

export type ReceiverUpdateOneWithoutShipmentNestedInput = {
  create?: Prisma.XOR<Prisma.ReceiverCreateWithoutShipmentInput, Prisma.ReceiverUncheckedCreateWithoutShipmentInput>
  connectOrCreate?: Prisma.ReceiverCreateOrConnectWithoutShipmentInput
  upsert?: Prisma.ReceiverUpsertWithoutShipmentInput
  disconnect?: Prisma.ReceiverWhereInput | boolean
  delete?: Prisma.ReceiverWhereInput | boolean
  connect?: Prisma.ReceiverWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ReceiverUpdateToOneWithWhereWithoutShipmentInput, Prisma.ReceiverUpdateWithoutShipmentInput>, Prisma.ReceiverUncheckedUpdateWithoutShipmentInput>
}

export type ReceiverCreateNestedOneWithoutLocationInput = {
  create?: Prisma.XOR<Prisma.ReceiverCreateWithoutLocationInput, Prisma.ReceiverUncheckedCreateWithoutLocationInput>
  connectOrCreate?: Prisma.ReceiverCreateOrConnectWithoutLocationInput
  connect?: Prisma.ReceiverWhereUniqueInput
}

export type ReceiverUncheckedCreateNestedOneWithoutLocationInput = {
  create?: Prisma.XOR<Prisma.ReceiverCreateWithoutLocationInput, Prisma.ReceiverUncheckedCreateWithoutLocationInput>
  connectOrCreate?: Prisma.ReceiverCreateOrConnectWithoutLocationInput
  connect?: Prisma.ReceiverWhereUniqueInput
}

export type ReceiverUpdateOneWithoutLocationNestedInput = {
  create?: Prisma.XOR<Prisma.ReceiverCreateWithoutLocationInput, Prisma.ReceiverUncheckedCreateWithoutLocationInput>
  connectOrCreate?: Prisma.ReceiverCreateOrConnectWithoutLocationInput
  upsert?: Prisma.ReceiverUpsertWithoutLocationInput
  disconnect?: Prisma.ReceiverWhereInput | boolean
  delete?: Prisma.ReceiverWhereInput | boolean
  connect?: Prisma.ReceiverWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ReceiverUpdateToOneWithWhereWithoutLocationInput, Prisma.ReceiverUpdateWithoutLocationInput>, Prisma.ReceiverUncheckedUpdateWithoutLocationInput>
}

export type ReceiverUncheckedUpdateOneWithoutLocationNestedInput = {
  create?: Prisma.XOR<Prisma.ReceiverCreateWithoutLocationInput, Prisma.ReceiverUncheckedCreateWithoutLocationInput>
  connectOrCreate?: Prisma.ReceiverCreateOrConnectWithoutLocationInput
  upsert?: Prisma.ReceiverUpsertWithoutLocationInput
  disconnect?: Prisma.ReceiverWhereInput | boolean
  delete?: Prisma.ReceiverWhereInput | boolean
  connect?: Prisma.ReceiverWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ReceiverUpdateToOneWithWhereWithoutLocationInput, Prisma.ReceiverUpdateWithoutLocationInput>, Prisma.ReceiverUncheckedUpdateWithoutLocationInput>
}

export type ReceiverCreateNestedOneWithoutNewShipmentInput = {
  create?: Prisma.XOR<Prisma.ReceiverCreateWithoutNewShipmentInput, Prisma.ReceiverUncheckedCreateWithoutNewShipmentInput>
  connectOrCreate?: Prisma.ReceiverCreateOrConnectWithoutNewShipmentInput
  connect?: Prisma.ReceiverWhereUniqueInput
}

export type ReceiverUpdateOneWithoutNewShipmentNestedInput = {
  create?: Prisma.XOR<Prisma.ReceiverCreateWithoutNewShipmentInput, Prisma.ReceiverUncheckedCreateWithoutNewShipmentInput>
  connectOrCreate?: Prisma.ReceiverCreateOrConnectWithoutNewShipmentInput
  upsert?: Prisma.ReceiverUpsertWithoutNewShipmentInput
  disconnect?: Prisma.ReceiverWhereInput | boolean
  delete?: Prisma.ReceiverWhereInput | boolean
  connect?: Prisma.ReceiverWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ReceiverUpdateToOneWithWhereWithoutNewShipmentInput, Prisma.ReceiverUpdateWithoutNewShipmentInput>, Prisma.ReceiverUncheckedUpdateWithoutNewShipmentInput>
}

export type ReceiverCreateWithoutShipmentInput = {
  id?: string
  name?: string
  specialInstructions?: string | null
  createdAt?: Date | string
  tenantId?: string
  code?: string | null
  isResidential?: boolean
  isRecipient?: boolean | null
  location: Prisma.LocationCreateNestedOneWithoutReceiverInput
  newShipment?: Prisma.NewShipmentCreateNestedManyWithoutReceiverInput
}

export type ReceiverUncheckedCreateWithoutShipmentInput = {
  id?: string
  name?: string
  locationId: string
  specialInstructions?: string | null
  createdAt?: Date | string
  tenantId?: string
  code?: string | null
  isResidential?: boolean
  isRecipient?: boolean | null
  newShipment?: Prisma.NewShipmentUncheckedCreateNestedManyWithoutReceiverInput
}

export type ReceiverCreateOrConnectWithoutShipmentInput = {
  where: Prisma.ReceiverWhereUniqueInput
  create: Prisma.XOR<Prisma.ReceiverCreateWithoutShipmentInput, Prisma.ReceiverUncheckedCreateWithoutShipmentInput>
}

export type ReceiverUpsertWithoutShipmentInput = {
  update: Prisma.XOR<Prisma.ReceiverUpdateWithoutShipmentInput, Prisma.ReceiverUncheckedUpdateWithoutShipmentInput>
  create: Prisma.XOR<Prisma.ReceiverCreateWithoutShipmentInput, Prisma.ReceiverUncheckedCreateWithoutShipmentInput>
  where?: Prisma.ReceiverWhereInput
}

export type ReceiverUpdateToOneWithWhereWithoutShipmentInput = {
  where?: Prisma.ReceiverWhereInput
  data: Prisma.XOR<Prisma.ReceiverUpdateWithoutShipmentInput, Prisma.ReceiverUncheckedUpdateWithoutShipmentInput>
}

export type ReceiverUpdateWithoutShipmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isResidential?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isRecipient?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  location?: Prisma.LocationUpdateOneRequiredWithoutReceiverNestedInput
  newShipment?: Prisma.NewShipmentUpdateManyWithoutReceiverNestedInput
}

export type ReceiverUncheckedUpdateWithoutShipmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  locationId?: Prisma.StringFieldUpdateOperationsInput | string
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isResidential?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isRecipient?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  newShipment?: Prisma.NewShipmentUncheckedUpdateManyWithoutReceiverNestedInput
}

export type ReceiverCreateWithoutLocationInput = {
  id?: string
  name?: string
  specialInstructions?: string | null
  createdAt?: Date | string
  tenantId?: string
  code?: string | null
  isResidential?: boolean
  isRecipient?: boolean | null
  shipment?: Prisma.ShipmentCreateNestedManyWithoutReceiverInput
  newShipment?: Prisma.NewShipmentCreateNestedManyWithoutReceiverInput
}

export type ReceiverUncheckedCreateWithoutLocationInput = {
  id?: string
  name?: string
  specialInstructions?: string | null
  createdAt?: Date | string
  tenantId?: string
  code?: string | null
  isResidential?: boolean
  isRecipient?: boolean | null
  shipment?: Prisma.ShipmentUncheckedCreateNestedManyWithoutReceiverInput
  newShipment?: Prisma.NewShipmentUncheckedCreateNestedManyWithoutReceiverInput
}

export type ReceiverCreateOrConnectWithoutLocationInput = {
  where: Prisma.ReceiverWhereUniqueInput
  create: Prisma.XOR<Prisma.ReceiverCreateWithoutLocationInput, Prisma.ReceiverUncheckedCreateWithoutLocationInput>
}

export type ReceiverUpsertWithoutLocationInput = {
  update: Prisma.XOR<Prisma.ReceiverUpdateWithoutLocationInput, Prisma.ReceiverUncheckedUpdateWithoutLocationInput>
  create: Prisma.XOR<Prisma.ReceiverCreateWithoutLocationInput, Prisma.ReceiverUncheckedCreateWithoutLocationInput>
  where?: Prisma.ReceiverWhereInput
}

export type ReceiverUpdateToOneWithWhereWithoutLocationInput = {
  where?: Prisma.ReceiverWhereInput
  data: Prisma.XOR<Prisma.ReceiverUpdateWithoutLocationInput, Prisma.ReceiverUncheckedUpdateWithoutLocationInput>
}

export type ReceiverUpdateWithoutLocationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isResidential?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isRecipient?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  shipment?: Prisma.ShipmentUpdateManyWithoutReceiverNestedInput
  newShipment?: Prisma.NewShipmentUpdateManyWithoutReceiverNestedInput
}

export type ReceiverUncheckedUpdateWithoutLocationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isResidential?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isRecipient?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  shipment?: Prisma.ShipmentUncheckedUpdateManyWithoutReceiverNestedInput
  newShipment?: Prisma.NewShipmentUncheckedUpdateManyWithoutReceiverNestedInput
}

export type ReceiverCreateWithoutNewShipmentInput = {
  id?: string
  name?: string
  specialInstructions?: string | null
  createdAt?: Date | string
  tenantId?: string
  code?: string | null
  isResidential?: boolean
  isRecipient?: boolean | null
  location: Prisma.LocationCreateNestedOneWithoutReceiverInput
  shipment?: Prisma.ShipmentCreateNestedManyWithoutReceiverInput
}

export type ReceiverUncheckedCreateWithoutNewShipmentInput = {
  id?: string
  name?: string
  locationId: string
  specialInstructions?: string | null
  createdAt?: Date | string
  tenantId?: string
  code?: string | null
  isResidential?: boolean
  isRecipient?: boolean | null
  shipment?: Prisma.ShipmentUncheckedCreateNestedManyWithoutReceiverInput
}

export type ReceiverCreateOrConnectWithoutNewShipmentInput = {
  where: Prisma.ReceiverWhereUniqueInput
  create: Prisma.XOR<Prisma.ReceiverCreateWithoutNewShipmentInput, Prisma.ReceiverUncheckedCreateWithoutNewShipmentInput>
}

export type ReceiverUpsertWithoutNewShipmentInput = {
  update: Prisma.XOR<Prisma.ReceiverUpdateWithoutNewShipmentInput, Prisma.ReceiverUncheckedUpdateWithoutNewShipmentInput>
  create: Prisma.XOR<Prisma.ReceiverCreateWithoutNewShipmentInput, Prisma.ReceiverUncheckedCreateWithoutNewShipmentInput>
  where?: Prisma.ReceiverWhereInput
}

export type ReceiverUpdateToOneWithWhereWithoutNewShipmentInput = {
  where?: Prisma.ReceiverWhereInput
  data: Prisma.XOR<Prisma.ReceiverUpdateWithoutNewShipmentInput, Prisma.ReceiverUncheckedUpdateWithoutNewShipmentInput>
}

export type ReceiverUpdateWithoutNewShipmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isResidential?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isRecipient?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  location?: Prisma.LocationUpdateOneRequiredWithoutReceiverNestedInput
  shipment?: Prisma.ShipmentUpdateManyWithoutReceiverNestedInput
}

export type ReceiverUncheckedUpdateWithoutNewShipmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  locationId?: Prisma.StringFieldUpdateOperationsInput | string
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isResidential?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isRecipient?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  shipment?: Prisma.ShipmentUncheckedUpdateManyWithoutReceiverNestedInput
}


/**
 * Count Type ReceiverCountOutputType
 */

export type ReceiverCountOutputType = {
  shipment: number
  newShipment: number
}

export type ReceiverCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  shipment?: boolean | ReceiverCountOutputTypeCountShipmentArgs
  newShipment?: boolean | ReceiverCountOutputTypeCountNewShipmentArgs
}

/**
 * ReceiverCountOutputType without action
 */
export type ReceiverCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReceiverCountOutputType
   */
  select?: Prisma.ReceiverCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ReceiverCountOutputType without action
 */
export type ReceiverCountOutputTypeCountShipmentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ShipmentWhereInput
}

/**
 * ReceiverCountOutputType without action
 */
export type ReceiverCountOutputTypeCountNewShipmentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NewShipmentWhereInput
}


export type ReceiverSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  locationId?: boolean
  specialInstructions?: boolean
  createdAt?: boolean
  tenantId?: boolean
  code?: boolean
  isResidential?: boolean
  isRecipient?: boolean
  location?: boolean | Prisma.LocationDefaultArgs<ExtArgs>
  shipment?: boolean | Prisma.Receiver$shipmentArgs<ExtArgs>
  newShipment?: boolean | Prisma.Receiver$newShipmentArgs<ExtArgs>
  _count?: boolean | Prisma.ReceiverCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["receiver"]>

export type ReceiverSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  locationId?: boolean
  specialInstructions?: boolean
  createdAt?: boolean
  tenantId?: boolean
  code?: boolean
  isResidential?: boolean
  isRecipient?: boolean
  location?: boolean | Prisma.LocationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["receiver"]>

export type ReceiverSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  locationId?: boolean
  specialInstructions?: boolean
  createdAt?: boolean
  tenantId?: boolean
  code?: boolean
  isResidential?: boolean
  isRecipient?: boolean
  location?: boolean | Prisma.LocationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["receiver"]>

export type ReceiverSelectScalar = {
  id?: boolean
  name?: boolean
  locationId?: boolean
  specialInstructions?: boolean
  createdAt?: boolean
  tenantId?: boolean
  code?: boolean
  isResidential?: boolean
  isRecipient?: boolean
}

export type ReceiverOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "locationId" | "specialInstructions" | "createdAt" | "tenantId" | "code" | "isResidential" | "isRecipient", ExtArgs["result"]["receiver"]>
export type ReceiverInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  location?: boolean | Prisma.LocationDefaultArgs<ExtArgs>
  shipment?: boolean | Prisma.Receiver$shipmentArgs<ExtArgs>
  newShipment?: boolean | Prisma.Receiver$newShipmentArgs<ExtArgs>
  _count?: boolean | Prisma.ReceiverCountOutputTypeDefaultArgs<ExtArgs>
}
export type ReceiverIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  location?: boolean | Prisma.LocationDefaultArgs<ExtArgs>
}
export type ReceiverIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  location?: boolean | Prisma.LocationDefaultArgs<ExtArgs>
}

export type $ReceiverPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Receiver"
  objects: {
    location: Prisma.$LocationPayload<ExtArgs>
    shipment: Prisma.$ShipmentPayload<ExtArgs>[]
    newShipment: Prisma.$NewShipmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    locationId: string
    specialInstructions: string | null
    createdAt: Date
    tenantId: string
    code: string | null
    isResidential: boolean
    isRecipient: boolean | null
  }, ExtArgs["result"]["receiver"]>
  composites: {}
}

export type ReceiverGetPayload<S extends boolean | null | undefined | ReceiverDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReceiverPayload, S>

export type ReceiverCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReceiverFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReceiverCountAggregateInputType | true
  }

export interface ReceiverDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Receiver'], meta: { name: 'Receiver' } }
  /**
   * Find zero or one Receiver that matches the filter.
   * @param {ReceiverFindUniqueArgs} args - Arguments to find a Receiver
   * @example
   * // Get one Receiver
   * const receiver = await prisma.receiver.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReceiverFindUniqueArgs>(args: Prisma.SelectSubset<T, ReceiverFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReceiverClient<runtime.Types.Result.GetResult<Prisma.$ReceiverPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Receiver that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReceiverFindUniqueOrThrowArgs} args - Arguments to find a Receiver
   * @example
   * // Get one Receiver
   * const receiver = await prisma.receiver.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReceiverFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReceiverFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReceiverClient<runtime.Types.Result.GetResult<Prisma.$ReceiverPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Receiver that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReceiverFindFirstArgs} args - Arguments to find a Receiver
   * @example
   * // Get one Receiver
   * const receiver = await prisma.receiver.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReceiverFindFirstArgs>(args?: Prisma.SelectSubset<T, ReceiverFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReceiverClient<runtime.Types.Result.GetResult<Prisma.$ReceiverPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Receiver that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReceiverFindFirstOrThrowArgs} args - Arguments to find a Receiver
   * @example
   * // Get one Receiver
   * const receiver = await prisma.receiver.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReceiverFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReceiverFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReceiverClient<runtime.Types.Result.GetResult<Prisma.$ReceiverPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Receivers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReceiverFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Receivers
   * const receivers = await prisma.receiver.findMany()
   * 
   * // Get first 10 Receivers
   * const receivers = await prisma.receiver.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const receiverWithIdOnly = await prisma.receiver.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReceiverFindManyArgs>(args?: Prisma.SelectSubset<T, ReceiverFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReceiverPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Receiver.
   * @param {ReceiverCreateArgs} args - Arguments to create a Receiver.
   * @example
   * // Create one Receiver
   * const Receiver = await prisma.receiver.create({
   *   data: {
   *     // ... data to create a Receiver
   *   }
   * })
   * 
   */
  create<T extends ReceiverCreateArgs>(args: Prisma.SelectSubset<T, ReceiverCreateArgs<ExtArgs>>): Prisma.Prisma__ReceiverClient<runtime.Types.Result.GetResult<Prisma.$ReceiverPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Receivers.
   * @param {ReceiverCreateManyArgs} args - Arguments to create many Receivers.
   * @example
   * // Create many Receivers
   * const receiver = await prisma.receiver.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReceiverCreateManyArgs>(args?: Prisma.SelectSubset<T, ReceiverCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Receivers and returns the data saved in the database.
   * @param {ReceiverCreateManyAndReturnArgs} args - Arguments to create many Receivers.
   * @example
   * // Create many Receivers
   * const receiver = await prisma.receiver.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Receivers and only return the `id`
   * const receiverWithIdOnly = await prisma.receiver.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ReceiverCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ReceiverCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReceiverPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Receiver.
   * @param {ReceiverDeleteArgs} args - Arguments to delete one Receiver.
   * @example
   * // Delete one Receiver
   * const Receiver = await prisma.receiver.delete({
   *   where: {
   *     // ... filter to delete one Receiver
   *   }
   * })
   * 
   */
  delete<T extends ReceiverDeleteArgs>(args: Prisma.SelectSubset<T, ReceiverDeleteArgs<ExtArgs>>): Prisma.Prisma__ReceiverClient<runtime.Types.Result.GetResult<Prisma.$ReceiverPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Receiver.
   * @param {ReceiverUpdateArgs} args - Arguments to update one Receiver.
   * @example
   * // Update one Receiver
   * const receiver = await prisma.receiver.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReceiverUpdateArgs>(args: Prisma.SelectSubset<T, ReceiverUpdateArgs<ExtArgs>>): Prisma.Prisma__ReceiverClient<runtime.Types.Result.GetResult<Prisma.$ReceiverPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Receivers.
   * @param {ReceiverDeleteManyArgs} args - Arguments to filter Receivers to delete.
   * @example
   * // Delete a few Receivers
   * const { count } = await prisma.receiver.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReceiverDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReceiverDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Receivers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReceiverUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Receivers
   * const receiver = await prisma.receiver.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReceiverUpdateManyArgs>(args: Prisma.SelectSubset<T, ReceiverUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Receivers and returns the data updated in the database.
   * @param {ReceiverUpdateManyAndReturnArgs} args - Arguments to update many Receivers.
   * @example
   * // Update many Receivers
   * const receiver = await prisma.receiver.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Receivers and only return the `id`
   * const receiverWithIdOnly = await prisma.receiver.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ReceiverUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ReceiverUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReceiverPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Receiver.
   * @param {ReceiverUpsertArgs} args - Arguments to update or create a Receiver.
   * @example
   * // Update or create a Receiver
   * const receiver = await prisma.receiver.upsert({
   *   create: {
   *     // ... data to create a Receiver
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Receiver we want to update
   *   }
   * })
   */
  upsert<T extends ReceiverUpsertArgs>(args: Prisma.SelectSubset<T, ReceiverUpsertArgs<ExtArgs>>): Prisma.Prisma__ReceiverClient<runtime.Types.Result.GetResult<Prisma.$ReceiverPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Receivers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReceiverCountArgs} args - Arguments to filter Receivers to count.
   * @example
   * // Count the number of Receivers
   * const count = await prisma.receiver.count({
   *   where: {
   *     // ... the filter for the Receivers we want to count
   *   }
   * })
  **/
  count<T extends ReceiverCountArgs>(
    args?: Prisma.Subset<T, ReceiverCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReceiverCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Receiver.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReceiverAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReceiverAggregateArgs>(args: Prisma.Subset<T, ReceiverAggregateArgs>): Prisma.PrismaPromise<GetReceiverAggregateType<T>>

  /**
   * Group by Receiver.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReceiverGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReceiverGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReceiverGroupByArgs['orderBy'] }
      : { orderBy?: ReceiverGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReceiverGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReceiverGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Receiver model
 */
readonly fields: ReceiverFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Receiver.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReceiverClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  location<T extends Prisma.LocationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LocationDefaultArgs<ExtArgs>>): Prisma.Prisma__LocationClient<runtime.Types.Result.GetResult<Prisma.$LocationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  shipment<T extends Prisma.Receiver$shipmentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Receiver$shipmentArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShipmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  newShipment<T extends Prisma.Receiver$newShipmentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Receiver$newShipmentArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewShipmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Receiver model
 */
export interface ReceiverFieldRefs {
  readonly id: Prisma.FieldRef<"Receiver", 'String'>
  readonly name: Prisma.FieldRef<"Receiver", 'String'>
  readonly locationId: Prisma.FieldRef<"Receiver", 'String'>
  readonly specialInstructions: Prisma.FieldRef<"Receiver", 'String'>
  readonly createdAt: Prisma.FieldRef<"Receiver", 'DateTime'>
  readonly tenantId: Prisma.FieldRef<"Receiver", 'String'>
  readonly code: Prisma.FieldRef<"Receiver", 'String'>
  readonly isResidential: Prisma.FieldRef<"Receiver", 'Boolean'>
  readonly isRecipient: Prisma.FieldRef<"Receiver", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Receiver findUnique
 */
export type ReceiverFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receiver
   */
  select?: Prisma.ReceiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Receiver
   */
  omit?: Prisma.ReceiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiverInclude<ExtArgs> | null
  /**
   * Filter, which Receiver to fetch.
   */
  where: Prisma.ReceiverWhereUniqueInput
}

/**
 * Receiver findUniqueOrThrow
 */
export type ReceiverFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receiver
   */
  select?: Prisma.ReceiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Receiver
   */
  omit?: Prisma.ReceiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiverInclude<ExtArgs> | null
  /**
   * Filter, which Receiver to fetch.
   */
  where: Prisma.ReceiverWhereUniqueInput
}

/**
 * Receiver findFirst
 */
export type ReceiverFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receiver
   */
  select?: Prisma.ReceiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Receiver
   */
  omit?: Prisma.ReceiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiverInclude<ExtArgs> | null
  /**
   * Filter, which Receiver to fetch.
   */
  where?: Prisma.ReceiverWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Receivers to fetch.
   */
  orderBy?: Prisma.ReceiverOrderByWithRelationInput | Prisma.ReceiverOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Receivers.
   */
  cursor?: Prisma.ReceiverWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Receivers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Receivers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Receivers.
   */
  distinct?: Prisma.ReceiverScalarFieldEnum | Prisma.ReceiverScalarFieldEnum[]
}

/**
 * Receiver findFirstOrThrow
 */
export type ReceiverFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receiver
   */
  select?: Prisma.ReceiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Receiver
   */
  omit?: Prisma.ReceiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiverInclude<ExtArgs> | null
  /**
   * Filter, which Receiver to fetch.
   */
  where?: Prisma.ReceiverWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Receivers to fetch.
   */
  orderBy?: Prisma.ReceiverOrderByWithRelationInput | Prisma.ReceiverOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Receivers.
   */
  cursor?: Prisma.ReceiverWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Receivers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Receivers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Receivers.
   */
  distinct?: Prisma.ReceiverScalarFieldEnum | Prisma.ReceiverScalarFieldEnum[]
}

/**
 * Receiver findMany
 */
export type ReceiverFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receiver
   */
  select?: Prisma.ReceiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Receiver
   */
  omit?: Prisma.ReceiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiverInclude<ExtArgs> | null
  /**
   * Filter, which Receivers to fetch.
   */
  where?: Prisma.ReceiverWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Receivers to fetch.
   */
  orderBy?: Prisma.ReceiverOrderByWithRelationInput | Prisma.ReceiverOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Receivers.
   */
  cursor?: Prisma.ReceiverWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Receivers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Receivers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Receivers.
   */
  distinct?: Prisma.ReceiverScalarFieldEnum | Prisma.ReceiverScalarFieldEnum[]
}

/**
 * Receiver create
 */
export type ReceiverCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receiver
   */
  select?: Prisma.ReceiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Receiver
   */
  omit?: Prisma.ReceiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiverInclude<ExtArgs> | null
  /**
   * The data needed to create a Receiver.
   */
  data: Prisma.XOR<Prisma.ReceiverCreateInput, Prisma.ReceiverUncheckedCreateInput>
}

/**
 * Receiver createMany
 */
export type ReceiverCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Receivers.
   */
  data: Prisma.ReceiverCreateManyInput | Prisma.ReceiverCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Receiver createManyAndReturn
 */
export type ReceiverCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receiver
   */
  select?: Prisma.ReceiverSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Receiver
   */
  omit?: Prisma.ReceiverOmit<ExtArgs> | null
  /**
   * The data used to create many Receivers.
   */
  data: Prisma.ReceiverCreateManyInput | Prisma.ReceiverCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiverIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Receiver update
 */
export type ReceiverUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receiver
   */
  select?: Prisma.ReceiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Receiver
   */
  omit?: Prisma.ReceiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiverInclude<ExtArgs> | null
  /**
   * The data needed to update a Receiver.
   */
  data: Prisma.XOR<Prisma.ReceiverUpdateInput, Prisma.ReceiverUncheckedUpdateInput>
  /**
   * Choose, which Receiver to update.
   */
  where: Prisma.ReceiverWhereUniqueInput
}

/**
 * Receiver updateMany
 */
export type ReceiverUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Receivers.
   */
  data: Prisma.XOR<Prisma.ReceiverUpdateManyMutationInput, Prisma.ReceiverUncheckedUpdateManyInput>
  /**
   * Filter which Receivers to update
   */
  where?: Prisma.ReceiverWhereInput
  /**
   * Limit how many Receivers to update.
   */
  limit?: number
}

/**
 * Receiver updateManyAndReturn
 */
export type ReceiverUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receiver
   */
  select?: Prisma.ReceiverSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Receiver
   */
  omit?: Prisma.ReceiverOmit<ExtArgs> | null
  /**
   * The data used to update Receivers.
   */
  data: Prisma.XOR<Prisma.ReceiverUpdateManyMutationInput, Prisma.ReceiverUncheckedUpdateManyInput>
  /**
   * Filter which Receivers to update
   */
  where?: Prisma.ReceiverWhereInput
  /**
   * Limit how many Receivers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiverIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Receiver upsert
 */
export type ReceiverUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receiver
   */
  select?: Prisma.ReceiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Receiver
   */
  omit?: Prisma.ReceiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiverInclude<ExtArgs> | null
  /**
   * The filter to search for the Receiver to update in case it exists.
   */
  where: Prisma.ReceiverWhereUniqueInput
  /**
   * In case the Receiver found by the `where` argument doesn't exist, create a new Receiver with this data.
   */
  create: Prisma.XOR<Prisma.ReceiverCreateInput, Prisma.ReceiverUncheckedCreateInput>
  /**
   * In case the Receiver was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReceiverUpdateInput, Prisma.ReceiverUncheckedUpdateInput>
}

/**
 * Receiver delete
 */
export type ReceiverDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receiver
   */
  select?: Prisma.ReceiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Receiver
   */
  omit?: Prisma.ReceiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiverInclude<ExtArgs> | null
  /**
   * Filter which Receiver to delete.
   */
  where: Prisma.ReceiverWhereUniqueInput
}

/**
 * Receiver deleteMany
 */
export type ReceiverDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Receivers to delete
   */
  where?: Prisma.ReceiverWhereInput
  /**
   * Limit how many Receivers to delete.
   */
  limit?: number
}

/**
 * Receiver.shipment
 */
export type Receiver$shipmentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Shipment
   */
  select?: Prisma.ShipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Shipment
   */
  omit?: Prisma.ShipmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShipmentInclude<ExtArgs> | null
  where?: Prisma.ShipmentWhereInput
  orderBy?: Prisma.ShipmentOrderByWithRelationInput | Prisma.ShipmentOrderByWithRelationInput[]
  cursor?: Prisma.ShipmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ShipmentScalarFieldEnum | Prisma.ShipmentScalarFieldEnum[]
}

/**
 * Receiver.newShipment
 */
export type Receiver$newShipmentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewShipment
   */
  select?: Prisma.NewShipmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewShipment
   */
  omit?: Prisma.NewShipmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewShipmentInclude<ExtArgs> | null
  where?: Prisma.NewShipmentWhereInput
  orderBy?: Prisma.NewShipmentOrderByWithRelationInput | Prisma.NewShipmentOrderByWithRelationInput[]
  cursor?: Prisma.NewShipmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NewShipmentScalarFieldEnum | Prisma.NewShipmentScalarFieldEnum[]
}

/**
 * Receiver without action
 */
export type ReceiverDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receiver
   */
  select?: Prisma.ReceiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Receiver
   */
  omit?: Prisma.ReceiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiverInclude<ExtArgs> | null
}
