
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ZoneETACard` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ZoneETACard
 * 
 */
export type ZoneETACardModel = runtime.Types.Result.DefaultSelection<Prisma.$ZoneETACardPayload>

export type AggregateZoneETACard = {
  _count: ZoneETACardCountAggregateOutputType | null
  _min: ZoneETACardMinAggregateOutputType | null
  _max: ZoneETACardMaxAggregateOutputType | null
}

export type ZoneETACardMinAggregateOutputType = {
  id: string | null
  displayName: string | null
  start: Date | null
  end: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  masterCarrierId: string | null
  masterCarrierServiceId: string | null
}

export type ZoneETACardMaxAggregateOutputType = {
  id: string | null
  displayName: string | null
  start: Date | null
  end: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  masterCarrierId: string | null
  masterCarrierServiceId: string | null
}

export type ZoneETACardCountAggregateOutputType = {
  id: number
  displayName: number
  start: number
  end: number
  createdAt: number
  updatedAt: number
  masterCarrierId: number
  masterCarrierServiceId: number
  _all: number
}


export type ZoneETACardMinAggregateInputType = {
  id?: true
  displayName?: true
  start?: true
  end?: true
  createdAt?: true
  updatedAt?: true
  masterCarrierId?: true
  masterCarrierServiceId?: true
}

export type ZoneETACardMaxAggregateInputType = {
  id?: true
  displayName?: true
  start?: true
  end?: true
  createdAt?: true
  updatedAt?: true
  masterCarrierId?: true
  masterCarrierServiceId?: true
}

export type ZoneETACardCountAggregateInputType = {
  id?: true
  displayName?: true
  start?: true
  end?: true
  createdAt?: true
  updatedAt?: true
  masterCarrierId?: true
  masterCarrierServiceId?: true
  _all?: true
}

export type ZoneETACardAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ZoneETACard to aggregate.
   */
  where?: Prisma.ZoneETACardWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ZoneETACards to fetch.
   */
  orderBy?: Prisma.ZoneETACardOrderByWithRelationInput | Prisma.ZoneETACardOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ZoneETACardWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ZoneETACards from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ZoneETACards.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ZoneETACards
  **/
  _count?: true | ZoneETACardCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ZoneETACardMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ZoneETACardMaxAggregateInputType
}

export type GetZoneETACardAggregateType<T extends ZoneETACardAggregateArgs> = {
      [P in keyof T & keyof AggregateZoneETACard]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateZoneETACard[P]>
    : Prisma.GetScalarType<T[P], AggregateZoneETACard[P]>
}




export type ZoneETACardGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ZoneETACardWhereInput
  orderBy?: Prisma.ZoneETACardOrderByWithAggregationInput | Prisma.ZoneETACardOrderByWithAggregationInput[]
  by: Prisma.ZoneETACardScalarFieldEnum[] | Prisma.ZoneETACardScalarFieldEnum
  having?: Prisma.ZoneETACardScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ZoneETACardCountAggregateInputType | true
  _min?: ZoneETACardMinAggregateInputType
  _max?: ZoneETACardMaxAggregateInputType
}

export type ZoneETACardGroupByOutputType = {
  id: string
  displayName: string
  start: Date
  end: Date | null
  createdAt: Date
  updatedAt: Date
  masterCarrierId: string
  masterCarrierServiceId: string | null
  _count: ZoneETACardCountAggregateOutputType | null
  _min: ZoneETACardMinAggregateOutputType | null
  _max: ZoneETACardMaxAggregateOutputType | null
}

export type GetZoneETACardGroupByPayload<T extends ZoneETACardGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ZoneETACardGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ZoneETACardGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ZoneETACardGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ZoneETACardGroupByOutputType[P]>
      }
    >
  >



export type ZoneETACardWhereInput = {
  AND?: Prisma.ZoneETACardWhereInput | Prisma.ZoneETACardWhereInput[]
  OR?: Prisma.ZoneETACardWhereInput[]
  NOT?: Prisma.ZoneETACardWhereInput | Prisma.ZoneETACardWhereInput[]
  id?: Prisma.UuidFilter<"ZoneETACard"> | string
  displayName?: Prisma.StringFilter<"ZoneETACard"> | string
  start?: Prisma.DateTimeFilter<"ZoneETACard"> | Date | string
  end?: Prisma.DateTimeNullableFilter<"ZoneETACard"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ZoneETACard"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ZoneETACard"> | Date | string
  masterCarrierId?: Prisma.UuidFilter<"ZoneETACard"> | string
  masterCarrierServiceId?: Prisma.UuidNullableFilter<"ZoneETACard"> | string | null
  zoneETAs?: Prisma.ZoneETAListRelationFilter
  masterCarrier?: Prisma.XOR<Prisma.MasterCarrierScalarRelationFilter, Prisma.MasterCarrierWhereInput>
}

export type ZoneETACardOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  masterCarrierId?: Prisma.SortOrder
  masterCarrierServiceId?: Prisma.SortOrderInput | Prisma.SortOrder
  zoneETAs?: Prisma.ZoneETAOrderByRelationAggregateInput
  masterCarrier?: Prisma.MasterCarrierOrderByWithRelationInput
}

export type ZoneETACardWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ZoneETACardWhereInput | Prisma.ZoneETACardWhereInput[]
  OR?: Prisma.ZoneETACardWhereInput[]
  NOT?: Prisma.ZoneETACardWhereInput | Prisma.ZoneETACardWhereInput[]
  displayName?: Prisma.StringFilter<"ZoneETACard"> | string
  start?: Prisma.DateTimeFilter<"ZoneETACard"> | Date | string
  end?: Prisma.DateTimeNullableFilter<"ZoneETACard"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ZoneETACard"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ZoneETACard"> | Date | string
  masterCarrierId?: Prisma.UuidFilter<"ZoneETACard"> | string
  masterCarrierServiceId?: Prisma.UuidNullableFilter<"ZoneETACard"> | string | null
  zoneETAs?: Prisma.ZoneETAListRelationFilter
  masterCarrier?: Prisma.XOR<Prisma.MasterCarrierScalarRelationFilter, Prisma.MasterCarrierWhereInput>
}, "id">

export type ZoneETACardOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  masterCarrierId?: Prisma.SortOrder
  masterCarrierServiceId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ZoneETACardCountOrderByAggregateInput
  _max?: Prisma.ZoneETACardMaxOrderByAggregateInput
  _min?: Prisma.ZoneETACardMinOrderByAggregateInput
}

export type ZoneETACardScalarWhereWithAggregatesInput = {
  AND?: Prisma.ZoneETACardScalarWhereWithAggregatesInput | Prisma.ZoneETACardScalarWhereWithAggregatesInput[]
  OR?: Prisma.ZoneETACardScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ZoneETACardScalarWhereWithAggregatesInput | Prisma.ZoneETACardScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"ZoneETACard"> | string
  displayName?: Prisma.StringWithAggregatesFilter<"ZoneETACard"> | string
  start?: Prisma.DateTimeWithAggregatesFilter<"ZoneETACard"> | Date | string
  end?: Prisma.DateTimeNullableWithAggregatesFilter<"ZoneETACard"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ZoneETACard"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ZoneETACard"> | Date | string
  masterCarrierId?: Prisma.UuidWithAggregatesFilter<"ZoneETACard"> | string
  masterCarrierServiceId?: Prisma.UuidNullableWithAggregatesFilter<"ZoneETACard"> | string | null
}

export type ZoneETACardCreateInput = {
  id?: string
  displayName: string
  start: Date | string
  end?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  masterCarrierServiceId?: string | null
  zoneETAs?: Prisma.ZoneETACreateNestedManyWithoutZoneETACardInput
  masterCarrier: Prisma.MasterCarrierCreateNestedOneWithoutZoneETACardsInput
}

export type ZoneETACardUncheckedCreateInput = {
  id?: string
  displayName: string
  start: Date | string
  end?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  masterCarrierId: string
  masterCarrierServiceId?: string | null
  zoneETAs?: Prisma.ZoneETAUncheckedCreateNestedManyWithoutZoneETACardInput
}

export type ZoneETACardUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  masterCarrierServiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zoneETAs?: Prisma.ZoneETAUpdateManyWithoutZoneETACardNestedInput
  masterCarrier?: Prisma.MasterCarrierUpdateOneRequiredWithoutZoneETACardsNestedInput
}

export type ZoneETACardUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  masterCarrierId?: Prisma.StringFieldUpdateOperationsInput | string
  masterCarrierServiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zoneETAs?: Prisma.ZoneETAUncheckedUpdateManyWithoutZoneETACardNestedInput
}

export type ZoneETACardCreateManyInput = {
  id?: string
  displayName: string
  start: Date | string
  end?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  masterCarrierId: string
  masterCarrierServiceId?: string | null
}

export type ZoneETACardUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  masterCarrierServiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ZoneETACardUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  masterCarrierId?: Prisma.StringFieldUpdateOperationsInput | string
  masterCarrierServiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ZoneETACardListRelationFilter = {
  every?: Prisma.ZoneETACardWhereInput
  some?: Prisma.ZoneETACardWhereInput
  none?: Prisma.ZoneETACardWhereInput
}

export type ZoneETACardOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ZoneETACardCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  masterCarrierId?: Prisma.SortOrder
  masterCarrierServiceId?: Prisma.SortOrder
}

export type ZoneETACardMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  masterCarrierId?: Prisma.SortOrder
  masterCarrierServiceId?: Prisma.SortOrder
}

export type ZoneETACardMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  masterCarrierId?: Prisma.SortOrder
  masterCarrierServiceId?: Prisma.SortOrder
}

export type ZoneETACardScalarRelationFilter = {
  is?: Prisma.ZoneETACardWhereInput
  isNot?: Prisma.ZoneETACardWhereInput
}

export type ZoneETACardCreateNestedManyWithoutMasterCarrierInput = {
  create?: Prisma.XOR<Prisma.ZoneETACardCreateWithoutMasterCarrierInput, Prisma.ZoneETACardUncheckedCreateWithoutMasterCarrierInput> | Prisma.ZoneETACardCreateWithoutMasterCarrierInput[] | Prisma.ZoneETACardUncheckedCreateWithoutMasterCarrierInput[]
  connectOrCreate?: Prisma.ZoneETACardCreateOrConnectWithoutMasterCarrierInput | Prisma.ZoneETACardCreateOrConnectWithoutMasterCarrierInput[]
  createMany?: Prisma.ZoneETACardCreateManyMasterCarrierInputEnvelope
  connect?: Prisma.ZoneETACardWhereUniqueInput | Prisma.ZoneETACardWhereUniqueInput[]
}

export type ZoneETACardUncheckedCreateNestedManyWithoutMasterCarrierInput = {
  create?: Prisma.XOR<Prisma.ZoneETACardCreateWithoutMasterCarrierInput, Prisma.ZoneETACardUncheckedCreateWithoutMasterCarrierInput> | Prisma.ZoneETACardCreateWithoutMasterCarrierInput[] | Prisma.ZoneETACardUncheckedCreateWithoutMasterCarrierInput[]
  connectOrCreate?: Prisma.ZoneETACardCreateOrConnectWithoutMasterCarrierInput | Prisma.ZoneETACardCreateOrConnectWithoutMasterCarrierInput[]
  createMany?: Prisma.ZoneETACardCreateManyMasterCarrierInputEnvelope
  connect?: Prisma.ZoneETACardWhereUniqueInput | Prisma.ZoneETACardWhereUniqueInput[]
}

export type ZoneETACardUpdateManyWithoutMasterCarrierNestedInput = {
  create?: Prisma.XOR<Prisma.ZoneETACardCreateWithoutMasterCarrierInput, Prisma.ZoneETACardUncheckedCreateWithoutMasterCarrierInput> | Prisma.ZoneETACardCreateWithoutMasterCarrierInput[] | Prisma.ZoneETACardUncheckedCreateWithoutMasterCarrierInput[]
  connectOrCreate?: Prisma.ZoneETACardCreateOrConnectWithoutMasterCarrierInput | Prisma.ZoneETACardCreateOrConnectWithoutMasterCarrierInput[]
  upsert?: Prisma.ZoneETACardUpsertWithWhereUniqueWithoutMasterCarrierInput | Prisma.ZoneETACardUpsertWithWhereUniqueWithoutMasterCarrierInput[]
  createMany?: Prisma.ZoneETACardCreateManyMasterCarrierInputEnvelope
  set?: Prisma.ZoneETACardWhereUniqueInput | Prisma.ZoneETACardWhereUniqueInput[]
  disconnect?: Prisma.ZoneETACardWhereUniqueInput | Prisma.ZoneETACardWhereUniqueInput[]
  delete?: Prisma.ZoneETACardWhereUniqueInput | Prisma.ZoneETACardWhereUniqueInput[]
  connect?: Prisma.ZoneETACardWhereUniqueInput | Prisma.ZoneETACardWhereUniqueInput[]
  update?: Prisma.ZoneETACardUpdateWithWhereUniqueWithoutMasterCarrierInput | Prisma.ZoneETACardUpdateWithWhereUniqueWithoutMasterCarrierInput[]
  updateMany?: Prisma.ZoneETACardUpdateManyWithWhereWithoutMasterCarrierInput | Prisma.ZoneETACardUpdateManyWithWhereWithoutMasterCarrierInput[]
  deleteMany?: Prisma.ZoneETACardScalarWhereInput | Prisma.ZoneETACardScalarWhereInput[]
}

export type ZoneETACardUncheckedUpdateManyWithoutMasterCarrierNestedInput = {
  create?: Prisma.XOR<Prisma.ZoneETACardCreateWithoutMasterCarrierInput, Prisma.ZoneETACardUncheckedCreateWithoutMasterCarrierInput> | Prisma.ZoneETACardCreateWithoutMasterCarrierInput[] | Prisma.ZoneETACardUncheckedCreateWithoutMasterCarrierInput[]
  connectOrCreate?: Prisma.ZoneETACardCreateOrConnectWithoutMasterCarrierInput | Prisma.ZoneETACardCreateOrConnectWithoutMasterCarrierInput[]
  upsert?: Prisma.ZoneETACardUpsertWithWhereUniqueWithoutMasterCarrierInput | Prisma.ZoneETACardUpsertWithWhereUniqueWithoutMasterCarrierInput[]
  createMany?: Prisma.ZoneETACardCreateManyMasterCarrierInputEnvelope
  set?: Prisma.ZoneETACardWhereUniqueInput | Prisma.ZoneETACardWhereUniqueInput[]
  disconnect?: Prisma.ZoneETACardWhereUniqueInput | Prisma.ZoneETACardWhereUniqueInput[]
  delete?: Prisma.ZoneETACardWhereUniqueInput | Prisma.ZoneETACardWhereUniqueInput[]
  connect?: Prisma.ZoneETACardWhereUniqueInput | Prisma.ZoneETACardWhereUniqueInput[]
  update?: Prisma.ZoneETACardUpdateWithWhereUniqueWithoutMasterCarrierInput | Prisma.ZoneETACardUpdateWithWhereUniqueWithoutMasterCarrierInput[]
  updateMany?: Prisma.ZoneETACardUpdateManyWithWhereWithoutMasterCarrierInput | Prisma.ZoneETACardUpdateManyWithWhereWithoutMasterCarrierInput[]
  deleteMany?: Prisma.ZoneETACardScalarWhereInput | Prisma.ZoneETACardScalarWhereInput[]
}

export type ZoneETACardCreateNestedOneWithoutZoneETAsInput = {
  create?: Prisma.XOR<Prisma.ZoneETACardCreateWithoutZoneETAsInput, Prisma.ZoneETACardUncheckedCreateWithoutZoneETAsInput>
  connectOrCreate?: Prisma.ZoneETACardCreateOrConnectWithoutZoneETAsInput
  connect?: Prisma.ZoneETACardWhereUniqueInput
}

export type ZoneETACardUpdateOneRequiredWithoutZoneETAsNestedInput = {
  create?: Prisma.XOR<Prisma.ZoneETACardCreateWithoutZoneETAsInput, Prisma.ZoneETACardUncheckedCreateWithoutZoneETAsInput>
  connectOrCreate?: Prisma.ZoneETACardCreateOrConnectWithoutZoneETAsInput
  upsert?: Prisma.ZoneETACardUpsertWithoutZoneETAsInput
  connect?: Prisma.ZoneETACardWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ZoneETACardUpdateToOneWithWhereWithoutZoneETAsInput, Prisma.ZoneETACardUpdateWithoutZoneETAsInput>, Prisma.ZoneETACardUncheckedUpdateWithoutZoneETAsInput>
}

export type ZoneETACardCreateWithoutMasterCarrierInput = {
  id?: string
  displayName: string
  start: Date | string
  end?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  masterCarrierServiceId?: string | null
  zoneETAs?: Prisma.ZoneETACreateNestedManyWithoutZoneETACardInput
}

export type ZoneETACardUncheckedCreateWithoutMasterCarrierInput = {
  id?: string
  displayName: string
  start: Date | string
  end?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  masterCarrierServiceId?: string | null
  zoneETAs?: Prisma.ZoneETAUncheckedCreateNestedManyWithoutZoneETACardInput
}

export type ZoneETACardCreateOrConnectWithoutMasterCarrierInput = {
  where: Prisma.ZoneETACardWhereUniqueInput
  create: Prisma.XOR<Prisma.ZoneETACardCreateWithoutMasterCarrierInput, Prisma.ZoneETACardUncheckedCreateWithoutMasterCarrierInput>
}

export type ZoneETACardCreateManyMasterCarrierInputEnvelope = {
  data: Prisma.ZoneETACardCreateManyMasterCarrierInput | Prisma.ZoneETACardCreateManyMasterCarrierInput[]
  skipDuplicates?: boolean
}

export type ZoneETACardUpsertWithWhereUniqueWithoutMasterCarrierInput = {
  where: Prisma.ZoneETACardWhereUniqueInput
  update: Prisma.XOR<Prisma.ZoneETACardUpdateWithoutMasterCarrierInput, Prisma.ZoneETACardUncheckedUpdateWithoutMasterCarrierInput>
  create: Prisma.XOR<Prisma.ZoneETACardCreateWithoutMasterCarrierInput, Prisma.ZoneETACardUncheckedCreateWithoutMasterCarrierInput>
}

export type ZoneETACardUpdateWithWhereUniqueWithoutMasterCarrierInput = {
  where: Prisma.ZoneETACardWhereUniqueInput
  data: Prisma.XOR<Prisma.ZoneETACardUpdateWithoutMasterCarrierInput, Prisma.ZoneETACardUncheckedUpdateWithoutMasterCarrierInput>
}

export type ZoneETACardUpdateManyWithWhereWithoutMasterCarrierInput = {
  where: Prisma.ZoneETACardScalarWhereInput
  data: Prisma.XOR<Prisma.ZoneETACardUpdateManyMutationInput, Prisma.ZoneETACardUncheckedUpdateManyWithoutMasterCarrierInput>
}

export type ZoneETACardScalarWhereInput = {
  AND?: Prisma.ZoneETACardScalarWhereInput | Prisma.ZoneETACardScalarWhereInput[]
  OR?: Prisma.ZoneETACardScalarWhereInput[]
  NOT?: Prisma.ZoneETACardScalarWhereInput | Prisma.ZoneETACardScalarWhereInput[]
  id?: Prisma.UuidFilter<"ZoneETACard"> | string
  displayName?: Prisma.StringFilter<"ZoneETACard"> | string
  start?: Prisma.DateTimeFilter<"ZoneETACard"> | Date | string
  end?: Prisma.DateTimeNullableFilter<"ZoneETACard"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ZoneETACard"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ZoneETACard"> | Date | string
  masterCarrierId?: Prisma.UuidFilter<"ZoneETACard"> | string
  masterCarrierServiceId?: Prisma.UuidNullableFilter<"ZoneETACard"> | string | null
}

export type ZoneETACardCreateWithoutZoneETAsInput = {
  id?: string
  displayName: string
  start: Date | string
  end?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  masterCarrierServiceId?: string | null
  masterCarrier: Prisma.MasterCarrierCreateNestedOneWithoutZoneETACardsInput
}

export type ZoneETACardUncheckedCreateWithoutZoneETAsInput = {
  id?: string
  displayName: string
  start: Date | string
  end?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  masterCarrierId: string
  masterCarrierServiceId?: string | null
}

export type ZoneETACardCreateOrConnectWithoutZoneETAsInput = {
  where: Prisma.ZoneETACardWhereUniqueInput
  create: Prisma.XOR<Prisma.ZoneETACardCreateWithoutZoneETAsInput, Prisma.ZoneETACardUncheckedCreateWithoutZoneETAsInput>
}

export type ZoneETACardUpsertWithoutZoneETAsInput = {
  update: Prisma.XOR<Prisma.ZoneETACardUpdateWithoutZoneETAsInput, Prisma.ZoneETACardUncheckedUpdateWithoutZoneETAsInput>
  create: Prisma.XOR<Prisma.ZoneETACardCreateWithoutZoneETAsInput, Prisma.ZoneETACardUncheckedCreateWithoutZoneETAsInput>
  where?: Prisma.ZoneETACardWhereInput
}

export type ZoneETACardUpdateToOneWithWhereWithoutZoneETAsInput = {
  where?: Prisma.ZoneETACardWhereInput
  data: Prisma.XOR<Prisma.ZoneETACardUpdateWithoutZoneETAsInput, Prisma.ZoneETACardUncheckedUpdateWithoutZoneETAsInput>
}

export type ZoneETACardUpdateWithoutZoneETAsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  masterCarrierServiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  masterCarrier?: Prisma.MasterCarrierUpdateOneRequiredWithoutZoneETACardsNestedInput
}

export type ZoneETACardUncheckedUpdateWithoutZoneETAsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  masterCarrierId?: Prisma.StringFieldUpdateOperationsInput | string
  masterCarrierServiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ZoneETACardCreateManyMasterCarrierInput = {
  id?: string
  displayName: string
  start: Date | string
  end?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  masterCarrierServiceId?: string | null
}

export type ZoneETACardUpdateWithoutMasterCarrierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  masterCarrierServiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zoneETAs?: Prisma.ZoneETAUpdateManyWithoutZoneETACardNestedInput
}

export type ZoneETACardUncheckedUpdateWithoutMasterCarrierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  masterCarrierServiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zoneETAs?: Prisma.ZoneETAUncheckedUpdateManyWithoutZoneETACardNestedInput
}

export type ZoneETACardUncheckedUpdateManyWithoutMasterCarrierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  masterCarrierServiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type ZoneETACardCountOutputType
 */

export type ZoneETACardCountOutputType = {
  zoneETAs: number
}

export type ZoneETACardCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  zoneETAs?: boolean | ZoneETACardCountOutputTypeCountZoneETAsArgs
}

/**
 * ZoneETACardCountOutputType without action
 */
export type ZoneETACardCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACardCountOutputType
   */
  select?: Prisma.ZoneETACardCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ZoneETACardCountOutputType without action
 */
export type ZoneETACardCountOutputTypeCountZoneETAsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ZoneETAWhereInput
}


export type ZoneETACardSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  displayName?: boolean
  start?: boolean
  end?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  masterCarrierId?: boolean
  masterCarrierServiceId?: boolean
  zoneETAs?: boolean | Prisma.ZoneETACard$zoneETAsArgs<ExtArgs>
  masterCarrier?: boolean | Prisma.MasterCarrierDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.ZoneETACardCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["zoneETACard"]>

export type ZoneETACardSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  displayName?: boolean
  start?: boolean
  end?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  masterCarrierId?: boolean
  masterCarrierServiceId?: boolean
  masterCarrier?: boolean | Prisma.MasterCarrierDefaultArgs<ExtArgs>
}, ExtArgs["result"]["zoneETACard"]>

export type ZoneETACardSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  displayName?: boolean
  start?: boolean
  end?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  masterCarrierId?: boolean
  masterCarrierServiceId?: boolean
  masterCarrier?: boolean | Prisma.MasterCarrierDefaultArgs<ExtArgs>
}, ExtArgs["result"]["zoneETACard"]>

export type ZoneETACardSelectScalar = {
  id?: boolean
  displayName?: boolean
  start?: boolean
  end?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  masterCarrierId?: boolean
  masterCarrierServiceId?: boolean
}

export type ZoneETACardOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "displayName" | "start" | "end" | "createdAt" | "updatedAt" | "masterCarrierId" | "masterCarrierServiceId", ExtArgs["result"]["zoneETACard"]>
export type ZoneETACardInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  zoneETAs?: boolean | Prisma.ZoneETACard$zoneETAsArgs<ExtArgs>
  masterCarrier?: boolean | Prisma.MasterCarrierDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.ZoneETACardCountOutputTypeDefaultArgs<ExtArgs>
}
export type ZoneETACardIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  masterCarrier?: boolean | Prisma.MasterCarrierDefaultArgs<ExtArgs>
}
export type ZoneETACardIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  masterCarrier?: boolean | Prisma.MasterCarrierDefaultArgs<ExtArgs>
}

export type $ZoneETACardPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ZoneETACard"
  objects: {
    zoneETAs: Prisma.$ZoneETAPayload<ExtArgs>[]
    masterCarrier: Prisma.$MasterCarrierPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    displayName: string
    start: Date
    end: Date | null
    createdAt: Date
    updatedAt: Date
    masterCarrierId: string
    masterCarrierServiceId: string | null
  }, ExtArgs["result"]["zoneETACard"]>
  composites: {}
}

export type ZoneETACardGetPayload<S extends boolean | null | undefined | ZoneETACardDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ZoneETACardPayload, S>

export type ZoneETACardCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ZoneETACardFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ZoneETACardCountAggregateInputType | true
  }

export interface ZoneETACardDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ZoneETACard'], meta: { name: 'ZoneETACard' } }
  /**
   * Find zero or one ZoneETACard that matches the filter.
   * @param {ZoneETACardFindUniqueArgs} args - Arguments to find a ZoneETACard
   * @example
   * // Get one ZoneETACard
   * const zoneETACard = await prisma.zoneETACard.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ZoneETACardFindUniqueArgs>(args: Prisma.SelectSubset<T, ZoneETACardFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ZoneETACardClient<runtime.Types.Result.GetResult<Prisma.$ZoneETACardPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ZoneETACard that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ZoneETACardFindUniqueOrThrowArgs} args - Arguments to find a ZoneETACard
   * @example
   * // Get one ZoneETACard
   * const zoneETACard = await prisma.zoneETACard.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ZoneETACardFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ZoneETACardFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ZoneETACardClient<runtime.Types.Result.GetResult<Prisma.$ZoneETACardPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ZoneETACard that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ZoneETACardFindFirstArgs} args - Arguments to find a ZoneETACard
   * @example
   * // Get one ZoneETACard
   * const zoneETACard = await prisma.zoneETACard.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ZoneETACardFindFirstArgs>(args?: Prisma.SelectSubset<T, ZoneETACardFindFirstArgs<ExtArgs>>): Prisma.Prisma__ZoneETACardClient<runtime.Types.Result.GetResult<Prisma.$ZoneETACardPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ZoneETACard that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ZoneETACardFindFirstOrThrowArgs} args - Arguments to find a ZoneETACard
   * @example
   * // Get one ZoneETACard
   * const zoneETACard = await prisma.zoneETACard.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ZoneETACardFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ZoneETACardFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ZoneETACardClient<runtime.Types.Result.GetResult<Prisma.$ZoneETACardPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ZoneETACards that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ZoneETACardFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ZoneETACards
   * const zoneETACards = await prisma.zoneETACard.findMany()
   * 
   * // Get first 10 ZoneETACards
   * const zoneETACards = await prisma.zoneETACard.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const zoneETACardWithIdOnly = await prisma.zoneETACard.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ZoneETACardFindManyArgs>(args?: Prisma.SelectSubset<T, ZoneETACardFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ZoneETACardPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ZoneETACard.
   * @param {ZoneETACardCreateArgs} args - Arguments to create a ZoneETACard.
   * @example
   * // Create one ZoneETACard
   * const ZoneETACard = await prisma.zoneETACard.create({
   *   data: {
   *     // ... data to create a ZoneETACard
   *   }
   * })
   * 
   */
  create<T extends ZoneETACardCreateArgs>(args: Prisma.SelectSubset<T, ZoneETACardCreateArgs<ExtArgs>>): Prisma.Prisma__ZoneETACardClient<runtime.Types.Result.GetResult<Prisma.$ZoneETACardPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ZoneETACards.
   * @param {ZoneETACardCreateManyArgs} args - Arguments to create many ZoneETACards.
   * @example
   * // Create many ZoneETACards
   * const zoneETACard = await prisma.zoneETACard.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ZoneETACardCreateManyArgs>(args?: Prisma.SelectSubset<T, ZoneETACardCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ZoneETACards and returns the data saved in the database.
   * @param {ZoneETACardCreateManyAndReturnArgs} args - Arguments to create many ZoneETACards.
   * @example
   * // Create many ZoneETACards
   * const zoneETACard = await prisma.zoneETACard.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ZoneETACards and only return the `id`
   * const zoneETACardWithIdOnly = await prisma.zoneETACard.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ZoneETACardCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ZoneETACardCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ZoneETACardPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ZoneETACard.
   * @param {ZoneETACardDeleteArgs} args - Arguments to delete one ZoneETACard.
   * @example
   * // Delete one ZoneETACard
   * const ZoneETACard = await prisma.zoneETACard.delete({
   *   where: {
   *     // ... filter to delete one ZoneETACard
   *   }
   * })
   * 
   */
  delete<T extends ZoneETACardDeleteArgs>(args: Prisma.SelectSubset<T, ZoneETACardDeleteArgs<ExtArgs>>): Prisma.Prisma__ZoneETACardClient<runtime.Types.Result.GetResult<Prisma.$ZoneETACardPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ZoneETACard.
   * @param {ZoneETACardUpdateArgs} args - Arguments to update one ZoneETACard.
   * @example
   * // Update one ZoneETACard
   * const zoneETACard = await prisma.zoneETACard.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ZoneETACardUpdateArgs>(args: Prisma.SelectSubset<T, ZoneETACardUpdateArgs<ExtArgs>>): Prisma.Prisma__ZoneETACardClient<runtime.Types.Result.GetResult<Prisma.$ZoneETACardPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ZoneETACards.
   * @param {ZoneETACardDeleteManyArgs} args - Arguments to filter ZoneETACards to delete.
   * @example
   * // Delete a few ZoneETACards
   * const { count } = await prisma.zoneETACard.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ZoneETACardDeleteManyArgs>(args?: Prisma.SelectSubset<T, ZoneETACardDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ZoneETACards.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ZoneETACardUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ZoneETACards
   * const zoneETACard = await prisma.zoneETACard.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ZoneETACardUpdateManyArgs>(args: Prisma.SelectSubset<T, ZoneETACardUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ZoneETACards and returns the data updated in the database.
   * @param {ZoneETACardUpdateManyAndReturnArgs} args - Arguments to update many ZoneETACards.
   * @example
   * // Update many ZoneETACards
   * const zoneETACard = await prisma.zoneETACard.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ZoneETACards and only return the `id`
   * const zoneETACardWithIdOnly = await prisma.zoneETACard.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ZoneETACardUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ZoneETACardUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ZoneETACardPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ZoneETACard.
   * @param {ZoneETACardUpsertArgs} args - Arguments to update or create a ZoneETACard.
   * @example
   * // Update or create a ZoneETACard
   * const zoneETACard = await prisma.zoneETACard.upsert({
   *   create: {
   *     // ... data to create a ZoneETACard
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ZoneETACard we want to update
   *   }
   * })
   */
  upsert<T extends ZoneETACardUpsertArgs>(args: Prisma.SelectSubset<T, ZoneETACardUpsertArgs<ExtArgs>>): Prisma.Prisma__ZoneETACardClient<runtime.Types.Result.GetResult<Prisma.$ZoneETACardPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ZoneETACards.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ZoneETACardCountArgs} args - Arguments to filter ZoneETACards to count.
   * @example
   * // Count the number of ZoneETACards
   * const count = await prisma.zoneETACard.count({
   *   where: {
   *     // ... the filter for the ZoneETACards we want to count
   *   }
   * })
  **/
  count<T extends ZoneETACardCountArgs>(
    args?: Prisma.Subset<T, ZoneETACardCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ZoneETACardCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ZoneETACard.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ZoneETACardAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ZoneETACardAggregateArgs>(args: Prisma.Subset<T, ZoneETACardAggregateArgs>): Prisma.PrismaPromise<GetZoneETACardAggregateType<T>>

  /**
   * Group by ZoneETACard.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ZoneETACardGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ZoneETACardGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ZoneETACardGroupByArgs['orderBy'] }
      : { orderBy?: ZoneETACardGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ZoneETACardGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetZoneETACardGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ZoneETACard model
 */
readonly fields: ZoneETACardFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ZoneETACard.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ZoneETACardClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  zoneETAs<T extends Prisma.ZoneETACard$zoneETAsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ZoneETACard$zoneETAsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ZoneETAPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  masterCarrier<T extends Prisma.MasterCarrierDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MasterCarrierDefaultArgs<ExtArgs>>): Prisma.Prisma__MasterCarrierClient<runtime.Types.Result.GetResult<Prisma.$MasterCarrierPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ZoneETACard model
 */
export interface ZoneETACardFieldRefs {
  readonly id: Prisma.FieldRef<"ZoneETACard", 'String'>
  readonly displayName: Prisma.FieldRef<"ZoneETACard", 'String'>
  readonly start: Prisma.FieldRef<"ZoneETACard", 'DateTime'>
  readonly end: Prisma.FieldRef<"ZoneETACard", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ZoneETACard", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ZoneETACard", 'DateTime'>
  readonly masterCarrierId: Prisma.FieldRef<"ZoneETACard", 'String'>
  readonly masterCarrierServiceId: Prisma.FieldRef<"ZoneETACard", 'String'>
}
    

// Custom InputTypes
/**
 * ZoneETACard findUnique
 */
export type ZoneETACardFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACard
   */
  select?: Prisma.ZoneETACardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETACard
   */
  omit?: Prisma.ZoneETACardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETACardInclude<ExtArgs> | null
  /**
   * Filter, which ZoneETACard to fetch.
   */
  where: Prisma.ZoneETACardWhereUniqueInput
}

/**
 * ZoneETACard findUniqueOrThrow
 */
export type ZoneETACardFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACard
   */
  select?: Prisma.ZoneETACardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETACard
   */
  omit?: Prisma.ZoneETACardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETACardInclude<ExtArgs> | null
  /**
   * Filter, which ZoneETACard to fetch.
   */
  where: Prisma.ZoneETACardWhereUniqueInput
}

/**
 * ZoneETACard findFirst
 */
export type ZoneETACardFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACard
   */
  select?: Prisma.ZoneETACardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETACard
   */
  omit?: Prisma.ZoneETACardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETACardInclude<ExtArgs> | null
  /**
   * Filter, which ZoneETACard to fetch.
   */
  where?: Prisma.ZoneETACardWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ZoneETACards to fetch.
   */
  orderBy?: Prisma.ZoneETACardOrderByWithRelationInput | Prisma.ZoneETACardOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ZoneETACards.
   */
  cursor?: Prisma.ZoneETACardWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ZoneETACards from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ZoneETACards.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ZoneETACards.
   */
  distinct?: Prisma.ZoneETACardScalarFieldEnum | Prisma.ZoneETACardScalarFieldEnum[]
}

/**
 * ZoneETACard findFirstOrThrow
 */
export type ZoneETACardFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACard
   */
  select?: Prisma.ZoneETACardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETACard
   */
  omit?: Prisma.ZoneETACardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETACardInclude<ExtArgs> | null
  /**
   * Filter, which ZoneETACard to fetch.
   */
  where?: Prisma.ZoneETACardWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ZoneETACards to fetch.
   */
  orderBy?: Prisma.ZoneETACardOrderByWithRelationInput | Prisma.ZoneETACardOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ZoneETACards.
   */
  cursor?: Prisma.ZoneETACardWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ZoneETACards from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ZoneETACards.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ZoneETACards.
   */
  distinct?: Prisma.ZoneETACardScalarFieldEnum | Prisma.ZoneETACardScalarFieldEnum[]
}

/**
 * ZoneETACard findMany
 */
export type ZoneETACardFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACard
   */
  select?: Prisma.ZoneETACardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETACard
   */
  omit?: Prisma.ZoneETACardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETACardInclude<ExtArgs> | null
  /**
   * Filter, which ZoneETACards to fetch.
   */
  where?: Prisma.ZoneETACardWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ZoneETACards to fetch.
   */
  orderBy?: Prisma.ZoneETACardOrderByWithRelationInput | Prisma.ZoneETACardOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ZoneETACards.
   */
  cursor?: Prisma.ZoneETACardWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ZoneETACards from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ZoneETACards.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ZoneETACards.
   */
  distinct?: Prisma.ZoneETACardScalarFieldEnum | Prisma.ZoneETACardScalarFieldEnum[]
}

/**
 * ZoneETACard create
 */
export type ZoneETACardCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACard
   */
  select?: Prisma.ZoneETACardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETACard
   */
  omit?: Prisma.ZoneETACardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETACardInclude<ExtArgs> | null
  /**
   * The data needed to create a ZoneETACard.
   */
  data: Prisma.XOR<Prisma.ZoneETACardCreateInput, Prisma.ZoneETACardUncheckedCreateInput>
}

/**
 * ZoneETACard createMany
 */
export type ZoneETACardCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ZoneETACards.
   */
  data: Prisma.ZoneETACardCreateManyInput | Prisma.ZoneETACardCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ZoneETACard createManyAndReturn
 */
export type ZoneETACardCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACard
   */
  select?: Prisma.ZoneETACardSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETACard
   */
  omit?: Prisma.ZoneETACardOmit<ExtArgs> | null
  /**
   * The data used to create many ZoneETACards.
   */
  data: Prisma.ZoneETACardCreateManyInput | Prisma.ZoneETACardCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETACardIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ZoneETACard update
 */
export type ZoneETACardUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACard
   */
  select?: Prisma.ZoneETACardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETACard
   */
  omit?: Prisma.ZoneETACardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETACardInclude<ExtArgs> | null
  /**
   * The data needed to update a ZoneETACard.
   */
  data: Prisma.XOR<Prisma.ZoneETACardUpdateInput, Prisma.ZoneETACardUncheckedUpdateInput>
  /**
   * Choose, which ZoneETACard to update.
   */
  where: Prisma.ZoneETACardWhereUniqueInput
}

/**
 * ZoneETACard updateMany
 */
export type ZoneETACardUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ZoneETACards.
   */
  data: Prisma.XOR<Prisma.ZoneETACardUpdateManyMutationInput, Prisma.ZoneETACardUncheckedUpdateManyInput>
  /**
   * Filter which ZoneETACards to update
   */
  where?: Prisma.ZoneETACardWhereInput
  /**
   * Limit how many ZoneETACards to update.
   */
  limit?: number
}

/**
 * ZoneETACard updateManyAndReturn
 */
export type ZoneETACardUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACard
   */
  select?: Prisma.ZoneETACardSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETACard
   */
  omit?: Prisma.ZoneETACardOmit<ExtArgs> | null
  /**
   * The data used to update ZoneETACards.
   */
  data: Prisma.XOR<Prisma.ZoneETACardUpdateManyMutationInput, Prisma.ZoneETACardUncheckedUpdateManyInput>
  /**
   * Filter which ZoneETACards to update
   */
  where?: Prisma.ZoneETACardWhereInput
  /**
   * Limit how many ZoneETACards to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETACardIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ZoneETACard upsert
 */
export type ZoneETACardUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACard
   */
  select?: Prisma.ZoneETACardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETACard
   */
  omit?: Prisma.ZoneETACardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETACardInclude<ExtArgs> | null
  /**
   * The filter to search for the ZoneETACard to update in case it exists.
   */
  where: Prisma.ZoneETACardWhereUniqueInput
  /**
   * In case the ZoneETACard found by the `where` argument doesn't exist, create a new ZoneETACard with this data.
   */
  create: Prisma.XOR<Prisma.ZoneETACardCreateInput, Prisma.ZoneETACardUncheckedCreateInput>
  /**
   * In case the ZoneETACard was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ZoneETACardUpdateInput, Prisma.ZoneETACardUncheckedUpdateInput>
}

/**
 * ZoneETACard delete
 */
export type ZoneETACardDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACard
   */
  select?: Prisma.ZoneETACardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETACard
   */
  omit?: Prisma.ZoneETACardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETACardInclude<ExtArgs> | null
  /**
   * Filter which ZoneETACard to delete.
   */
  where: Prisma.ZoneETACardWhereUniqueInput
}

/**
 * ZoneETACard deleteMany
 */
export type ZoneETACardDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ZoneETACards to delete
   */
  where?: Prisma.ZoneETACardWhereInput
  /**
   * Limit how many ZoneETACards to delete.
   */
  limit?: number
}

/**
 * ZoneETACard.zoneETAs
 */
export type ZoneETACard$zoneETAsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETA
   */
  select?: Prisma.ZoneETASelect<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETA
   */
  omit?: Prisma.ZoneETAOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETAInclude<ExtArgs> | null
  where?: Prisma.ZoneETAWhereInput
  orderBy?: Prisma.ZoneETAOrderByWithRelationInput | Prisma.ZoneETAOrderByWithRelationInput[]
  cursor?: Prisma.ZoneETAWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ZoneETAScalarFieldEnum | Prisma.ZoneETAScalarFieldEnum[]
}

/**
 * ZoneETACard without action
 */
export type ZoneETACardDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ZoneETACard
   */
  select?: Prisma.ZoneETACardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ZoneETACard
   */
  omit?: Prisma.ZoneETACardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneETACardInclude<ExtArgs> | null
}
